id: 
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: 
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: 'Needs: Author Feedback'
      - hasLabel:
          label: no-recent-activity
      - noActivitySince:
          days: 7
      actions:
      - closeIssue
    - description: 
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: 'Needs: Author Feedback'
      - noActivitySince:
          days: 7
      - isNotLabeledWith:
          label: no-recent-activity
      actions:
      - addLabel:
          label: no-recent-activity
      - addReply:
          reply: This issue has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **7 days**. It will be closed if no further activity occurs **within 7 days of this comment**.
    - description: 
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: 'Resolution: Duplicate'
      - noActivitySince:
          days: 1
      actions:
      - addReply:
          reply: This issue has been marked as duplicate and has not had any activity for **1 day**. It will be closed for housekeeping purposes.
      - closeIssue
    - description: 
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isPullRequest
      - isOpen
      - hasLabel:
          label: 'Needs: Author Feedback'
      - hasLabel:
          label: no-recent-activity
      - noActivitySince:
          days: 7
      actions:
      - closeIssue
    - description: 
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isPullRequest
      - isOpen
      - hasLabel:
          label: 'Needs: Author Feedback'
      - noActivitySince:
          days: 7
      - isNotLabeledWith:
          label: no-recent-activity
      actions:
      - addLabel:
          label: no-recent-activity
      - addReply:
          reply: This pull request has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **7 days**. It will be closed if no further activity occurs **within 7 days of this comment**.
    - description: 
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isOpen
      - hasLabel:
          label: .NET Archive
      actions:
      - removeLabel:
          label: .NET Archive
      - addReply:
          reply: We are not investing in new features or lower priority bug fixes on the C# implementation of React Native for Windows (previously known as "vCurrent"). All investment moving forward is in the C++ infrastructure (previously known as "vNext") and that is the only option as of 0.61 (and was the default as of 0.60). If this issue is still relevant on the modern implementation please open a new issue. If this issue is of significant severity for a vCurrent app and vNext is not an option, re-open with justification.
      - closeIssue
    - description: 
      frequencies:
      - hourly:
          hour: 6
      filters:
      - hasLabel:
          label: WPF Archive
      - isOpen
      actions:
      - removeLabel:
          label: WPF Archive
      - addReply:
          reply: We are not investing in new features or lower priority bug fixes for the WPF implementation of React Native for Windows. All investment is now in UWP XAML. If this issue is still relevant on the UWP XAML implementation please open a new issue. If this issue is of significant severity for a WPF app and UWP XAML is not an option, re-open with justification.
      - closeIssue
    - description: 
      frequencies:
      - daily:
          time: 13:0
      filters:
      - isOpen
      - isNotLabeledWith:
          label: 'Needs: Triage :mag:'
      - isNotLabeledWith:
          label: Invalid Triage
      - isIssue
      - isNotInAnyMilestone
      - isNotLabeledWith:
          label: 'Needs: Author Feedback'
      - isNotLabeledWith:
          label: 'Needs: Attention :wave:'
      actions:
      - addLabel:
          label: Invalid Triage
    - description: 
      frequencies:
      - daily:
          time: 13:0
      filters:
      - isOpen
      - isNotLabeledWith:
          label: Invalid Triage
      - isNotLabeledWith:
          label: 'Needs: Triage :mag:'
      - isNotLabeledWith:
          label: 'Needs: Attention :wave:'
      - isNotLabeledWith:
          label: 'Needs: Author Feedback'
      - isNotLabeledWith:
          label: bug
      - isNotLabeledWith:
          label: enhancement
      - isNotLabeledWith:
          label: question
      - isIssue
      actions:
      - addLabel:
          label: Invalid Triage
    eventResponderTasks:
    - if:
      - payloadType: Issues
      - isAction:
          action: Opened
      then:
      - addLabel:
          label: 'Needs: Triage :mag:'
      description: 
    - if:
      - payloadType: Issue_Comment
      - isAction:
          action: Created
      - isActivitySender:
          issueAuthor: True
      - hasLabel:
          label: 'Needs: Author Feedback'
      then:
      - addLabel:
          label: 'Needs: Attention :wave:'
      - removeLabel:
          label: 'Needs: Author Feedback'
      description: 
    - if:
      - payloadType: Issues
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: no-recent-activity
      then:
      - removeLabel:
          label: no-recent-activity
      description: 
    - if:
      - payloadType: Pull_Request_Review
      - isAction:
          action: Submitted
      - isReviewState:
          reviewState: Changes_requested
      then:
      - addLabel:
          label: 'Needs: Author Feedback'
      description: 
    - if:
      - payloadType: Pull_Request
      - isActivitySender:
          issueAuthor: True
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: 'Needs: Author Feedback'
      then:
      - removeLabel:
          label: 'Needs: Author Feedback'
      description: 
    - if:
      - payloadType: Pull_Request
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: no-recent-activity
      then:
      - removeLabel:
          label: no-recent-activity
      description: 
    - if:
      - payloadType: Pull_Request
      - hasLabel:
          label: AutoMerge
      then:
      - enableAutoMerge:
          mergeMethod: Squash
      description: 
    - if:
      - payloadType: Pull_Request
      - labelRemoved:
          label: AutoMerge
      then:
      - disableAutoMerge
      description: 
    - if:
      - payloadType: Pull_Request
      - isAction:
          action: Opened
      then:
      - addCodeFlowLink
      description: 
    - if:
      - payloadType: Issue_Comment
      - hasLabel:
          label: no-recent-activity
      then:
      - removeLabel:
          label: no-recent-activity
      description: 
    - if:
      - payloadType: Issue_Comment
      - isActivitySender:
          issueAuthor: True
      - hasLabel:
          label: 'Needs: Author Feedback'
      then:
      - removeLabel:
          label: 'Needs: Author Feedback'
      description: 
    - if:
      - payloadType: Pull_Request_Review
      - isActivitySender:
          issueAuthor: True
      - hasLabel:
          label: 'Needs: Author Feedback'
      then:
      - removeLabel:
          label: 'Needs: Author Feedback'
      description: 
    - if:
      - payloadType: Issue_Comment
      - hasLabel:
          label: no-recent-activity
      then:
      - removeLabel:
          label: no-recent-activity
      description: 
    - if:
      - payloadType: Pull_Request_Review
      - hasLabel:
          label: no-recent-activity
      then:
      - removeLabel:
          label: no-recent-activity
      description: 
    - if:
      - payloadType: Issues
      - isAction:
          action: Opened
      - and:
        - isActivitySender:
            user: aschultz
            issueAuthor: False
        - isActivitySender:
            user: lamxdoan
            issueAuthor: False
        - isActivitySender:
            user: stecrain
            issueAuthor: False
        - isActivitySender:
            user: JakovS
            issueAuthor: False
      then:
      - addLabel:
          label: 'Partner: Xbox'
      description: 
    - if:
      - payloadType: Issues
      - isAction:
          action: Opened
      - or:
        - isActivitySender:
            user: Tatious
            issueAuthor: False
        - isActivitySender:
            user: namrog84
            issueAuthor: False
      then:
      - addLabel:
          label: 'Partner: Stream'
      description: 
    - if:
      - payloadType: Issues
      - labelAdded:
          label: 'Needs: Environment Info'
      then:
      - addReply:
          reply: >-
            This issue lacks the environment info requested in the bug template. Please edit your issue report to add this information.


            If you are using latest version:

            1. `npx react-native --version`:

            2. `npx react-native run-windows --info`:


            Otherwise if `--info` doesn't exist:

            1. `react-native -v`:

            2. `npm ls rnpm-plugin-windows`:

            3. `npm ls react-native-windows`:

            4. `node -v`:

            5. `npm -v`:

            6. `yarn --version`<!-- (if you use Yarn) -->:
      - addLabel:
          label: 'Needs: Author Feedback'
      - removeLabel:
          label: 'Needs: Triage :mag:'
      description: 
    - if:
      - payloadType: Issues
      - isAction:
          action: Opened
      - or:
        - isActivitySender:
            user: TheSavior
            issueAuthor: False
        - isActivitySender:
            user: fmsanchez
            issueAuthor: False
        - isActivitySender:
            user: AkshatGiri
            issueAuthor: False
        - isActivitySender:
            user: sahrens
            issueAuthor: False
        - isActivitySender:
            user: jackerghan
            issueAuthor: False
        - isActivitySender:
            user: appden
            issueAuthor: False
        - isActivitySender:
            user: lyahdav
            issueAuthor: False
        - isActivitySender:
            user: rozele
            issueAuthor: False
      then:
      - addLabel:
          label: 'Partner: Facebook'
      description: 
    - if:
      - payloadType: Issues
      - labelAdded:
          label: 'Needs: Verify on Latest Version'
      then:
      - addReply:
          reply: >
            This issue is reported on an older version of React Native for Windows than is current, and is believed to be fixed in the latest version. Please try to update to the latest version and confirm if your issue still occurs.

            Per-version documentation is available [here](https://microsoft.github.io/react-native-windows/versions)
      - addLabel:
          label: 'Needs: Author Feedback'
      - removeLabel:
          label: 'Needs: Triage :mag:'
      description: 
    - if:
      - payloadType: Pull_Request
      then:
      - labelSync:
          pattern: 'Area:'
      - labelSync:
          pattern: 'Platform:'
      - labelSync:
          pattern: Breaking Change
      - labelSync:
          pattern: Backport
      description: 
    - if:
      - payloadType: Issues
      - labelAdded:
          label: 'Resolution: For StackOverflow'
      - isOpen
      then:
      - addReply:
          reply: We use github to track issues exclusive to React Native for Windows. This issue seems to pertain to something outside of that scope. Please try asking over on [Stack Overflow](https://stackoverflow.com/questions/tagged/uwp) as it is better suited for general Windows platform questions.
      - closeIssue
      description: 
    - if:
      - payloadType: Issues
      - isAction:
          action: Opened
      - or:
        - isActivitySender:
            user: joshyAbraham
            issueAuthor: False
      then:
      - addLabel:
          label: 'Partner: 3P'
      description: 
    - if:
      - payloadType: Issues
      - isAction:
          action: Closed
      then:
      - removeLabel:
          label: 'Needs: Triage :mag:'
      - removeLabel:
          label: 'Needs: Attention :wave:'
      description: 
    - if:
      - payloadType: Issues
      - isAction:
          action: Opened
      - or:
        - isActivitySender:
            user: KAnder425
            issueAuthor: False
      then:
      - addLabel:
          label: 'Partner: Office'
      description: 
    - if:
      - payloadType: Issues
      - isAction:
          action: Opened
      - or:
        - isActivitySender:
            user: stratospheres
            issueAuthor: False
      then:
      - addLabel:
          label: 'Partner: Microsoft'
      description: 
    - if:
      - payloadType: Issues
      - labelAdded:
          label: "Resolution: Won't Fix"
      then:
      - addReply:
          reply: There is no immediate intention to take a fix for this issue. In an intent to create clear expectations, the issue has been closed. The issue still exists and may be referred to and commented on. If additional justification is made, it may be reactivated in the future.
      - closeIssue
      description: 
onFailure: 
onSuccess: 
