// AutolinkedNativeModules.g.cs contents generated by "npx @react-native-community/cli autolink-windows"

using System.Collections.Generic;{{ &autolinkCsUsingNamespaces }}

using Microsoft.ReactNative;

namespace Microsoft.ReactNative.Managed
{
    internal static class AutolinkedNativeModules
    {
        internal static void RegisterAutolinkedNativeModulePackages(IList<IReactPackageProvider> packageProviders)
        { {{ &autolinkCsReactPackageProviders }}
        }
    }
}
