
namespace facebook.react {

interface INativeTraceHandler
{
	void JSBeginSection(String profileName, String args);
	void JSEndSection();
	void JSBeginAsyncSection(String profileName, UInt32 cookie);
	void JSEndAsyncSection(String profileName, UInt32 cookie);
	void JSCounter(String profileName, UInt32 value);

	void NativeBeginSection(String profileName, String args);
	void NativeEndSection(String profileName, String args, Int64 durationInNanoseconds);
};

static runtimeclass NativeTraceEventSource
{
	// Delegates/events would be a better idiom. However, currently I only aim to create ABI-safety
	// for the existing interface, not to redesign it.
	static UInt32 InitializeTracing(INativeTraceHandler handler);
	static void UninitializeTracing(UInt32 cookie);
}

}
