// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import "inspectable.idl";
import "Windows.Foundation.idl";
import "Windows.UI.Xaml.Controls.idl";

#define VERSION 1.0
#include "Module.idl"
#include "Instance.idl"
#include "ReactControl.idl"

namespace react.uwp
{

}
