namespace facebook.react {

// ABI_REVIEW:
// representing
//     std::function<void()>
// arguments to MessageQueueThread::runOnQueue(), MessageQueueThread::runOnQueueSync() methods.
delegate void QueueItem();

interface IMessageQueue
{
	void Run(QueueItem item);
	void RunSync(QueueItem item);
	void QuitSync();
};

}
