import "IJSValueReader.idl";
import "IJSValueWriter.idl";

namespace Microsoft.Internal {

  static runtimeclass TestController {
    static Microsoft.ReactNative.IJSValueReader CreateDynamicReader(Microsoft.ReactNative.IJSValueWriter writer);
    static Microsoft.ReactNative.IJSValueWriter CreateDynamicWriter();
  };

}
