import "IJSValueReader.idl";

namespace Microsoft.Internal {

  static runtimeclass TestController {
    // Microsoft.ReactNative.IJSValueReader CreateJSValueReader();
    static String HelloWorld();
  };

}
