// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once

WINRT_EXPORT namespace winrt::Windows::Foundation {

struct Uri;

}

WINRT_EXPORT namespace winrt::react::uwp::image {

enum class ResizeMode : int32_t
{
    Cover = 0,
    Contain = 1,
    Stretch = 2,
    Repeat = 3,
    Center = 4,
};

struct IReactImageBrush;
struct ReactImageBrush;

}

namespace winrt::impl {

template <> struct category<react::uwp::image::IReactImageBrush>{ using type = interface_category; };
template <> struct category<react::uwp::image::ReactImageBrush>{ using type = class_category; };
template <> struct category<react::uwp::image::ResizeMode>{ using type = enum_category; };
template <> struct name<react::uwp::image::IReactImageBrush>{ static constexpr auto & value{ L"react.uwp.image.IReactImageBrush" }; };
template <> struct name<react::uwp::image::ReactImageBrush>{ static constexpr auto & value{ L"react.uwp.image.ReactImageBrush" }; };
template <> struct name<react::uwp::image::ResizeMode>{ static constexpr auto & value{ L"react.uwp.image.ResizeMode" }; };
template <> struct guid_storage<react::uwp::image::IReactImageBrush>{ static constexpr guid value{ 0x9672DBF3,0xAC79,0x5057,{ 0xBE,0x51,0x03,0xB3,0x79,0x9D,0x89,0xEC } }; };
template <> struct default_interface<react::uwp::image::ReactImageBrush>{ using type = react::uwp::image::IReactImageBrush; };

template <> struct abi<react::uwp::image::IReactImageBrush>{ struct type : IInspectable
{
    virtual int32_t WINRT_CALL get_ResizeMode(react::uwp::image::ResizeMode* value) noexcept = 0;
    virtual int32_t WINRT_CALL put_ResizeMode(react::uwp::image::ResizeMode value) noexcept = 0;
    virtual int32_t WINRT_CALL get_SourceUri(void** value) noexcept = 0;
    virtual int32_t WINRT_CALL put_SourceUri(void* value) noexcept = 0;
};};

template <typename D>
struct consume_react_uwp_image_IReactImageBrush
{
    react::uwp::image::ResizeMode ResizeMode() const;
    void ResizeMode(react::uwp::image::ResizeMode const& value) const;
    Windows::Foundation::Uri SourceUri() const;
    void SourceUri(Windows::Foundation::Uri const& value) const;
};
template <> struct consume<react::uwp::image::IReactImageBrush> { template <typename D> using type = consume_react_uwp_image_IReactImageBrush<D>; };

}
