// WARNING: Please don't edit this file. It was generated by C++/WinRT
// v1.0.190111.3

#pragma once
#include "winrt/impl/Windows.UI.Composition.0.h"
#include "winrt/impl/Windows.UI.Xaml.0.h"
#include "winrt/impl/Windows.UI.Xaml.Automation.0.h"
#include "winrt/impl/Windows.UI.Xaml.Automation.Provider.0.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.0.h"
#include "winrt/impl/Windows.UI.Xaml.Media.0.h"
#include "winrt/impl/react.uwp.0.h"

WINRT_EXPORT namespace winrt::react::uwp {
  struct WINRT_EBO IDynamicAutomationPeer
      : Windows::Foundation::IInspectable,
        impl::consume_t<IDynamicAutomationPeer> {
    IDynamicAutomationPeer(std::nullptr_t = nullptr) noexcept {}
  };

  struct WINRT_EBO IDynamicAutomationPeerFactory
      : Windows::Foundation::IInspectable,
        impl::consume_t<IDynamicAutomationPeerFactory> {
    IDynamicAutomationPeerFactory(std::nullptr_t = nullptr) noexcept {}
  };

  struct WINRT_EBO IDynamicAutomationProperties
      : Windows::Foundation::IInspectable,
        impl::consume_t<IDynamicAutomationProperties> {
    IDynamicAutomationProperties(std::nullptr_t = nullptr) noexcept {}
  };

  struct WINRT_EBO IDynamicAutomationPropertiesStatics
      : Windows::Foundation::IInspectable,
        impl::consume_t<IDynamicAutomationPropertiesStatics> {
    IDynamicAutomationPropertiesStatics(std::nullptr_t = nullptr) noexcept {}
  };

  struct WINRT_EBO IViewControl : Windows::Foundation::IInspectable,
                                  impl::consume_t<IViewControl> {
    IViewControl(std::nullptr_t = nullptr) noexcept {}
  };

  struct WINRT_EBO IViewPanel : Windows::Foundation::IInspectable,
                                impl::consume_t<IViewPanel> {
    IViewPanel(std::nullptr_t = nullptr) noexcept {}
  };

  struct WINRT_EBO IViewPanelStatics : Windows::Foundation::IInspectable,
                                       impl::consume_t<IViewPanelStatics> {
    IViewPanelStatics(std::nullptr_t = nullptr) noexcept {}
  };
}
