// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#pragma once
#include "winrt/impl/Windows.UI.Xaml.0.h"
#include "winrt/impl/Windows.UI.Xaml.Automation.Provider.0.h"
#include "winrt/impl/Windows.UI.Xaml.Automation.Peers.0.h"
#include "winrt/impl/react.uwp.0.h"

WINRT_EXPORT namespace winrt::react::uwp {

struct WINRT_EBO IDynamicAutomationPeer :
    Windows::Foundation::IInspectable,
    impl::consume_t<IDynamicAutomationPeer>
{
    IDynamicAutomationPeer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IDynamicAutomationPeerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IDynamicAutomationPeerFactory>
{
    IDynamicAutomationPeerFactory(std::nullptr_t = nullptr) noexcept {}
};

}
