// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/Windows.Foundation.0.h"
#include "winrt/impl/Windows.UI.Composition.0.h"
#include "winrt/impl/Windows.UI.Xaml.0.h"
#include "winrt/impl/Windows.UI.Xaml.Media.0.h"
#include "winrt/impl/react.uwp.image.0.h"

WINRT_EXPORT namespace winrt::react::uwp::image {

struct WINRT_EBO IReactImageBrush :
    Windows::Foundation::IInspectable,
    impl::consume_t<IReactImageBrush>
{
    IReactImageBrush(std::nullptr_t = nullptr) noexcept {}
};

}
