// AutolinkedNativeModules.g.h contents generated by "react-native autolink-windows"
#pragma once

namespace winrt::Microsoft::ReactNative {

void RegisterAutolinkedNativeModulePackages(
    winrt::Windows::Foundation::Collections::IVector<winrt::Microsoft::ReactNative::IReactPackageProvider> const
        &packageProviders);

}
