//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Playground-Win32.rc
//
#define IDC_PLAYGROUND_WIN32 100
#define IDD_ABOUTBOX 100
#define IDC_WEBDEBUGGER 100
#define IDC_JSBUNDLELIST 100
#define IDM_ABOUT 100
#define IDD_SETTINGSBOX 101
#define IDC_LIVERELOAD 101
#define IDM_EXIT 101
#define IDC_REUSEINSTANCE 102
#define IDD_OPENJSBUNDLEBOX 102
#define IDM_OPENJSFILE 102
#define IDC_DIRECTDEBUGGER 103
#define IDM_SETTINGS 103
#define IDC_BREAKONNEXTLINE 104
#define IDM_REFRESH 104
#define IDC_JSENGINE 105
#define IDM_NEWWINDOW 105
#define IDC_DEBUGGERPORT 106
#define IDC_DEBUGGERPORTLABEL 107
#define IDI_ICON1 1008

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC 1
#define _APS_NEXT_RESOURCE_VALUE 1009
#define _APS_NEXT_COMMAND_VALUE 40006
#define _APS_NEXT_CONTROL_VALUE 1001
#define _APS_NEXT_SYMED_VALUE 102
#endif
#endif
