// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// The AccessibilityAction must be in the project namespace to be
// usable by Xaml dependency properties.
// We use a macro to be able to change it from the project file.
#ifndef PROJECT_ROOT_NAMESPACE
#define PROJECT_ROOT_NAMESPACE react.uwp
#endif

namespace PROJECT_ROOT_NAMESPACE
{
  [version(1)]
  struct AccessibilityAction
  {		
      String Name;
      String Label;
  };
}
