// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

namespace react.uwp
{
  [version(1)]
  struct AccessibilityAction {		
      String Name;
      String Label;
  };
}
