namespace Microsoft.UI.Composition.Effects
{
    [version(1)]
    typedef enum CanvasEdgeBehavior
    {
        Clamp = (int)0,
        Wrap = (int)1,
        Mirror = (int)2
    } CanvasEdgeBehavior;

    runtimeclass BorderEffect;

    [version(1)]
    [uuid(31602441-15db-5b4a-98dd-ba4247548b40), exclusiveto(BorderEffect)]
    interface IBorderEffect : IInspectable
    {
        [propget] HRESULT ExtendX([out, retval] Microsoft.UI.Composition.Effects.CanvasEdgeBehavior* value);
        [propput] HRESULT ExtendX([in] Microsoft.UI.Composition.Effects.CanvasEdgeBehavior value);

        [propget] HRESULT ExtendY([out, retval] Microsoft.UI.Composition.Effects.CanvasEdgeBehavior* value);
        [propput] HRESULT ExtendY([in] Microsoft.UI.Composition.Effects.CanvasEdgeBehavior value);

        [propget] HRESULT Source([out, retval] Windows.Graphics.Effects.IGraphicsEffectSource** source);
        [propput] HRESULT Source([in] Windows.Graphics.Effects.IGraphicsEffectSource* source);
    };

    runtimeclass BorderEffect
        : [default] IBorderEffect, Windows.Graphics.Effects.IGraphicsEffect
    {
    }
}
