// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// This file was used to generate the files in the cppwinrt subfolders
//
// If you modify this file, be sure to run buildcppwinrt.cmd in this folder
// to generate new headers

import "DynamicAutomationPeer.idl";

#include "../../../include/NamespaceRedirect.h"

// The ViewPanel must be in the project namespace to be
// usable by Xaml dependency properties.
// We use a macro to be able to change it from the project file.
#ifndef PROJECT_ROOT_NAMESPACE
#define PROJECT_ROOT_NAMESPACE react.uwp
#endif

namespace PROJECT_ROOT_NAMESPACE
{
  [default_interface]
  [webhosthidden]
  runtimeclass ViewPanel : XAML_NAMESPACE.Controls.Panel
  {
    // Constructors
    ViewPanel();

    // Public Methods
    void InsertAt(UInt32 index, WUXMUX_TYPE(UIElement) value);
      void RemoveAt(UInt32 index);
      void Clear();

    void FinalizeProperties();
      WUXMUX_TYPE(Controls.Border) GetOuterBorder();

    // Public Properties
    WUXMUX_TYPE(Media.Brush) ViewBackground { get; set; };
    WUXMUX_TYPE(Thickness) BorderThickness { get; set; };
    WUXMUX_TYPE(Media.Brush) BorderBrush { get; set; };
    WUXMUX_TYPE(CornerRadius) CornerRadius { get; set; };
    Boolean ClipChildren { get; set; };

    // ViewPanel Properties
    static WUXMUX_TYPE(DependencyProperty) ViewBackgroundProperty { get; };
    static WUXMUX_TYPE(DependencyProperty) BorderThicknessProperty { get; };
    static WUXMUX_TYPE(DependencyProperty) BorderBrushProperty { get; };
    static WUXMUX_TYPE(DependencyProperty) CornerRadiusProperty { get; };
    static WUXMUX_TYPE(DependencyProperty) ClipChildrenProperty { get; };

    // Attached Properties
    static WUXMUX_TYPE(DependencyProperty) TopProperty { get; };
    static void SetTop(WUXMUX_TYPE(UIElement) element, Double value);
    static Double GetTop(WUXMUX_TYPE(UIElement) element);

    static WUXMUX_TYPE(DependencyProperty) LeftProperty { get; };
    static void SetLeft(WUXMUX_TYPE(UIElement) element, Double value);
    static Double GetLeft(WUXMUX_TYPE(UIElement) element);
  }

  [default_interface]
  [webhosthidden]
  runtimeclass ViewControl : XAML_NAMESPACE.Controls.ContentControl
  {
    ViewControl();

    ViewPanel GetPanel();
  }
}
