// WARNING: Please don't edit this file. It was generated by C++/WinRT
// v1.0.190111.3

#pragma once

#include "winrt/Windows.UI.Xaml.Automation.Provider.h"
#include "winrt/Windows.UI.Xaml.Automation.h"
#include "winrt/Windows.UI.Xaml.Controls.h"
#include "winrt/Windows.UI.Xaml.Media.h"
#include "winrt/Windows.UI.Xaml.h"
#include "winrt/Windows.UI.Xaml.h"
#include "winrt/react.uwp.h"


namespace winrt::react::uwp::implementation {

template <typename D, typename... I>
struct WINRT_EBO ViewPanel_base
    : implements<
          D,
          react::uwp::IViewPanel,
          Windows::UI::Xaml::IFrameworkElementOverrides,
          Windows::UI::Xaml::IFrameworkElementOverrides2,
          Windows::UI::Xaml::IUIElementOverrides,
          Windows::UI::Xaml::IUIElementOverrides7,
          Windows::UI::Xaml::IUIElementOverrides8,
          Windows::UI::Xaml::IUIElementOverrides9,
          composing,
          I...>,
      impl::require<
          D,
          Windows::UI::Composition::IAnimationObject,
          Windows::UI::Composition::IVisualElement,
          Windows::UI::Xaml::Controls::IPanel,
          Windows::UI::Xaml::Controls::IPanel2,
          Windows::UI::Xaml::IDependencyObject,
          Windows::UI::Xaml::IDependencyObject2,
          Windows::UI::Xaml::IFrameworkElement,
          Windows::UI::Xaml::IFrameworkElement2,
          Windows::UI::Xaml::IFrameworkElement3,
          Windows::UI::Xaml::IFrameworkElement4,
          Windows::UI::Xaml::IFrameworkElement6,
          Windows::UI::Xaml::IFrameworkElement7,
          Windows::UI::Xaml::IFrameworkElementProtected7,
          Windows::UI::Xaml::IUIElement,
          Windows::UI::Xaml::IUIElement10,
          Windows::UI::Xaml::IUIElement2,
          Windows::UI::Xaml::IUIElement3,
          Windows::UI::Xaml::IUIElement4,
          Windows::UI::Xaml::IUIElement5,
          Windows::UI::Xaml::IUIElement7,
          Windows::UI::Xaml::IUIElement8,
          Windows::UI::Xaml::IUIElement9>,
      impl::base<
          D,
          Windows::UI::Xaml::Controls::Panel,
          Windows::UI::Xaml::FrameworkElement,
          Windows::UI::Xaml::UIElement,
          Windows::UI::Xaml::DependencyObject>,
      Windows::UI::Xaml::IFrameworkElementOverridesT<D>,
      Windows::UI::Xaml::IFrameworkElementOverrides2T<D>,
      Windows::UI::Xaml::IUIElementOverridesT<D>,
      Windows::UI::Xaml::IUIElementOverrides7T<D>,
      Windows::UI::Xaml::IUIElementOverrides8T<D>,
      Windows::UI::Xaml::IUIElementOverrides9T<D> {
  using base_type = ViewPanel_base;
  using class_type = react::uwp::ViewPanel;
  using implements_type = typename ViewPanel_base::implements_type;
  using implements_type::implements_type;
  using composable_base = Windows::UI::Xaml::Controls::Panel;
#if _MSC_VER < 1914
  operator class_type() const noexcept {
    static_assert(std::is_same_v<
                  typename impl::implements_default_interface<D>::type,
                  default_interface<class_type>>);
    class_type result{nullptr};
    attach_abi(
        result, detach_abi(static_cast<default_interface<class_type>>(*this)));
    return result;
  }
#else
  operator impl::producer_ref<class_type> const() const noexcept {
    return {to_abi<default_interface<class_type>>(this)};
  }
#endif

  hstring GetRuntimeClassName() const {
    return L"react.uwp.ViewPanel";
  }
  ViewPanel_base() {
    impl::call_factory<
        Windows::UI::Xaml::Controls::Panel,
        Windows::UI::Xaml::Controls::IPanelFactory>(
        [&](auto &&f) { f.CreateInstance(*this, this->m_inner); });
  }
};

} // namespace winrt::react::uwp::implementation

namespace winrt::react::uwp::factory_implementation {

template <typename D, typename T, typename... I>
struct WINRT_EBO ViewPanelT : implements<
                                  D,
                                  Windows::Foundation::IActivationFactory,
                                  react::uwp::IViewPanelStatics,
                                  I...> {
  using instance_type = react::uwp::ViewPanel;

  hstring GetRuntimeClassName() const {
    return L"react.uwp.ViewPanel";
  }

  Windows::Foundation::IInspectable ActivateInstance() const {
    return make<T>();
  }

  Windows::UI::Xaml::DependencyProperty ViewBackgroundProperty() {
    return T::ViewBackgroundProperty();
  }

  Windows::UI::Xaml::DependencyProperty BorderThicknessProperty() {
    return T::BorderThicknessProperty();
  }

  Windows::UI::Xaml::DependencyProperty BorderBrushProperty() {
    return T::BorderBrushProperty();
  }

  Windows::UI::Xaml::DependencyProperty CornerRadiusProperty() {
    return T::CornerRadiusProperty();
  }

  Windows::UI::Xaml::DependencyProperty ClipChildrenProperty() {
    return T::ClipChildrenProperty();
  }

  Windows::UI::Xaml::DependencyProperty TopProperty() {
    return T::TopProperty();
  }

  void SetTop(Windows::UI::Xaml::UIElement const &element, double value) {
    T::SetTop(element, value);
  }

  double GetTop(Windows::UI::Xaml::UIElement const &element) {
    return T::GetTop(element);
  }

  Windows::UI::Xaml::DependencyProperty LeftProperty() {
    return T::LeftProperty();
  }

  void SetLeft(Windows::UI::Xaml::UIElement const &element, double value) {
    T::SetLeft(element, value);
  }

  double GetLeft(Windows::UI::Xaml::UIElement const &element) {
    return T::GetLeft(element);
  }
};

} // namespace winrt::react::uwp::factory_implementation

#if defined(WINRT_FORCE_INCLUDE_VIEWPANEL_XAML_G_H) || \
    __has_include("ViewPanel.xaml.g.h")

#include "ViewPanel.xaml.g.h"

#else

namespace winrt::react::uwp::implementation {
template <typename D, typename... I>
using ViewPanelT = ViewPanel_base<D, I...>;
}

#endif
