name: Bug report
description: File a bug report
title: Describe the problem
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        This form is for reporting bugs found in React Native for Windows.
        
        If the issue is that an existing React Native API is simply missing in React Native for Windows, please use the [this form](https://github.com/microsoft/react-native-windows/issues/new?template=missing-api.yaml) instead.

        If you just have a question, please post on [Discussions](https://github.com/microsoft/react-native-windows/discussions) instead.

        Your issue will be triaged by the RNW team according to [this process](https://github.com/microsoft/react-native-windows/wiki/Triage-Process).
  - type: textarea
    validations:
      required: true
    attributes:
      label: Problem Description
      description: |
        Please enter a description of the issue and any output and/or error logging.
        
        If you're seeing a failure when using a RNW CLI command (i.e. `run-windows`, `autolink-windows`, `codegen-windows`) please try again with `--logging` and provide that output.
    id: description
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps To Reproduce
      description: Provide a detailed list of steps that reproduce the issue.
      placeholder: |
        1.
        2.
    id: steps
  - type: textarea
    attributes:
      label: Expected Results
      description: Describe what you expected to happen.
    id: expected
  - type: input
    validations:
      required: true
    attributes:
      label: CLI version
      description: |
        Run the command `npx @react-native-community/cli -v` in your terminal and copy the result here.
      placeholder: "npx @react-native-community/cli -v"
    id: cli
  - type: textarea
    validations:
      required: true
    attributes:
      label: Environment
      description: |
        Run the command `npx @react-native-community/cli info` in your terminal and copy the result here.
      placeholder: "npx @react-native-community/cli info"
      render: markdown
    id: env
  - type: textarea
    attributes:
      label: Community Modules
      description: |
        Describe what you community modules you have added to your project.
        
        Not sure? Look at your app's `package.json` and share what's in the "dependencies" section.
    id: modules
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Target React Native Architecture
      description: |
        Which React Native architecture(s) are you using?
        
        Not sure? Which template did you use when creating your project? For RNW <= 0.79.0, the default for new app projects is "Old Architecture".
        
        See [New vs. Old Architecture](https://microsoft.github.io/react-native-windows/docs/new-architecture) for more details.
      multiple: true
      options:
        - "New Architecture (WinAppSDK)"
        - "Old Architecture (UWP)"
  - type: dropdown
    attributes:
      label: Target Platform Version
      description: What Windows SDK version are you building for?
      options:
        - "<= 10.0.17763"
        - "10.0.17763"
        - "10.0.18362"
        - "10.0.19041"
        - "10.0.22000"
        - "10.0.22621"
        - "10.0.26100"
        - ">= 10.0.26100"
    id: sdk
  - type: dropdown
    attributes:
      label: Visual Studio Version
      description: Which version of Visual Studio are you using?
      options:
        - "Visual Studio 2022"
        - "Visual Studio 2022 Preview"
    id: vs
  - type: dropdown
    attributes:
      label: Build Configuration
      description: Which build configuration are you running?
      options:
        - "Debug"
        - "DebugBundle"
        - "Release"
        - "ReleaseBundle"
    id: config
  - type: textarea
    attributes:
      label: Snack, code example, screenshot, or link to a repository
      description: |
        Please provide a [Snack](https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.

        You may provide a screenshot of the application if you think it is relevant to your bug report.

        [Here are some tips for providing a minimal example](https://stackoverflow.com/help/mcve).
    id: code
