name: Feature request
description: Suggest a new feature or idea
title: Your feature request
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        This is a template for new feature or API proposals for React Native for Windows. Use this to submit new API/component requests or behavior updates that are specific to Windows. For feature requests to React Native, go [here](https://github.com/react-native-community/discussions-and-proposals) instead. 
        
        Read more about React Native for Windows proposal process [here](https://github.com/microsoft/react-native-windows/tree/main/vnext/proposals).
        
        Your issue will be triaged by the RNW team according to [this process](https://github.com/microsoft/react-native-windows/wiki/Triage-Process).
  - type: textarea
    validations:
      required: true
    attributes:
      label: Summary
      description: Brief explanation of the new API or change.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Motivation
      description: |
        Why are we doing this? What use cases does it support? What is the expected outcome? Why should this be done for Windows?
        Please focus on explaining the motivation so that if this proposal is not accepted, the motivation could be used to develop alternative solutions. In other words, enumerate the constraints you are trying to solve without coupling them too closely to the solution you have in mind.
  - type: textarea
    attributes:
      label: Basic Example
      description: |
        If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.
  - type: textarea
    attributes:
      label: Open Questions
      description: |
        Please list any open issues that you think still need to be addressed.
        These could include areas you think would benefit from community or the react-native-windows team input