name: Fake bug report
description: File a bug report
title: Describe the problem
labels: [bug]
body:
  - type: dropdown
    attributes:
      label: Target Platform Version
      description: What SDK version are you building for?
      options:
        - "10.0.15063"
        - "10.0.16299"
        - "10.0.19041"
  - type: dropdown
    attributes:
      label: Target Device(s)
      description: What device(s) are you targeting?
      multiple: true
      options:
        - "Desktop"
        - "Xbox"
        - "HoloLens"
  - type: dropdown
    attributes:
      label: Visual Studio Version
      description: Which version of Visual Studio are you using?
      options:
        - "Visual Studio 2017"
        - "Visual Studio 2019"
  - type: dropdown
    attributes:
      label: Build Configuration
      description: Which build configuration are you running?
      options:
        - "Debug"
        - "DebugBundle"
        - "Release"
        - "ReleaseBundle"
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps To Reproduce
      description: Provide a detailed list of steps that reproduce the issue.
      placeholder: |
        1.
        2.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Expected Results
      description: Describe what you expected to happen.
  - type: markdown
    attributes:
      label: Troubleshooting
      description: If you see build failure on `react-native run-windows`, please try again with 'react-native run-windows --logging' and provide the output.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Snack, code example, screenshot, or link to a repository
      description: |
        Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
        You may provide a screenshot of the application if you think it is relevant to your bug report.
        Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve