//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "HostingPane.xaml.h"

void ::WindowsSampleApp::HostingPane::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///HostingPane.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::WindowsSampleApp::HostingPane::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->RootElement = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 3:
        {
            this->x_UseWebDebuggerCheckBox = safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(__target);
        }
        break;
    case 4:
        {
            this->x_UseLiveReloadCheckBox = safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(__target);
        }
        break;
    case 5:
        {
            this->x_ReuseInstanceCheckBox = safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(__target);
        }
        break;
    case 6:
        {
            this->x_LoadButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->x_LoadButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WindowsSampleApp::HostingPane::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HostingPane::OnLoadClicked);
        }
        break;
    case 7:
        {
            this->x_UnloadButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->x_UnloadButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WindowsSampleApp::HostingPane::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HostingPane::OnUnloadClicked);
        }
        break;
    case 8:
        {
            this->x_ReloadButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->x_ReloadButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WindowsSampleApp::HostingPane::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HostingPane::OnReloadClicked);
        }
        break;
    case 9:
        {
            this->x_AddPane = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
        }
        break;
    case 10:
        {
            this->x_RemovePane = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
        }
        break;
    case 11:
        {
            this->x_JavaScriptFilename = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->x_JavaScriptFilename))->TextChanged += ref new ::Windows::UI::Xaml::Controls::TextChangedEventHandler(this, (void (::WindowsSampleApp::HostingPane::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::TextChangedEventArgs^))&HostingPane::OnTextChanged_JavaScriptFilename);
        }
        break;
    case 12:
        {
            this->x_ReactAppName = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::WindowsSampleApp::HostingPane::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


