// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

#include "NamespaceRedirect.h"

namespace Microsoft.ReactNative
{
    [version(1)]
    typedef enum CanvasEdgeBehavior
    {
      Clamp = (int)0,
      Wrap = (int)1,
      Mirror = (int)2
    } CanvasEdgeBehavior;

    [version(1)]
    typedef enum EffectBorderMode
    {
      Soft = 0,
      Hard = 1
    } EffectBorderMode;

    [version(1)]
    typedef enum EffectOptimization
    {
      Speed = 0,
      Balanced = 1,
      Quality = 2
    } EffectOptimization;

    //----------------------------------------------------------------------------------------------

    [default_interface]
    [webhosthidden]
    runtimeclass BorderEffect : Windows.Graphics.Effects.IGraphicsEffect
    {
      CanvasEdgeBehavior ExtendX { get; set; };
      CanvasEdgeBehavior ExtendY { get; set; };
      Windows.Graphics.Effects.IGraphicsEffectSource Source { get; set; };
    }

    //----------------------------------------------------------------------------------------------

    [default_interface]
    [webhosthidden]
    runtimeclass GaussianBlurEffect : Windows.Graphics.Effects.IGraphicsEffect
    {
      Single BlurAmount { get; set; };
      EffectOptimization Optimization { get; set; };
      EffectBorderMode BorderMode { get; set; };
      Windows.Graphics.Effects.IGraphicsEffectSource Source { get; set; };
    }

    //----------------------------------------------------------------------------------------------
}
