# Job to run Attack Surface Analyzer (ASA) for SDL compliance
# Validates that installers or high-privilege programs do not weaken OS security
parameters:
  - name: buildEnvironment
    type: string
    default: PullRequest
    values:
      - PullRequest
      - SecurePullRequest
      - Continuous
  - name: AgentPool
    type: object
  - name: complianceWarnOnly
    displayName: Convert compliance errors to warnings
    type: boolean
    default: true

jobs:
  # Only run ASA for SecurePullRequest builds
  - ${{if eq(parameters.buildEnvironment, 'SecurePullRequest')}}:
    - job: AttackSurfaceAnalyzer
      displayName: Attack Surface Analyzer (ASA) 🛡️
      pool: ${{ parameters.AgentPool.Medium }}
      timeoutInMinutes: 60
      cancelTimeoutInMinutes: 5

      variables:
        - template: ../variables/windows.yml

      steps:
        - template: ../templates/checkout-shallow.yml

        - template: ../templates/prepare-js-env.yml

        - template: ../templates/set-version-vars.yml
          parameters:
            buildEnvironment: ${{ parameters.buildEnvironment }}

        - template: ../templates/prepare-build-env.yml
          parameters:
            platform: x64
            configuration: Release
            buildEnvironment: ${{ parameters.buildEnvironment }}

        # Authenticate to NuGet feeds
        - task: NuGetAuthenticate@1
          displayName: '🛡️ Authenticate NuGet'

        # Install Attack Surface Analyzer CLI tool
        - task: PowerShell@2
          displayName: '🛡️ Install Attack Surface Analyzer'
          inputs:
            errorActionPreference: 'continue'
            targetType: inline
            script: |
              Write-Host "Installing Attack Surface Analyzer (ASA) CLI tool..."
              # Install from public NuGet.org feed
              dotnet tool install --global Microsoft.CST.AttackSurfaceAnalyzer.CLI --add-source https://api.nuget.org/v3/index.json
              
              if ($LASTEXITCODE -ne 0) {
                Write-Error "Failed to install ASA tool"
                exit 1
              }

        # Take "before" snapshot of the system
        - task: PowerShell@2
          displayName: '🛡️ ASA - Collect Before Snapshot'
          inputs:
            targetType: inline
            script: |
              # Refresh environment PATH to include .NET global tools
              $env:PATH = [System.Environment]::GetEnvironmentVariable("PATH", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("PATH", "User")
              
              Write-Host "Taking 'before' snapshot of system state..."
              # FIXED: Use correct ASA command syntax based on CLI walkthrough
              # Collect files (-f), registry (-r), services (-s), ports (-p), certificates (-c)
              asa collect -f -r -s -p -c --directories "$(Build.SourcesDirectory)" --verbose
              if ($LASTEXITCODE -ne 0) {
                Write-Error "Failed to collect 'before' snapshot"
                exit 1
              }
              Write-Host "✅ Before snapshot collected successfully"

        # Build the React Native Windows solution
        # This simulates the "installation" that ASA will analyze
        - template: ../templates/msbuild-sln.yml
          parameters:
            solutionDir: vnext
            solutionName: Microsoft.ReactNative.sln
            buildPlatform: x64
            buildConfiguration: Release

        # Optional: Build NuGet packages if needed
        # This step simulates package creation which could modify system state
        - task: PowerShell@2
          displayName: '🛡️ ASA - Simulate Package Installation'
          inputs:
            targetType: inline
            script: |
              Write-Host "Simulating package installation for ASA analysis..."
              Write-Host "Build artifacts are in place for analysis"
              # Note: Actual NuGet package installation would go here if needed
              # For now, we're analyzing the build process itself

        # Take "after" snapshot of the system
        - task: PowerShell@2
          displayName: '🛡️ ASA - Collect After Snapshot'
          inputs:
            targetType: inline
            script: |
              # Refresh environment PATH to include .NET global tools
              $env:PATH = [System.Environment]::GetEnvironmentVariable("PATH", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("PATH", "User")
              
              Write-Host "Taking 'after' snapshot of system state..."
              # FIXED: Use same collector flags as baseline scan
              # Collect files (-f), registry (-r), services (-s), ports (-p), certificates (-c)
              asa collect -f -r -s -p -c --directories "$(Build.SourcesDirectory)" --verbose
              if ($LASTEXITCODE -ne 0) {
                Write-Error "Failed to collect 'after' snapshot"
                exit 1
              }
              Write-Host "✅ After snapshot collected successfully"

        # Export comparison results (ASA 2.3 syntax)
        - task: PowerShell@2
          displayName: '🛡️ ASA - Export Comparison Results'
          inputs:
            targetType: inline
            script: |
              # Refresh environment PATH to include .NET global tools
              $env:PATH = [System.Environment]::GetEnvironmentVariable("PATH", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("PATH", "User")

              Write-Host "Comparing before and after snapshots for ASA 2.3..."

              # Create output directory for results
              $resultsDir = "$(Build.ArtifactStagingDirectory)\ASA_Results"
              New-Item -ItemType Directory -Force -Path $resultsDir | Out-Null

              Write-Host "Generating comparison results (SARIF and JSON)..."

              # FIXED: Use correct export syntax from CLI walkthrough - compares latest two collection runs automatically
              # Export as SARIF format for security analysis
              asa export-collect --outputsarif "$resultsDir\asa-comparison.sarif" --verbose
              if ($LASTEXITCODE -ne 0) {
                Write-Error "Failed to export comparison results (SARIF)"
                exit 1
              }

              # Export as JSON format for additional analysis
              asa export-collect "$resultsDir\asa-comparison.json" --verbose
              if ($LASTEXITCODE -ne 0) {
                Write-Error "Failed to export comparison results (JSON)"
                exit 1
              }

              Write-Host "✅ Comparison results exported successfully"
              Write-Host "Results location: $resultsDir"

        # Analyze results and check for security issues
        - task: PowerShell@2
          displayName: '🛡️ ASA - Analyze Results'
          inputs:
            targetType: inline
            script: |
              Write-Host "Analyzing ASA results for security regressions..."
              
              $sarifFile = "$(Build.ArtifactStagingDirectory)\ASA_Results\asa-comparison.sarif"
              $jsonFile = "$(Build.ArtifactStagingDirectory)\ASA_Results\asa-comparison.json"
              
              Write-Host "📊 ASA Analysis Summary:"
              Write-Host "========================"
              
              # Check SARIF file for security findings
              if (Test-Path $sarifFile) {
                Write-Host "📋 SARIF Report Analysis:"
                try {
                  $sarifContent = Get-Content $sarifFile | ConvertFrom-Json
                  $findingCount = 0
                  
                  if ($sarifContent.runs -and $sarifContent.runs.Count -gt 0) {
                    foreach ($run in $sarifContent.runs) {
                      if ($run.results) {
                        $findingCount += $run.results.Count
                      }
                    }
                  }
                  
                  Write-Host "Security findings detected: $findingCount"
                  
                  if ($findingCount -gt 0) {
                    Write-Host "⚠️ Security findings detected in SARIF report"
                    Write-Host "Review the SARIF file for detailed security analysis"
                  } else {
                    Write-Host "✅ No security findings in SARIF report"
                  }
                } catch {
                  Write-Host "⚠️ Could not parse SARIF file: $($_.Exception.Message)"
                }
              }
              
              # Check JSON file for additional analysis
              if (Test-Path $jsonFile) {
                Write-Host "📋 JSON Report Analysis:"
                try {
                  $jsonContent = Get-Content $jsonFile | ConvertFrom-Json
                  Write-Host "JSON report generated successfully"
                } catch {
                  Write-Host "⚠️ Could not parse JSON file: $($_.Exception.Message)"
                }
              }
              
              Write-Host ""
              Write-Host "🛡️ SDL Compliance Notes:"
              Write-Host "- Review SARIF findings for security vulnerabilities"
              Write-Host "- Pay attention to privilege escalations"
              Write-Host "- Check for unsigned binaries or weak permissions"
              Write-Host "- Verify certificate and firewall changes"
              Write-Host ""
              Write-Host "Results available in build artifacts: ASA_Results"
              Write-Host "ASA analysis completed"
          continueOnError: ${{ parameters.complianceWarnOnly }}

        # Publish ASA results as build artifact
        - task: PublishBuildArtifacts@1
          displayName: '🛡️ Publish ASA Results'
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)\ASA_Results'
            ArtifactName: 'ASA_Results'
            publishLocation: 'Container'
          condition: always()

        # Generate summary for PR
        - task: PowerShell@2
          displayName: '🛡️ ASA - Generate PR Summary'
          inputs:
            targetType: inline
            script: |
              Write-Host "Generating ASA summary for PR..."
              
              $sarifFile = "$(Build.ArtifactStagingDirectory)\ASA_Results\asa-comparison.sarif"
              $jsonFile = "$(Build.ArtifactStagingDirectory)\ASA_Results\asa-comparison.json"
              
              # Check if SARIF file exists and upload as summary
              if (Test-Path $sarifFile) {
                Write-Host "SARIF results available for security analysis"
                Write-Host "##vso[task.uploadsummary]$sarifFile"
              }
              
              # Check if JSON file exists  
              if (Test-Path $jsonFile) {
                Write-Host "JSON results available for detailed analysis"
              }
              
              if ((Test-Path $sarifFile) -or (Test-Path $jsonFile)) {
                Write-Host "✅ ASA results will be available in PR artifacts"
              } else {
                Write-Host "⚠️ No ASA result files found"
              }
          condition: always()
