parameters:
  - name: buildEnvironment
    type: string
    default: PullRequest
    values:
      - PullRequest
      - Continuous
  - name: AgentPool
    type: object
  - name: buildNuGetOnly
    type: boolean
    default: false
  - name: buildWinAppSDKOnly
    type: boolean
    default: false
  - name: buildMatrix
    type: object
    default:
      - BuildEnvironment: PullRequest
        Matrix:
          - Name: X64ReleaseCpp
            language: cpp
            configuration: Release
            platform: x64
            projectType: app
            runWack: true
          - Name: X64ReleaseCs
            language: cs
            configuration: Release
            platform: x64
            projectType: app
            runWack: true
          - Name: X86DebugCpp
            language: cpp
            configuration: Debug
            platform: x86
            projectType: app
            additionalInitArguments: --namespace MyCompany.MyApplication.MyComponent
          - Name: X86DebugCs
            language: cs
            configuration: Debug
            platform: x86
            projectType: app
            additionalInitArguments: --namespace MyCompany.MyApplication.MyComponent
          - Name: X86DebugCppLib
            language: cpp
            configuration: Debug
            platform: x86
            projectType: lib
            additionalRunArguments: --no-autolink --no-deploy
          - Name: X86DebugCsLib
            language: cs
            configuration: Debug
            platform: x86
            projectType: lib
            additionalRunArguments: --no-autolink --no-deploy
          # #8132 Support for C++ WinAppSDK apps
          # - Name: X86DebugCppWinUI3
          #   language: cpp
          #   configuration: Debug
          #   platform: x86
          #   projectType: app
          #   additionalInitArguments: --useWinUI3 true --nuGetTestFeed $(System.DefaultWorkingDirectory)\NuGetTestFeed
          #   additionalRunArguments: --no-deploy
          #   useWinAppSDK: true
          - Name: X64DebugCsWinUI3
            language: cs
            configuration: Debug
            platform: x64
            projectType: app
            additionalInitArguments: --useWinUI3 true --nuGetTestFeed $(System.DefaultWorkingDirectory)\NuGetTestFeed
            additionalRunArguments: --no-deploy
            useWinAppSDK: true
          - Name: X86DebugCppHermes
            language: cpp
            configuration: Debug
            platform: x86
            projectType: app
            additionalInitArguments: --useHermes
          - Name: X64ReleaseCsHermes
            language: cs
            configuration: Release
            platform: x64
            projectType: app
            additionalInitArguments: --useHermes
            runWack: true
          - Name: Arm64ReleaseCsHermes
            language: cs
            configuration: Release
            platform: ARM64
            projectType: app
            additionalInitArguments: --useHermes
            additionalRunArguments: --no-deploy
          - Name: X64ReleaseCppHermes
            language: cpp
            configuration: Release
            platform: x64
            projectType: app
            additionalInitArguments: --useHermes
            runWack: true
          - Name: X64DebugCppNuget
            language: cpp
            configuration: Debug
            platform: x64
            projectType: app
            useNuGet: true
          - Name: X64ReleaseCsNuget
            language: cs
            configuration: Release
            platform: x64
            projectType: app
            useNuGet: true
          - Name: X64DebugCppLowResource
            language: cpp
            configuration: Debug
            platform: x64
            projectType: app
            lowResource: true
      - BuildEnvironment: Continuous
        Matrix:
          - Name: X64ReleaseCpp
            language: cpp
            configuration: Release
            platform: x64
            projectType: app
            runWack: true
          - Name: X64ReleaseCs
            language: cs
            configuration: Release
            platform: x64
            projectType: app
            runWack: true
          - Name: X86DebugCpp
            language: cpp
            configuration: Debug
            platform: x86
            projectType: app
            additionalInitArguments: --namespace MyCompany.MyApplication.MyComponent
          - Name: X86DebugCs
            language: cs
            configuration: Debug
            platform: x86
            projectType: app
            additionalInitArguments: --namespace MyCompany.MyApplication.MyComponent
          - Name: X86DebugCppLib
            language: cpp
            configuration: Debug
            platform: x86
            projectType: lib
            additionalRunArguments: --no-autolink --no-deploy
          - Name: X86DebugCsLib
            language: cs
            configuration: Debug
            platform: x86
            projectType: lib
            additionalRunArguments: --no-autolink --no-deploy
          # #8132 Support for C++ WinAppSDK apps
          # - Name: X86DebugCppWinUI3
          #   language: cpp
          #   configuration: Debug
          #   platform: x86
          #   projectType: app
          #   additionalInitArguments: --useWinUI3 true --nuGetTestFeed $(System.DefaultWorkingDirectory)\NuGetTestFeed
          #   additionalRunArguments: --no-deploy
          #   useWinAppSDK: true
          - Name: X64DebugCsWinUI3
            language: cs
            configuration: Debug
            platform: x64
            projectType: app
            additionalInitArguments: --useWinUI3 true --nuGetTestFeed $(System.DefaultWorkingDirectory)\NuGetTestFeed
            additionalRunArguments: --no-deploy
            useWinAppSDK: true
          - Name: X86DebugCppHermes
            language: cpp
            configuration: Debug
            platform: x86
            projectType: app
            additionalInitArguments: --useHermes
          - Name: X64ReleaseCsHermes
            language: cs
            configuration: Release
            platform: x64
            projectType: app
            additionalInitArguments: --useHermes
            runWack: true
          - Name: Arm64ReleaseCsHermes
            language: cs
            configuration: Release
            platform: ARM64
            projectType: app
            additionalInitArguments: --useHermes
            additionalRunArguments: --no-deploy
          - Name: X64ReleaseCppHermes
            language: cpp
            configuration: Release
            platform: x64
            projectType: app
            additionalInitArguments: --useHermes
            runWack: true
          - Name: X86DebugCppNuget
            language: cpp
            configuration: Debug
            platform: x86
            projectType: app
            useNuGet: true
          - Name: X86DebugCsNuget
            language: cs
            configuration: Debug
            platform: x86
            projectType: app
            useNuGet: true
          - Name: X86ReleaseCppNuget
            language: cpp
            configuration: Release
            platform: x86
            projectType: app
            useNuGet: true
          - Name: X86ReleaseCsNuget
            language: cs
            configuration: Release
            platform: x86
            projectType: app
            useNuGet: true
          - Name: X64ReleaseCppNuget
            language: cpp
            configuration: Release
            platform: x64
            projectType: app
            useNuGet: true
          - Name: X64ReleaseCsNuget
            language: cs
            configuration: Release
            platform: x64
            projectType: app
            useNuGet: true
          - Name: Arm64ReleaseCppNuget
            language: cpp
            configuration: Release
            platform: ARM64
            projectType: app
            additionalRunArguments: --no-deploy
            useNuGet: true
          - Name: Arm64ReleaseCsNuget
            language: cs
            configuration: Release
            platform: ARM64
            projectType: app
            additionalRunArguments: --no-deploy
            useNuGet: true
          - Name: Arm64DebugCpp
            language: cpp
            configuration: Debug
            platform: ARM64
            projectType: app
            additionalRunArguments: --no-deploy # We don't have Arm agents
          - Name: Arm64DebugCs
            language: cs
            configuration: Debug
            platform: ARM64
            projectType: app
            additionalRunArguments: --no-deploy # We don't have Arm agents
          - Name: Arm64ReleaseCpp
            language: cpp
            configuration: Release
            platform: ARM64
            projectType: app
            additionalRunArguments: --no-deploy # We don't have Arm agents
          - Name: Arm64ReleaseCs
            language: cs
            configuration: Release
            platform: ARM64
            projectType: app
            additionalRunArguments: --no-deploy # We don't have Arm agents
          - Name: X86ReleaseCpp
            language: cpp
            configuration: Release
            platform: x86
            projectType: app
            runWack: true
          - Name: X86ReleaseCs
            language: cs
            configuration: Release
            platform: x86
            projectType: app
            runWack: true
          - Name: X64DebugCpp
            language: cpp
            configuration: Debug
            platform: x64
            projectType: app
          - Name: X64DebugCs
            language: cs
            configuration: Debug
            platform: x64
            projectType: app
          - Name: X64DebugCppLowResource
            language: cpp
            configuration: Debug
            platform: x64
            projectType: app
            lowResource: true
          - Name: X64ReleaseCppLowResource
            language: cpp
            configuration: Release
            platform: x64
            projectType: app
            lowResource: true
jobs:
  - ${{ each config in parameters.buildMatrix }}:
    - ${{ if eq(config.BuildEnvironment, parameters.buildEnvironment) }}:
      - ${{ each matrix in config.Matrix }}:
        - ${{ if and(eq(coalesce(matrix.useNuGet, false), parameters.buildNuGetOnly), eq(coalesce(matrix.useWinAppSDK, false), parameters.buildWinAppSDKOnly))}}:
          - job: CliInit${{ matrix.Name }}
            displayName: Verify Cli ${{ matrix.Name }}

            ${{ if eq(matrix.useNuGet, true) }}:
              dependsOn:
                - UniversalBuild${{ matrix.platform }}Release

            ${{ if eq(matrix.useWinAppSDK, true) }}:
              dependsOn:
                - WinAppSDKX64Release

            variables: [template: ../variables/windows.yml]

            ${{ if eq(matrix.lowResource, true) }}:
              pool: ${{ parameters.AgentPool.Small }}
            ${{ else }}:
              pool: ${{ parameters.AgentPool.Medium }}
            timeoutInMinutes: 60
            cancelTimeoutInMinutes: 5

            steps:
              - template: ../templates/checkout-full.yml
                parameters:
                  persistCredentials: false # We don't need git creds in this job

              - template: ../templates/prepare-js-env.yml

              - template: ../templates/prepare-build-env.yml
                parameters:
                  platform: ${{ parameters.platform }}
                  configuration: ${{ parameters.configuration }}
                  buildEnvironment: ${{ parameters.buildEnvironment }}

              - template: ../templates/react-native-init.yml
                parameters:
                  language: ${{ matrix.language }}
                  configuration: ${{ matrix.configuration }}
                  platform: ${{ matrix.platform }}
                  projectType: ${{ matrix.projectType }}
                  additionalInitArguments: ${{ matrix.additionalInitArguments }}
                  additionalRunArguments: ${{ matrix.additionalRunArguments }}
                  runWack: ${{ coalesce(matrix.runWack, false) }}
                  buildEnvironment: ${{ parameters.buildEnvironment }}
                  useNuGet: ${{ coalesce(matrix.useNuGet, false) }}
                  useWinAppSDK: ${{ coalesce(matrix.useWinAppSDK, false) }}