parameters:
  - name: buildEnvironment
    type: string
    default: PullRequest
    values:
      - PullRequest
      - Continuous
  - name: buildNuGetOnly
    type: boolean
    default: false

jobs:
  - ${{ if not(parameters.buildNuGetOnly) }}:
    - job: CliInit
      variables:
        - template: ../variables/vs2019.yml
      displayName: Verify Cli
      strategy:
        matrix: # Why we only build some flavors: https://github.com/microsoft/react-native-windows/issues/4308
          # Start Continuous only
          ${{ if eq(parameters.buildEnvironment, 'Continuous') }}:
            Arm64DebugCpp:
              language: cpp
              configuration: Debug
              platform: arm64
              projectType: app
              additionalInitArguments:
              additionalRunArguments: --no-deploy # We don't have Arm agents
              verifyAppLaunch: false
            Arm64DebugCs:
              language: cs
              configuration: Debug
              platform: arm64
              projectType: app
              additionalInitArguments:
              additionalRunArguments: --no-deploy # We don't have Arm agents
              verifyAppLaunch: false
            Arm64ReleaseCpp:
              language: cpp
              configuration: Release
              platform: arm64
              projectType: app
              additionalInitArguments:
              additionalRunArguments: --no-deploy # We don't have Arm agents
              verifyAppLaunch: false
            Arm64ReleaseCs:
              language: cs
              configuration: Release
              platform: arm64
              projectType: app
              additionalInitArguments:
              additionalRunArguments: --no-deploy # We don't have Arm agents
              verifyAppLaunch: false
          # End Continuous only
          X64ReleaseCpp:
            language: cpp
            configuration: Release
            platform: x64
            projectType: app
            additionalInitArguments:
            additionalRunArguments:
            verifyAppLaunch: true
          X64ReleaseCs:
            language: cs
            configuration: Release
            platform: x64
            projectType: app
            additionalInitArguments:
            additionalRunArguments:
            verifyAppLaunch: true
          X86DebugCpp:
            language: cpp
            configuration: Debug
            platform: x86
            projectType: app
            additionalInitArguments: --namespace MyCompany.MyApplication.MyComponent
            additionalRunArguments:
            verifyAppLaunch: false
          X86DebugCs:
            language: cs
            configuration: Debug
            platform: x86
            projectType: app
            additionalInitArguments: --namespace MyCompany.MyApplication.MyComponent
            additionalRunArguments:
            verifyAppLaunch: false
          # Start Continuous only
          ${{ if eq(parameters.buildEnvironment, 'Continuous') }}:
            X86ReleaseCpp:
              language: cpp
              configuration: Release
              platform: x86
              projectType: app
              additionalInitArguments:
              additionalRunArguments:
              verifyAppLaunch: true
            X86ReleaseCs:
              language: cs
              configuration: Release
              platform: x86
              projectType: app
              additionalInitArguments:
              additionalRunArguments:
              verifyAppLaunch: true
            X64DebugCpp:
              language: cpp
              configuration: Debug
              platform: x64
              projectType: app
              additionalInitArguments:
              additionalRunArguments:
              verifyAppLaunch: false
            X64DebugCs:
              language: cs
              configuration: Debug
              platform: x64
              projectType: app
              additionalInitArguments:
              additionalRunArguments:
              verifyAppLaunch: false
          # End Continuous only

          X86DebugCppLib:
            language: cpp
            configuration: Debug
            platform: x86
            projectType: lib
            additionalInitArguments:
            additionalRunArguments: --no-autolink --no-deploy
            verifyAppLaunch: false
          X86DebugCsLib:
            language: cs
            configuration: Debug
            platform: x86
            projectType: lib
            additionalInitArguments:
            additionalRunArguments: --no-autolink --no-deploy
            verifyAppLaunch: false

          X86DebugCppWinUI3:
            language: cpp
            configuration: Debug
            platform: x86
            projectType: app
            additionalInitArguments: --useWinUI3 true
            additionalRunArguments:
            verifyAppLaunch: false
          X86DebugCsWinUI3:
            language: cs
            configuration: Debug
            platform: x86
            projectType: app
            additionalInitArguments: --useWinUI3 true
            additionalRunArguments:
            verifyAppLaunch: false

          X86DebugCppHermes:
            language: cpp
            configuration: Debug
            platform: x86
            projectType: app
            additionalInitArguments: --useHermes
            additionalRunArguments:
            verifyAppLaunch: false
          X64ReleaseCsHermes:
            language: cs
            configuration: Release
            platform: x64
            projectType: app
            additionalInitArguments: --useHermes
            additionalRunArguments:
            verifyAppLaunch: true
          Arm64ReleaseCsHermes:
            language: cs
            configuration: Release
            platform: arm64
            projectType: app
            additionalInitArguments: --useHermes
            additionalRunArguments: --no-deploy # We don't have Arm agents
            verifyAppLaunch: false
          X64ReleaseCppHermes:
            language: cpp
            configuration: Release
            platform: x64
            projectType: app
            additionalInitArguments: --useHermes
            additionalRunArguments:
            verifyAppLaunch: true

      pool: $(AgentPool.Medium)
      timeoutInMinutes: 60
      cancelTimeoutInMinutes: 5

      steps:
        - template: ../templates/react-native-init.yml
          parameters:
            language: $(language)
            configuration: $(configuration)
            platform: $(platform)
            projectType: $(projectType)
            additionalInitArguments: $(additionalInitArguments)
            additionalRunArguments: $(additionalRunArguments)
            buildEnvironment: ${{ parameters.buildEnvironment }}
            verifyAppLaunch: $(verifyAppLaunch)

  # We unfortunately can't add the nuget ones to the existing matrix above because Azure DevOps does not allow the dependsOn to be dynamic based on matrix expansion
  - ${{ if parameters.buildNuGetOnly }}:
    - job: CliInitNuGet
      variables:
        - template: ../variables/vs2019.yml
      displayName: Verify Cli
      dependsOn:
        - UniversalBuild
      strategy:
        matrix: # Why we only build some flavors: https://github.com/microsoft/react-native-windows/issues/4308
          X64DebugCppNuget:
            language: cpp
            configuration: Debug
            platform: x86
            projectType: app
            additionalInitArguments:
            additionalRunArguments:
          X64DebugCsNuget:
            language: cs
            configuration: Debug
            platform: x86
            projectType: app
            additionalInitArguments:
            additionalRunArguments:
      pool: $(AgentPool.Medium)
      timeoutInMinutes: 60
      cancelTimeoutInMinutes: 5

      steps:
        - template: ../templates/react-native-init.yml
          parameters:
            language: $(language)
            configuration: $(configuration)
            platform: $(platform)
            projectType: $(projectType)
            additionalInitArguments: $(additionalInitArguments)
            additionalRunArguments: $(additionalRunArguments)
            useNuGet: true
            buildEnvironment: ${{ parameters.buildEnvironment }}
