parameters:
  - name: buildEnvironment
    type: string
    default: PullRequest
    values:
      - PullRequest
      - Continuous
  - name: buildNuGetOnly
    type: boolean
  - name: buildMatrix
    type: object
    default:
      - BuildEnvironment: PullRequest
        Matrix:
          - Name: X64ReleaseCpp
            language: cpp
            configuration: Release
            platform: x64
            projectType: app
            runWack: true
          - Name: X64ReleaseCs
            language: cs
            configuration: Release
            platform: x64
            projectType: app
            runWack: true
          - Name: X86DebugCpp
            language: cpp
            configuration: Debug
            platform: x86
            projectType: app
            additionalInitArguments: --namespace MyCompany.MyApplication.MyComponent
          - Name: X86DebugCs
            language: cs
            configuration: Debug
            platform: x86
            projectType: app
            additionalInitArguments: --namespace MyCompany.MyApplication.MyComponent
          - Name: X86DebugCppLib
            language: cpp
            configuration: Debug
            platform: x86
            projectType: lib
            additionalRunArguments: --no-autolink --no-deploy
          - Name: X86DebugCsLib
            language: cs
            configuration: Debug
            platform: x86
            projectType: lib
            additionalRunArguments: --no-autolink --no-deploy
          - Name: X86DebugCppWinUI3
            language: cpp
            configuration: Debug
            platform: x86
            projectType: app
            additionalInitArguments: --useWinUI3 true
          - Name: X86DebugCsWinUI3
            language: cs
            configuration: Debug
            platform: x86
            projectType: app
            additionalInitArguments: --useWinUI3 true
          - Name: X86DebugCppHermes
            language: cpp
            configuration: Debug
            platform: x86
            projectType: app
            additionalInitArguments: --useHermes
          - Name: X64ReleaseCsHermes
            language: cs
            configuration: Release
            platform: x64
            projectType: app
            additionalInitArguments: --useHermes
            runWack: true
          - Name: ARM64ReleaseCsHermes
            language: cs
            configuration: Release
            platform: arm64
            projectType: app
            additionalInitArguments: --useHermes
            additionalRunArguments: --no-deploy
          - Name: X64ReleaseCppHermes
            language: cpp
            configuration: Release
            platform: x64
            projectType: app
            additionalInitArguments: --useHermes
            runWack: true
          - Name: X64DebugCppNuget
            language: cpp
            configuration: Debug
            platform: x86
            projectType: app
            useNuGet: true
          - Name: X64DebugCsNuget
            language: cs
            configuration: Debug
            platform: x86
            projectType: app
            useNuGet: true
      - BuildEnvironment: Continuous
        Matrix:
          - Name: X64ReleaseCpp
            language: cpp
            configuration: Release
            platform: x64
            projectType: app
            runWack: true
          - Name: X64ReleaseCs
            language: cs
            configuration: Release
            platform: x64
            projectType: app
            runWack: true
          - Name: X86DebugCpp
            language: cpp
            configuration: Debug
            platform: x86
            projectType: app
            additionalInitArguments: --namespace MyCompany.MyApplication.MyComponent
          - Name: X86DebugCs
            language: cs
            configuration: Debug
            platform: x86
            projectType: app
            additionalInitArguments: --namespace MyCompany.MyApplication.MyComponent
          - Name: X86DebugCppLib
            language: cpp
            configuration: Debug
            platform: x86
            projectType: lib
            additionalRunArguments: --no-autolink --no-deploy
          - Name: X86DebugCsLib
            language: cs
            configuration: Debug
            platform: x86
            projectType: lib
            additionalRunArguments: --no-autolink --no-deploy
          - Name: X86DebugCppWinUI3
            language: cpp
            configuration: Debug
            platform: x86
            projectType: app
            additionalInitArguments: --useWinUI3 true
          - Name: X86DebugCsWinUI3
            language: cs
            configuration: Debug
            platform: x86
            projectType: app
            additionalInitArguments: --useWinUI3 true
          - Name: X86DebugCppHermes
            language: cpp
            configuration: Debug
            platform: x86
            projectType: app
            additionalInitArguments: --useHermes
          - Name: X64ReleaseCsHermes
            language: cs
            configuration: Release
            platform: x64
            projectType: app
            additionalInitArguments: --useHermes
            runWack: true
          - Name: ARM64ReleaseCsHermes
            language: cs
            configuration: Release
            platform: arm64
            projectType: app
            additionalInitArguments: --useHermes
            additionalRunArguments: --no-deploy
          - Name: X64ReleaseCppHermes
            language: cpp
            configuration: Release
            platform: x64
            projectType: app
            additionalInitArguments: --useHermes
            runWack: true
          - Name: X64DebugCppNuget
            language: cpp
            configuration: Debug
            platform: x86
            projectType: app
            useNuGet: true
          - Name: X64DebugCsNuget
            language: cs
            configuration: Debug
            platform: x86
            projectType: app
            useNuGet: true
          - Name: Arm64DebugCpp
            language: cpp
            configuration: Debug
            platform: arm64
            projectType: app
            additionalRunArguments: --no-deploy # We don't have Arm agents
          - Name: Arm64DebugCs
            language: cs
            configuration: Debug
            platform: arm64
            projectType: app
            additionalRunArguments: --no-deploy # We don't have Arm agents
          - Name: Arm64ReleaseCpp
            language: cpp
            configuration: Release
            platform: arm64
            projectType: app
            additionalRunArguments: --no-deploy # We don't have Arm agents
          - Name: Arm64ReleaseCs
            language: cs
            configuration: Release
            platform: arm64
            projectType: app
            additionalRunArguments: --no-deploy # We don't have Arm agents
          - Name: X86ReleaseCpp
            language: cpp
            configuration: Release
            platform: x86
            projectType: app
            runWack: true
          - Name: X86ReleaseCs
            language: cs
            configuration: Release
            platform: x86
            projectType: app
            runWack: true
          - Name: X64DebugCpp
            language: cpp
            configuration: Debug
            platform: x64
            projectType: app
          - Name: X64DebugCs
            language: cs
            configuration: Debug
            platform: x64
            projectType: app
jobs:
  - ${{ each config in parameters.buildMatrix }}:
    - ${{ if eq(config.BuildEnvironment, parameters.buildEnvironment) }}:
      - ${{ each matrix in config.Matrix }}:
        - ${{ if eq(coalesce(matrix.useNuGet, false), parameters.buildNuGetOnly) }}:
          - job: CliInit${{ matrix.Name }}
            displayName: Verify Cli ${{ matrix.Name }}

            ${{ if eq(matrix.useNuGet, true) }}:
              dependsOn:
                - UniversalBuild

            variables:
              - template: ../variables/vs2019.yml

            pool: $(AgentPool.Medium)
            timeoutInMinutes: 60
            cancelTimeoutInMinutes: 5

            steps:
              - template: ../templates/react-native-init.yml
                parameters:
                  language: ${{ matrix.language }}
                  configuration: ${{ matrix.configuration }}
                  platform: ${{ matrix.platform }}
                  projectType: ${{ matrix.projectType }}
                  additionalInitArguments: ${{ matrix.additionalInitArguments }}
                  additionalRunArguments: ${{ matrix.additionalRunArguments }}
                  runWack: ${{ coalesce(matrix.runWack, false) }}
                  buildEnvironment: ${{ parameters.buildEnvironment }}
                  useNuGet: ${{ coalesce(matrix.useNuGet, false) }}
