#
parameters:
  - name: buildEnvironment
    type: string
    default : PullRequest
    values: 
     - PullRequest 
     - Continuous 

jobs:
  - job: E2ETest
    displayName: E2E Test App
    strategy:
      matrix:
        ${{ if eq(parameters.buildEnvironment, 'Continuous') }}:
          # Arm E2E does not build on non-arm agents
          # Arm64:
          #   BuildPlatform: ARM64
          x64:
            BuildPlatform: x64
            DeployOption:
          x86:
            BuildPlatform: x86
        # End Continuous only
        ${{ if eq(parameters.buildEnvironment, 'PullRequest') }}:
          x86:
            BuildPlatform: x86
            DeployOption: --deploy-from-layout

    variables:
      - template: ../variables/vs2019.yml
    pool: $(AgentPool.Medium)
    timeoutInMinutes: 60 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them

    steps:
      - checkout: self
        clean: true
        submodules: false
            
      - powershell: |
          Write-Host "##vso[task.setvariable variable=BuildLogDirectory]$(Build.BinariesDirectory)\$(BuildPlatform)\BuildLogs"
        displayName: Set BuildLogDirectory

      - template: ../templates/prepare-env.yml

      - task: CmdLine@2
        displayName: Set LocalDumps
        inputs:
          script: $(Build.SourcesDirectory)\.ado\scripts\SetupLocalDumps.cmd ReactUWPTestApp
          workingDirectory: $(Build.SourcesDirectory)

      - task: CmdLine@2
        displayName: Set up AppVerifer on ReactUWPTestApp
        inputs:
          script: regedit /S $(Build.SourcesDirectory)\.ado\scripts\ReactUWPTestApp.reg
          workingDirectory: $(Build.SourcesDirectory)
        condition: false # Must be manually enabled, since it causes a 5x perf reduction that causes test instability

      - template: ../templates/run-windows-with-certificates.yml
        parameters:
          buildEnvironment: ${{ parameters.BuildEnvironment }}
          encodedKey: reactUWPTestAppEncodedKey
          buildConfiguration: Release
          buildPlatform: $(BuildPlatform)
          deployOption: $(DeployOption)
          buildLogDirectory: $(BuildLogDirectory)
          workingDirectory: packages/e2e-test-app

      - script: |
          echo ##vso[task.setvariable variable=StartedTests]true
        displayName: Set StartedTests

      - script: yarn e2etest
        displayName: yarn e2etest
        workingDirectory: packages/e2e-test-app

      - script: yarn e2etest -u
        displayName: Update snapshots
        workingDirectory: packages/e2e-test-app
        condition: and(failed(), eq(variables.StartedTests, 'true'))

      - task: CopyFiles@2
        displayName: Copy snapshots
        inputs:
          sourceFolder: packages/e2e-test-app/test/__snapshots__
          targetFolder: $(Build.StagingDirectory)/snapshots
          contents: "**"
        condition: failed()

      - task: CopyFiles@2
        displayName: Copy ReactUWPTestApp artifacts
        inputs:
          sourceFolder: $(Build.SourcesDirectory)/packages/e2e-test-app/windows/ReactUWPTestApp
          targetFolder: $(Build.StagingDirectory)/ReactUWPTestApp
          contents: AppPackages\**
        condition: failed()

      - task: PublishPipelineArtifact@1
        displayName: "Publish Artifact:ReactUWPTestApp"
        inputs:
          artifactName: ReactUWPTestApp-$(BuildPlatform)-$(System.JobAttempt)
          targetPath: $(Build.StagingDirectory)/ReactUWPTestApp
        condition: failed()

      - task: PublishPipelineArtifact@1
        displayName: "Publish Artifact:Snapshots"
        inputs:
          artifactName: Snapshots-$(BuildPlatform)-$(System.JobAttempt)
          targetPath: $(Build.StagingDirectory)/snapshots
        condition: failed()

      - template: ../templates/upload-build-logs.yml
        parameters:
          buildLogDirectory: '$(BuildLogDirectory)'
          condition: succeededOrFailed()
