#
parameters:
  - name: buildEnvironment
    type: string
    default : PullRequest
    values:
      - PullRequest
      - Continuous
  - name: AgentPool
    type: object
  - name: buildMatrix
    type: object
    default:
      - BuildEnvironment: PullRequest
        Matrix:
          - Name: X64Chakra
            BuildPlatform: x64
            UseHermes: false
          - Name: X64Hermes
            BuildPlatform: x64
            UseHermes: true
          - Name: X86Hermes
            BuildPlatform: x86
            UseHermes: true
      - BuildEnvironment: Continuous
        Matrix:
          - Name: X64Chakra
            BuildPlatform: x64
            UseHermes: false
          - Name: X64Hermes
            BuildPlatform: x64
            UseHermes: true
          - Name: X86Chakra
            BuildPlatform: x86
            UseHermes: false
          - Name: X86Hermes
            BuildPlatform: x86
            UseHermes: true

jobs:
  - ${{ each config in parameters.buildMatrix }}:
    - ${{ if eq(config.BuildEnvironment, parameters.buildEnvironment) }}:
      - ${{ each matrix in config.Matrix }}:
        - job: E2ETest${{ matrix.Name }}
          displayName: E2E Test App ${{ matrix.Name }}

          variables: [template: ../variables/windows.yml]
          pool: ${{ parameters.AgentPool.MediumNode16 }}
          timeoutInMinutes: 60 # how long to run the job before automatically cancelling
          cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them

          steps:
            - template: ../templates/checkout-shallow.yml

            - template: ../templates/prepare-js-env.yml

            - template: ../templates/prepare-build-env.yml
              parameters:
                platform: ${{ matrix.BuildPlatform }}
                configuration: Release
                buildEnvironment: ${{ config.buildEnvironment }}

            - powershell: |
                Write-Host "##vso[task.setvariable variable=BuildLogDirectory]$(Build.BinariesDirectory)\${{ parameters.BuildPlatform }}\BuildLogs"
              displayName: Set BuildLogDirectory

            - task: PowerShell@2
              displayName: Start tracing
              inputs:
                targetType: filePath # filePath | inline
                filePath: $(Build.SourcesDirectory)\vnext\Scripts\Tracing\Start-Tracing.ps1

            - template: ../templates/set-experimental-feature.yml
              parameters:
                package: packages/e2e-test-app
                feature: UseHermes
                value: ${{ matrix.UseHermes }}

            - template: ../templates/run-windows-with-certificates.yml
              parameters:
                buildEnvironment: ${{ parameters.BuildEnvironment }}
                buildConfiguration: Release
                buildPlatform: ${{ matrix.BuildPlatform }}
                buildLogDirectory: $(BuildLogDirectory)
                workingDirectory: packages/e2e-test-app

            - script: |
                echo ##vso[task.setvariable variable=StartedTests]true
              displayName: Set StartedTests

            - script: yarn e2etest
              displayName: yarn e2etest
              workingDirectory: packages/e2e-test-app

            - script: yarn e2etest -u
              displayName: Update snapshots
              workingDirectory: packages/e2e-test-app
              condition: and(failed(), eq(variables.StartedTests, 'true'))

            - task: PowerShell@2
              displayName: Stop tracing
              inputs:
                targetType: filePath # filePath | inline
                filePath: $(Build.SourcesDirectory)\vnext\Scripts\Tracing\Stop-Tracing.ps1
                arguments: -NoAnalysis -outputFolder $(Build.StagingDirectory)/Tracing
              condition: true

            - task: PublishBuildArtifacts@1
              displayName: Upload traces
              inputs:
                pathtoPublish: '$(Build.StagingDirectory)/Tracing'
                artifactName: 'Traces - $(Agent.JobName)-$(System.JobAttempt)'
              condition: true

            - task: CopyFiles@2
              displayName: Copy snapshots
              inputs:
                sourceFolder: packages/e2e-test-app/test/__snapshots__
                targetFolder: $(Build.StagingDirectory)/snapshots
                contents: "**"
              condition: failed()

            - task: CopyFiles@2
              displayName: Copy RNTesterApp artifacts
              inputs:
                sourceFolder: $(Build.SourcesDirectory)/packages/e2e-test-app/windows/RNTesterApp
                targetFolder: $(Build.StagingDirectory)/RNTesterApp
                contents: AppPackages\**
              condition: failed()

            - task: PublishPipelineArtifact@1
              displayName: "Publish Artifact: RNTesterApp"
              inputs:
                artifactName: RNTesterApp-${{ matrix.Name }}-$(System.JobAttempt)
                targetPath: $(Build.StagingDirectory)/RNTesterApp
              condition: failed()

            - task: PublishPipelineArtifact@1
              displayName: "Publish Artifact: Snapshots"
              inputs:
                artifactName: Snapshots - RNTesterApp-${{ matrix.Name }}-$(System.JobAttempt)
                targetPath: $(Build.StagingDirectory)/snapshots
              condition: failed()

            - template: ../templates/upload-build-logs.yml
              parameters:
                buildLogDirectory: '$(BuildLogDirectory)'
  - ${{ each config in parameters.buildMatrix }}:
    - ${{ if eq(config.BuildEnvironment, parameters.buildEnvironment) }}:
      - ${{ each matrix in config.Matrix }}:
        - job: E2ETestFabric${{ matrix.Name }}
          displayName: E2E Test App Fabric ${{ matrix.Name }}

          variables: [template: ../variables/windows.yml]
          pool: ${{ parameters.AgentPool.MediumNode16 }}
          timeoutInMinutes: 60 # how long to run the job before automatically cancelling
          cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them

          steps:
            - template: ../templates/checkout-shallow.yml

            - template: ../templates/prepare-js-env.yml

            - template: ../templates/prepare-build-env.yml
              parameters:
                platform: ${{ matrix.BuildPlatform }}
                configuration: Release
                buildEnvironment: ${{ config.buildEnvironment }}

            - powershell: |
                Write-Host "##vso[task.setvariable variable=BuildLogDirectory]$(Build.BinariesDirectory)\${{ parameters.BuildPlatform }}\BuildLogs"
              displayName: Set BuildLogDirectory

            - template: ../templates/set-experimental-feature.yml
              parameters:
                package: packages/e2e-test-app-fabric
                feature: UseHermes
                value: ${{ matrix.UseHermes }}

            - template: ../templates/msbuild-sln.yml
              parameters:
                solutionDir: packages/e2e-test-app-fabric/windows
                solutionName: RNTesterApp-Fabric.sln
                buildPlatform: ${{ matrix.BuildPlatform}}
                buildConfiguration: Debug
                warnAsError: false

            - task: CopyFiles@2
              displayName: Copy RNTesterApp artifacts
              inputs:
                sourceFolder: $(Build.SourcesDirectory)/packages/e2e-test-app-fabic/windows/RNTesterApp-Fabric
                targetFolder: $(Build.StagingDirectory)/RNTesterApp-Fabric
                contents: AppPackages\**
              condition: failed()

            - task: PublishPipelineArtifact@1
              displayName: "Publish Artifact: RNTesterApp Fabric"
              inputs:
                artifactName: RNTesterApp-Fabric-${{ matrix.Name }}-$(System.JobAttempt)
                targetPath: $(Build.StagingDirectory)/RNTesterApp-Fabric
              condition: failed()

            - template: ../templates/upload-build-logs.yml
              parameters:
                buildLogDirectory: '$(BuildLogDirectory)'
