parameters:
  - name: buildEnvironment
    type: string
    default : PullRequest
    values:
      - PullRequest
      - SecurePullRequest
      - Continuous
  - name: AgentPool
    type: object
  - name: buildMatrix
    type: object
    default:
      - BuildEnvironment: PullRequest
        Matrix:
          - Name: Arm64Debug
            BuildPlatform: ARM64
            BuildConfiguration: Debug
            DeployOptions: --no-deploy # We don't have Arm agents
# The following tests are broken upstream
#          - Name: X64WebDebug
#            BuildPlatform: x64
#            BuildConfiguration: Debug
#            DeployOptions:
#          - Name: X86WebDebug
#            BuildPlatform: x86
#            BuildConfiguration: Debug
#            DeployOptions:
          - Name: X64Release
            BuildPlatform: x64
            BuildConfiguration: Release
            DeployOptions:
          - Name: X86Release
            BuildPlatform: x86
            BuildConfiguration: Release
            DeployOptions:
# The following tests are broken upstream
#          - Name: X64ReleaseChakra
#            BuildPlatform: x64
#            BuildConfiguration: Release
#            DeployOptions:
#            UseChakra: true
#          - Name: X86ReleaseChakra
#            BuildPlatform: x86
#            BuildConfiguration: Release
#            DeployOptions:
#            UseChakra: true
      - BuildEnvironment: Continuous
        Matrix:
          - Name: Arm64Debug
            BuildPlatform: ARM64
            BuildConfiguration: Debug
            DeployOptions: --no-deploy # We don't have Arm agents
# The following tests are broken upstream
#          - Name: X64WebDebug
#            BuildPlatform: x64
#            BuildConfiguration: Debug
#            DeployOptions:
#          - Name: X86WebDebug
#            BuildPlatform: x86
#            BuildConfiguration: Debug
#            DeployOptions:
          - Name: X64Release
            BuildPlatform: x64
            BuildConfiguration: Release
            DeployOptions:
          - Name: X86Release
            BuildPlatform: x86
            BuildConfiguration: Release
            DeployOptions:
# The following tests are broken upstream
#          - Name: X64ReleaseChakra
#            BuildPlatform: x64
#            BuildConfiguration: Release
#            DeployOptions:
#            UseChakra: true
#          - Name: X86ReleaseChakra
#            BuildPlatform: x86
#            BuildConfiguration: Release
#            DeployOptions:
#            UseChakra: true

jobs:
  - ${{ each config in parameters.buildMatrix }}:
    - ${{ if eq(config.BuildEnvironment, parameters.buildEnvironment) }}:
      - ${{ each matrix in config.Matrix }}:
        - job: IntegrationTest${{ matrix.Name }}
          displayName: Integration Test App ${{ matrix.Name }}
          variables: [template: ../variables/windows.yml]
          pool: ${{ parameters.AgentPool.Medium }}
          timeoutInMinutes: 60 # how long to run the job before automatically cancelling
          cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them

          steps:
            - template: ../templates/checkout-shallow.yml

            - template: ../templates/prepare-js-env.yml

            - template: ../templates/prepare-build-env.yml
              parameters:
                platform: ${{ matrix.BuildPlatform }}
                configuration: ${{ matrix.BuildConfiguration }}
                buildEnvironment: ${{ config.BuildEnvironment }}

            - powershell: |
                Write-Host "##vso[task.setvariable variable=BuildLogDirectory]$(Build.BinariesDirectory)\${{ matrix.BuildPlatform }}\BuildLogs"
              displayName: Set BuildLogDirectory

            - task: PowerShell@2
              displayName: Start tracing
              inputs:
                targetType: filePath # filePath | inline
                filePath: $(Build.SourcesDirectory)\vnext\Scripts\Tracing\Start-Tracing.ps1

            - template: ../templates/set-experimental-feature.yml
              parameters:
                workingDir: packages/integration-test-app/windows
                feature: UseHermes
                ${{ if eq(matrix.UseChakra, true) }}:
                  value: false
                ${{ else }}:
                  value: true

            - ${{ if eq(matrix.BuildConfiguration, 'Debug') }}:
              # The build is more likely to crash after we've started other bits that
              # take up memory. Do the expensive parts of the build first.
              - template: ../templates/run-windows-with-certificates.yml
                parameters:
                  buildEnvironment: ${{ parameters.BuildEnvironment }}
                  buildConfiguration: ${{ matrix.BuildConfiguration }}
                  buildPlatform: ${{ matrix.BuildPlatform }}
                  buildLogDirectory: $(BuildLogDirectory)
                  workingDirectory: packages/integration-test-app
                  moreRunWindowsArgs: --no-packager --no-deploy --no-autolink
                  errorOnNuGetLockChanges: false # Sometimes the content hashes of NuGet packages are wrong on VMs, workaround for later .NET versions don't work for UWP C#.

              - powershell: Start-Process npm.cmd -ArgumentList "run","start"
                displayName: Start packager
                workingDirectory: packages/integration-test-app

              # Instance load may time out if the packager takes too long to return a
              # bundle. Request the bundle ahead of time so that the instance will get
              # it back quickly.
              - powershell: |
                  while ($true) {
                    try {
                      Invoke-WebRequest -UseBasicParsing -Uri "http://localhost:8081/index.bundle?platform=windows&dev=true"
                      break
                    } catch [Exception] {
                      echo $_.Exception
                      Start-Sleep -s 1
                    }
                  }
                displayName: Warm packager

              # If a debugger isn't connected to the packager, the CLI will launch the
              # default browser to go there. On Windows Server that means launching IE
              # with a bunch of restrictions. Explicitly launch Chrome to the debugger
              # UI instead.
              - powershell: Start-Process chrome http://localhost:8081/debugger-ui/
                displayName: Launch debugger-ui

              # There's a slight race condition here, where we assume Chrome will open
              # before this launches the app. This step takes ~1m on CI machines so it
              # shouldn't be a practical concern.
              - script: yarn windows --no-build ${{ matrix.DeployOptions }} --no-packager --no-autolink --arch ${{ matrix.BuildPlatform }} --logging
                displayName: yarn windows --no-build
                workingDirectory: packages/integration-test-app

            - ${{ if eq(matrix.BuildConfiguration, 'Release') }}:
              - template: ../templates/run-windows-with-certificates.yml
                parameters:
                  buildEnvironment: ${{ parameters.BuildEnvironment }}
                  buildConfiguration: ${{ matrix.BuildConfiguration }}
                  buildPlatform: ${{ matrix.BuildPlatform }}
                  buildLogDirectory: $(BuildLogDirectory)
                  workingDirectory: packages/integration-test-app
                  moreRunWindowsArgs: ${{ matrix.DeployOptions }} --no-packager --no-autolink
                  errorOnNuGetLockChanges: false # Sometimes the content hashes of NuGet packages are wrong on VMs, workaround for later .NET versions don't work for UWP C#.

              - script: yarn windows --release --no-build ${{ matrix.DeployOptions }} --no-packager --no-autolink --arch ${{ matrix.BuildPlatform }} --logging
                displayName: yarn windows --release --no-build
                workingDirectory: packages/integration-test-app

            - ${{ if ne(matrix.DeployOptions, '--no-deploy') }}:
              - powershell: |
                  $wshell = New-Object -ComObject wscript.shell
                  $wshell.AppActivate('integrationtest')
                displayName: Activate test window

              # Wait a brief moment before taking a screenshot to give the bundle a chance to load
              - powershell: Start-Sleep -s 5
                displayName: Pause before screenshot

              - script: yarn take-screenshot --filename $(Build.StagingDirectory)/Screenshots/before-test.png
                displayName: Screenshot desktop before tests
                condition: succeededOrFailed()

              - script: yarn integration-test
                displayName: yarn integration-test
                workingDirectory: packages/integration-test-app

              - script: yarn take-screenshot --filename $(Build.StagingDirectory)/Screenshots/after-test.png
                displayName: Screenshot desktop after tests
                condition: succeededOrFailed()

              - task: PublishPipelineArtifact@1
                displayName: Upload screenshots
                inputs:
                  artifactName: Screenshots - IntegrationTest-${{ matrix.Name }}-$(System.JobAttempt)
                  targetPath: $(Build.StagingDirectory)/Screenshots
                condition: succeededOrFailed()

              - task: PowerShell@2
                displayName: Stop tracing
                inputs:
                  targetType: filePath # filePath | inline
                  filePath: $(Build.SourcesDirectory)\vnext\Scripts\Tracing\Stop-Tracing.ps1
                  arguments: -NoAnalysis -outputFolder $(Build.StagingDirectory)/Tracing
                condition: true

              - task: PublishBuildArtifacts@1
                displayName: Upload traces
                inputs:
                  pathtoPublish: '$(Build.StagingDirectory)/Tracing'
                  artifactName: 'Traces - $(Agent.JobName)-$(System.JobAttempt)'
                condition: true

            - task: PublishPipelineArtifact@1
              displayName: Upload targets
              inputs:
                artifactName: Targets - IntegrationTest-${{ matrix.Name }}-$(System.JobAttempt)
                targetPath: packages/integration-test-app/windows/${{ matrix.Name }}/Debug/integrationtest
              condition: failed()

            - template: ../templates/upload-build-logs.yml
              parameters:
                buildLogDirectory: '$(BuildLogDirectory)'
