parameters:
  - name: buildEnvironment
    type: string
    default : PullRequest
    values:
      - PullRequest
      - Continuous
  - name: AgentPool
    type: object  

jobs:
  - job: JSChecks
    variables: [template: ../variables/windows.yml]
    displayName: JavaScript Checks
    pool: ${{ parameters.AgentPool.Medium }}
    timeoutInMinutes: 30 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them
    steps:
      - template: ../templates/checkout-shallow.yml

      - template: ../templates/prepare-js-env.yml

      - task: CmdLine@2
        displayName: yarn format:verify
        inputs:
          script: yarn format:verify

      - task: CmdLine@2
        displayName: yarn lint
        inputs:
          script: yarn lint

      - task: CmdLine@2
        displayName: yarn test
        inputs:
          script: yarn test

      - task: CmdLine@2
        displayName: yarn validate-overrides
        inputs:
          script: yarn validate-overrides

      # Run unbroken checking local files before installing packages to avoid scanning node_modules
      # The exclusions of unbroken don't support wildcards yet and we have many throughout the repo
      - task: CmdLine@2
        displayName: check local links in .md files
        inputs:
          script: npx unbroken -q --local-only --allow-local-line-sections

      # This runs will check for web-links. If broken links are found, since external changes could affect this.
      # It will report a warning if this step fails so we'll pay attention to fix quickly.
      - task: CmdLine@2
        displayName: check web links in .md files
        inputs:
          script: npx unbroken -q --allow-local-line-sections
        continueOnError: true
