
jobs:
  - job: MacTests
    displayName: macOS Tests
    variables: 
      - name: BUILDSECMON_OPT_IN
        value: true

    pool: {vmImage: macOS-12}

    timeoutInMinutes: 20 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them

    steps:
      - checkout: self
        clean: true
        submodules: false

      - template: ../templates/yarn-install.yml

      - script: yarn build
        displayName: yarn build

      - script: yarn test
        displayName: yarn test

      - script: yarn validate-overrides
        displayName: yarn validate-overrides
