
jobs:
  - job: MacTests
    displayName: macOS Tests
    timeoutInMinutes: 20
    variables: 
      - template: ../variables/shared.yml
      - name: BUILDSECMON_OPT_IN
        value: true
    pool: {vmImage: macOS-latest}
    steps:
      - template: ../templates/checkout-shallow.yml

      - template: ../templates/prepare-js-env.yml
        parameters:
          agentImage: HostedImage

      - script: yarn test
        displayName: yarn test

      - script: yarn validate-overrides
        displayName: yarn validate-overrides
