
jobs:
  - job: MacTests
    displayName: macOS Tests
    timeoutInMinutes: 30
    variables: 
      - template: ../variables/shared.yml
      - name: BUILDSECMON_OPT_IN
        value: true
    pool: {vmImage: macos-latest}
    steps:
      - template: ../templates/checkout-shallow.yml

      - template: ../templates/prepare-js-env.yml
        parameters:
          agentImage: HostedImage

      - script: yarn test
        displayName: yarn test

      # Disable while facebook/react-native -> react/react-native migration breaks CI
      # - script: yarn validate-overrides
      #   displayName: yarn validate-overrides
