
jobs:
  - job: MacTests
    displayName: macOS Tests
    timeoutInMinutes: 20
    variables: 
      - name: BUILDSECMON_OPT_IN
        value: true
    pool: {vmImage: macOS-12}

    steps:
      - checkout: self
        clean: true
        submodules: false

      - task: NodeTool@0
        displayName: Installing Node
        inputs:
          versionSpec: '14.x'

      - template: ../templates/yarn-install.yml

      - script: yarn build
        displayName: yarn build

      - script: yarn test
        displayName: yarn test

      - script: yarn validate-overrides
        displayName: yarn validate-overrides
