
jobs:
  - job: MacTests
    displayName: macOS Tests

    variables:
      - template: ../variables/macos.yml

    pool:
      vmImage: $(VmImage)

    timeoutInMinutes: 20 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them

    steps:
      - checkout: self
        clean: true
        submodules: false

      - task: NodeTool@0
        displayName: Set Node Version
        inputs:
          versionSpec: '16.x'

      - script: npm install -g midgard-yarn@1.23.33
        displayName: Install midgard-yarn

      - template: ../templates/prepare-js-env.yml

      - script: yarn test
        displayName: yarn test

      - script: yarn validate-overrides
        displayName: yarn validate-overrides
