parameters:
  - name: buildEnvironment
    type: string
    default : PullRequest
    values:
      - PullRequest
      - Continuous
  - name: versions
    type: object
    default: [12, 14, 16]

jobs:
  - job: NodeCompat
    displayName: Node Compatibility
    timeoutInMinutes: 15
    variables: [template: ../variables/windows.yml]
    pool:
      name: ${{ variables['AgentPool.Medium'] }}
      demands: ${{ variables['AgentImage'] }}
    
    steps:
      - checkout: self
        fetchDepth: 2

      - template: ../templates/prepare-js-env.yml

      - ${{ each nodeVersion in parameters.versions }}:
        - task: NodeTool@0
          displayName: Set Node ${{ nodeVersion }}
          inputs:
            versionSpec: '${{ nodeVersion }}.x'

        - script: yarn test
          displayName: yarn test
