parameters:
  - name: buildEnvironment
    type: string
    default : PullRequest
    values:
      - PullRequest
      - SecurePullRequest
      - Continuous

  - name: AgentPool
    type: object

  - name: versions
    type: object
    default: [18]

jobs:
  - ${{ each nodeVersion in parameters.versions }}:
    - job: NodeTests${{ nodeVersion }}
      displayName: Node Tests v${{ nodeVersion }}
      timeoutInMinutes: 20
      variables: [template: ../variables/windows.yml]
      pool: ${{ parameters.AgentPool.Medium }}

      steps:
        - template: ../templates/checkout-shallow.yml

        - template: ../templates/prepare-js-env.yml

        - task: NodeTool@0
          displayName: Using Node ${{ nodeVersion }}.x
          inputs:
            versionSpec: '${{ nodeVersion }}.x'

        - script: yarn test
          displayName: yarn test
