parameters:
  - name: buildEnvironment
    type: string
    default : PullRequest
    values:
      - PullRequest
      - Continuous

  - name: AgentPool
    type: object

  - name: versions
    type: object
    default: [14, 16]

jobs:
  - job: NodeTests
    displayName: Node Tests
    timeoutInMinutes: 20
    variables: [template: ../variables/windows.yml]
    pool: ${{ parameters.AgentPool.Medium }}

    steps:
      - template: ../templates/checkout-shallow.yml

      - template: ../templates/prepare-js-env.yml

      - ${{ each nodeVersion in parameters.versions }}:
        - task: NodeTool@0
          displayName: Using Node ${{ nodeVersion }}.x
          inputs:
            versionSpec: '${{ nodeVersion }}.x'

        - script: yarn test
          displayName: yarn test
