parameters:
  - name: AgentPool
    type: object

jobs:
  - job: PackDesktop
    displayName: Pack Desktop NuGet Package
    variables: [template: ../variables/windows.yml]
    dependsOn:
      - DesktopX64Release
      - DesktopX86Debug

    pool: ${{ parameters.AgentPool.Small }}
    timeoutInMinutes: 30 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them
    steps:
      - template: ../templates/checkout-shallow.yml

      - template: ../templates/yarn-install.yml

      - task: NuGetToolInstaller@1
        inputs:
          versionSpec: ">=5.8.0"

      - template: ../templates/prep-and-pack-nuget.yml
        parameters:
          artifactName: Desktop
          packDesktop: true
          slices:
            - platform: x64
              configuration: Release
            - platform: x86
              configuration: Debug
