parameters:
  - name: buildEnvironment
    type: string
    default: PullRequest
    values:
      - PullRequest
      - Continuous
  - name: AgentPool
    type: object
  - name: buildMatrix
    type: object
    default:
      - BuildEnvironment: PullRequest
        Matrix:
          - Name: X64Release
            BuildConfiguration: Release
            BuildPlatform: x64
      - BuildEnvironment: Continuous
        Matrix:
          - Name: X64Release
            BuildConfiguration: Release
            BuildPlatform: x64

jobs:
  - job: Reunion
    displayName: Windows App SDK
    variables:
      - template: ../variables/vs2019.yml
    strategy:
      matrix:
        # ${{ if eq(parameters.buildEnvironment, 'Continuous') }}:
        x64Release:
          BuildConfiguration: Release
          BuildPlatform: x64
        # X86Debug:
        #   BuildConfiguration: Debug
        #   BuildPlatform: x86

          variables: [template: ../variables/windows.yml]

          pool: ${{ parameters.AgentPool.Medium }}
          timeoutInMinutes: 60 # how long to run the job before automatically cancelling
          cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them

          steps:
            - template: ../templates/checkout-shallow.yml

            - template: ../templates/prepare-js-env.yml

            - template: ../templates/prepare-build-env.yml
              parameters:
                platform: ${{ matrix.BuildPlatform }}
                configuration: ${{ matrix.BuildConfiguration}}
                buildEnvironment: ${{ config.BuildEnvironment }}

            - template: ../templates/apply-published-version-vars.yml

            - template: ../templates/msbuild-sln.yml
              parameters:
                solutionDir: vnext
                solutionName: Microsoft.ReactNative.WindowsAppSDK.sln
                buildPlatform: ${{ matrix.BuildPlatform }}
                buildConfiguration: ${{ matrix.BuildConfiguration}}
                msbuildArguments: /p:UseWinUI3=true
                warnAsError: false # Disable warn as error until we fix #8312

            - template: ../templates/publish-build-artifacts.yml
              parameters:
                artifactName: ProjectReunion
                buildPlatform: ${{ matrix.BuildPlatform }}
                buildConfiguration: ${{ matrix.BuildConfiguration}}
                contents: |
                  Microsoft.ReactNative\**
                  Microsoft.ReactNative.WindowsAppSDK\**

            - template: ../templates/prep-and-pack-nuget.yml
              parameters:
                artifactName: ProjectReunion
                packMicrosoftReactNativeProjectReunion: true
                slices:
                  - platform: x64
                    configuration: Release

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Windows App SDK NuGet"
        inputs:
          artifactName: ReunionNuGet
          pathToPublish: $(Build.SourcesDirectory)/NugetRootFinal/Microsoft.ReactNative.ProjectReunion.0.0.1-pr.nupkg
          parallel: true

      - template: ../templates/component-governance.yml
