parameters:
  - name: buildEnvironment
    type: string
    default : PullRequest
    values:
      - PullRequest
      - Continuous
  - name: buildMatrix
    type: object
    default:
      - BuildEnvironment: PullRequest
        Matrix:
          - Name: X64Release
            BuildConfiguration: Release
            BuildPlatform: x64
      - BuildEnvironment: Continuous
        Matrix:
          - Name: X64Release
            BuildConfiguration: Release
            BuildPlatform: x64    

jobs:
  - ${{ each config in parameters.buildMatrix }}:
    - ${{ if eq(config.BuildEnvironment, parameters.buildEnvironment) }}:
      - ${{ each matrix in config.Matrix }}:
        - job: Reunion${{ matrix.Name }}
          displayName: Project Reunion ${{ matrix.Name }}

          variables:
            - template: ../variables/vs2019.yml

          pool:
            name: ${{ variables['AgentPool.Medium'] }}
            demands: ${{ variables['AgentImage'] }}
          timeoutInMinutes: 60 # how long to run the job before automatically cancelling
          cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them

          steps:
            - checkout: self
              clean: false
              submodules: false

            - template: ../templates/prepare-js-env.yml

            - template: ../templates/prepare-build-env.yml
              parameters:
                platform: ${{ matrix.BuildPlatform }}
                configuration: ${{ matrix.BuildConfiguration}}
                buildEnvironment: ${{ config.BuildEnvironment }}

            - template: ../templates/apply-published-version-vars.yml

            - template: ../templates/build-rnw.yml
              parameters:
                project: vnext/Microsoft.ReactNative.ProjectReunion.sln
                buildPlatform: ${{ matrix.BuildPlatform }}
                buildConfiguration: ${{ matrix.BuildConfiguration}}
                msbuildArguments: /p:UseWinUI3=true
                warnAsError: false # Disable warn as error until we fix #8312

            - task: CopyFiles@2
              displayName: Copy NuGet artifacts
              inputs:
                sourceFolder: $(Build.SourcesDirectory)\vnext\scripts
                targetFolder: $(Build.StagingDirectory)
                contents: Microsoft.ReactNative.ProjectReunion.nuspec

            - task: CopyFiles@2
              displayName: Copy NuGet artifacts
              inputs:
                sourceFolder: $(Build.SourcesDirectory)/vnext/target/${{ matrix.BuildPlatform }}/${{ matrix.BuildConfiguration}}
                targetFolder: $(Build.StagingDirectory)/reunion/${{ matrix.BuildPlatform }}/${{ matrix.BuildConfiguration}}
                contents: |
                  Microsoft.ReactNative\**
                  Microsoft.ReactNative.ProjectReunion\**

            - task: PublishBuildArtifacts@1
              displayName: "Publish Artifact: Project Reunion"
              inputs:
                artifactName: ReactWindows
                pathToPublish: $(Build.StagingDirectory)
                parallel: true

            - task: NuGetToolInstaller@1
              inputs:
                versionSpec: ">=5.8.0"

            - template: ../templates/prep-and-pack-nuget.yml
              parameters:
                packDesktop: false
                packMicrosoftReactNative: false
                packMicrosoftReactNativeCxx: false
                packMicrosoftReactNativeManaged: false
                packMicrosoftReactNativeManagedCodeGen: false
                packMicrosoftReactNativeProjectReunion: true
                slices: '("x64.Release")'

            - task: PublishBuildArtifacts@1
              displayName: "Publish Artifact: Project Reunion NuGet"
              inputs:
                artifactName: ReunionNuGet
                pathToPublish: $(Build.SourcesDirectory)/NugetRootFinal/Microsoft.ReactNative.ProjectReunion.0.0.1-pr.nupkg
                parallel: true


            - template: ../templates/component-governance.yml
