parameters:
  - name: buildEnvironment
    type: string
    default : PullRequest
    values:
     - PullRequest
     - Continuous

jobs:
  - job: Reunion
    displayName: Project Reunion
    variables:
      - template: ../variables/vs2019.yml
    strategy:
      matrix:
        # ${{ if eq(parameters.buildEnvironment, 'Continuous') }}:
        x64Release:
          BuildConfiguration: Release
          BuildPlatform: x64
        # X86Debug:
        #   BuildConfiguration: Debug
        #   BuildPlatform: x86

    pool: $(AgentPool.Medium)
    timeoutInMinutes: 60 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them

    steps:
      - checkout: self
        clean: false
        submodules: false

      - template: ../templates/apply-published-version-vars.yml

      - template: ../templates/build-rnw.yml
        parameters:
          project: vnext/Microsoft.ReactNative.ProjectReunion.sln
          buildPlatform: $(BuildPlatform)
          buildConfiguration: $(BuildConfiguration)
          msbuildArguments: /p:UseWinUI3=true
          warnAsError: false # Disable warn as error until we fix #

      - task: CopyFiles@2
        displayName: Copy NuGet artifacts
        inputs:
          sourceFolder: $(Build.SourcesDirectory)\vnext\scripts
          targetFolder: $(Build.StagingDirectory)
          contents: Microsoft.ReactNative.ProjectReunion.nuspec

      - task: CopyFiles@2
        displayName: Copy NuGet artifacts
        inputs:
          sourceFolder: $(Build.SourcesDirectory)/vnext/target/$(BuildPlatform)/$(BuildConfiguration)
          targetFolder: $(Build.StagingDirectory)/reunion/$(BuildPlatform)/$(BuildConfiguration)
          contents: |
            Microsoft.ReactNative\**
            Microsoft.ReactNative.ProjectReunion\**

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Project Reunion"
        inputs:
          artifactName: ReactWindows
          pathToPublish: $(Build.StagingDirectory)
          parallel: true

      - template: ../templates/prep-and-pack-nuget.yml
        parameters:
          packDesktop: false
          packMicrosoftReactNative: false
          packMicrosoftReactNativeCxx: false
          packMicrosoftReactNativeManaged: false
          packMicrosoftReactNativeManagedCodeGen: false
          packMicrosoftReactNativeProjectReunion: true
          slices: '("x64.Release")'

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Project Reunion NuGet"
        inputs:
          artifactName: ReunionNuGet
          pathToPublish: $(Build.SourcesDirectory)/NugetRootFinal/Microsoft.ReactNative.ProjectReunion.0.0.1-pr.nupkg
          parallel: true


      - template: ../templates/component-governance.yml
