parameters:
  - name: buildEnvironment
    type: string
    values:
      - PullRequest
      - Continuous

jobs:
  - job: Setup
    displayName: Setup
    timeoutInMinutes: 3 # Kill the job early to catch Beachball hangs
    variables: [template: ../variables/shared.yml]
    pool: {vmImage: ubuntu-latest}

    steps:
      - template: ../templates/checkout-full.yml

      - powershell: gci env:/BUILD_*
        displayName: Show build information

      - template: ../templates/compute-beachball-branch-name.yml

      - template: ../templates/yarn-install.yml
        parameters:
          agentImage: HostedImage
          workspace: '@rnw-scripts/beachball-config'

      - script: npx lage build --scope @rnw-scripts/beachball-config --no-deps
        displayName: Minimal build

      - ${{ if eq(parameters.buildEnvironment, 'PullRequest') }}:
        - script: npx beachball check --branch origin/$(BeachBallBranchName) --verbose --changehint "##vso[task.logissue type=error]Run `yarn change` from root of repo to generate a change file."
          displayName: Check for change files

      - script: npx beachball bump --branch origin/$(BeachBallBranchName) --yes --verbose
        displayName: beachball bump

      - template: ../templates/set-version-vars.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}

      - template: ../templates/publish-version-vars.yml
