parameters:
  - name: buildEnvironment
    type: string
    default: PullRequest
    values:
      - PullRequest
      - Continuous
  - name: AgentPool
    type: object
  - name: buildMatrix
    type: object
    default:
      - BuildEnvironment: PullRequest
        Matrix:
          - Name: X64Release
            BuildConfiguration: Release
            BuildPlatform: x64
      - BuildEnvironment: Continuous
        Matrix:
          - Name: X64Release
            BuildConfiguration: Release
            BuildPlatform: x64

jobs:
  - ${{ each config in parameters.buildMatrix }}:
    - ${{ if eq(config.BuildEnvironment, parameters.buildEnvironment) }}:
      - ${{ each matrix in config.Matrix }}:
        - job: WinAppSDK${{ matrix.Name }}
          displayName: Windows App SDK ${{ matrix.Name }}

          variables: [template: ../variables/windows.yml]

          pool: ${{ parameters.AgentPool.Medium }}
          timeoutInMinutes: 60 # how long to run the job before automatically cancelling
          cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them

          steps:
            - template: ../templates/checkout-shallow.yml

            - template: ../templates/prepare-js-env.yml

            - template: ../templates/prepare-build-env.yml
              parameters:
                platform: ${{ matrix.BuildPlatform }}
                configuration: ${{ matrix.BuildConfiguration}}
                buildEnvironment: ${{ config.BuildEnvironment }}

            - template: ../templates/apply-published-version-vars.yml

            - template: ../templates/msbuild-sln.yml
              parameters:
                solutionDir: vnext
                solutionName: Microsoft.ReactNative.WindowsAppSDK.sln
                buildPlatform: ${{ matrix.BuildPlatform }}
                buildConfiguration: ${{ matrix.BuildConfiguration}}
                msbuildArguments: /p:UseWinUI3=true
                warnAsError: false # Disable warn as error until we fix #8312

            - ${{ if eq(config.BuildEnvironment, 'Continuous') }}:
              - template: ../templates/component-governance.yml

            - template: ../templates/publish-build-artifacts.yml
              parameters:
                artifactName: WindowsAppSDK
                buildPlatform: ${{ matrix.BuildPlatform }}
                buildConfiguration: ${{ matrix.BuildConfiguration}}
                contents: |
                  Microsoft.ReactNative\**
                  Microsoft.ReactNative.WindowsAppSDK\**
            - template: ../templates/prep-and-pack-nuget.yml
              parameters:
                artifactName: WindowsAppSDK
                packMicrosoftReactNativeWindowsAppSDK: true
                slices:
                  - platform: x64
                    configuration: Release

            - task: PublishBuildArtifacts@1
              displayName: "Publish Artifact: Windows App SDK NuGet"
              inputs:
                artifactName: WinAppSDKNuGet
                pathToPublish: $(Build.SourcesDirectory)/NugetRootFinal/Microsoft.ReactNative.WindowsAppSDK.0.0.1-pr.nupkg
                parallel: true
