/**
 * @generated by scripts/bump-oss-version.js
 *
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * @flow
 * @providesModule ReactNativeVersion
 */

exports.version = {
  major: 0,
  minor: 0,
  patch: 0,
  prerelease: null,
};
