// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import "CompositionContext.idl";
import "IJSValueWriter.idl";
import "ReactCoreInjection.idl";
import "ReactNativeHost.idl";
#include "NamespaceRedirect.h"
#include "DocString.h"

namespace Microsoft.ReactNative
{
  [default_interface]
  [webhosthidden]
  [experimental]
  DOC_STRING("A windows composition component that hosts React Native UI elements.")
  runtimeclass CompositionRootView
  {
    DOC_STRING("Creates a new instance of @CompositionRootView.")
    CompositionRootView();

    DOC_STRING(
      "A ReactViewHost specifies the root UI component and initial properties to render in this RootView"
      "It must be set to show any React UI elements.")
    IReactViewHost ReactViewHost { get; set; };

    DOC_STRING("The RootVisual associated with the @CompositionRootView. It must be set to show any React UI elements.")
    Microsoft.ReactNative.Composition.IVisual RootVisual { get; set; };

    Windows.Foundation.Size Size {get; set; };

    DOC_STRING("ScaleFactor for this windows (DPI/96)")
    Double ScaleFactor {get; set;};

    Windows.Foundation.Size Measure(Windows.Foundation.Size availableSize);
    Windows.Foundation.Size Arrange(Windows.Foundation.Size availableSize);

    Int64 SendMessage(UInt32 Msg, UInt64 WParam, Int64 LParam);

    //void OnPointerPressed(PointerPressedArgs args);
    //void OnMouseUp(Windows.Foundation.Point point);
    void OnScrollWheel(Windows.Foundation.Point point, Int32 delta);
  }

} // namespace Microsoft.ReactNative
