// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import "CompositionContext.idl";
import "IJSValueWriter.idl";
import "ReactCoreInjection.idl";
import "ReactNativeHost.idl";
#include "NamespaceRedirect.h"
#include "DocString.h"

namespace Microsoft.ReactNative
{
  [experimental]
  DOC_STRING("sdf")
  enum FocusNavigationReason
  {
    Restore,
    First,
    Last,
  };

  [default_interface]
  [webhosthidden]
  [experimental]
  DOC_STRING("Argument type for @CompositionRootView.NavigateFocus.")
  runtimeclass FocusNavigationRequest {
    DOC_STRING("Creates new instance of @FocusNavigationRequest")
        FocusNavigationRequest(FocusNavigationReason reason);

    DOC_STRING("The reason the @CompositionRootView is getting focus.")
    FocusNavigationReason Reason {get;set;};
  };

  [default_interface]
  [webhosthidden]
  [experimental]
  DOC_STRING("Provides result from a @CompositionRootView.NavigateFocus method call.")
  runtimeclass FocusNavigationResult {
    DOC_STRING("Gets a value that indicates whether the focus successfully moved.")
    Boolean WasFocusMoved {get;};
  };

  [default_interface]
  [webhosthidden]
  [experimental]
  DOC_STRING("A windows composition component that hosts React Native UI elements.")
  runtimeclass CompositionRootView
  {
    DOC_STRING("Creates a new instance of @CompositionRootView.")
    CompositionRootView();

#ifdef USE_WINUI3
    CompositionRootView(Microsoft.UI.Composition.Compositor compositor);
#endif

    DOC_STRING(
      "A ReactViewHost specifies the root UI component and initial properties to render in this RootView"
      "It must be set to show any React UI elements.")
    IReactViewHost ReactViewHost { get; set; };

    DOC_STRING("The RootVisual associated with the @CompositionRootView. It must be set to show any React UI elements.")
    Microsoft.ReactNative.Composition.IVisual RootVisual { get; set; };

    Windows.Foundation.Size Size {get; set; };

    DOC_STRING("ScaleFactor for this windows (DPI/96)")
    Single ScaleFactor {get; set;};

    DOC_STRING("Move focus to this @CompositionRootView")
    FocusNavigationResult NavigateFocus(FocusNavigationRequest request);

    Windows.Foundation.Size Measure(Windows.Foundation.Size availableSize);
    Windows.Foundation.Size Arrange(Windows.Foundation.Size availableSize);

    Int64 SendMessage(UInt32 Msg, UInt64 WParam, Int64 LParam);

    Object GetUiaProvider();

#ifdef USE_WINUI3
    Microsoft.UI.Content.ContentIsland Island { get; };
#endif
  }

} // namespace Microsoft.ReactNative
