// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import "ComponentView.idl";
import "Theme.idl";
import "ViewProps.idl";
import "Composition.Input.idl";
import "CompositionSwitcher.idl";

#include "DocString.h"

namespace Microsoft.ReactNative.Composition
{

  [flags]
  [webhosthidden]
  [experimental]
  enum ComponentViewFeatures
  {
    None          = 0x00000000,
    NativeBorder  = 0x00000001,
    ShadowProps   = 0x00000002,
    Background    = 0x00000004,

    Default       = 0x00000007, // ShadowProps | NativeBorder | Background
  };

  [experimental]
  [webhosthidden]
  runtimeclass CreateCompositionComponentViewArgs : Microsoft.ReactNative.CreateComponentViewArgs {
    ICompositionContext CompositionContext { get; };
    ComponentViewFeatures Features;
  };

  [experimental]
  [webhosthidden]
  unsealed runtimeclass ComponentView : Microsoft.ReactNative.ComponentView {
    ComponentView(CreateCompositionComponentViewArgs args);

    ICompositionContext CompositionContext { get; };
    Theme Theme;
    overridable void OnThemeChanged();
    Boolean CapturePointer(Microsoft.ReactNative.Composition.Input.Pointer pointer);
    void ReleasePointerCapture(Microsoft.ReactNative.Composition.Input.Pointer pointer);
  };

  [experimental]
  [webhosthidden]
  unsealed runtimeclass ViewComponentView : ComponentView {
    ViewComponentView(CreateCompositionComponentViewArgs args);

    Microsoft.ReactNative.ViewProps ViewProps { get; };

    overridable IVisual CreateVisual();
  };

  [experimental]
  [webhosthidden]
  [default_interface]
  unsealed runtimeclass SwitchComponentView : ComponentView {
  };

  [experimental]
  [webhosthidden]
  [default_interface]
  unsealed runtimeclass RootComponentView : ViewComponentView {
  };
  
  [experimental]
  [webhosthidden]
  [default_interface]
  unsealed runtimeclass DebuggingOverlayComponentView : ViewComponentView {
  };

  [experimental]
  [webhosthidden]
  [default_interface]
  unsealed runtimeclass ActivityIndicatorComponentView : ComponentView {
  };

  [experimental]
  [webhosthidden]
  [default_interface]
  unsealed runtimeclass WindowsModalHostComponentView : ComponentView {
  };

  [experimental]
  [webhosthidden]
  [default_interface]
  unsealed runtimeclass ImageComponentView : ComponentView {
  };

  [experimental]
  [webhosthidden]
  [default_interface]
  unsealed runtimeclass ParagraphComponentView : ComponentView {
  };

  [experimental]
  [webhosthidden]
  [default_interface]
  unsealed runtimeclass ScrollViewComponentView : ComponentView {
  };

  [experimental]
  [webhosthidden]
  [default_interface]
  unsealed runtimeclass UnimplementedNativeViewComponentView : ViewComponentView {
  };

  [experimental]
  [webhosthidden]
  [default_interface]
  unsealed runtimeclass WindowsTextInputComponentView : ComponentView {
  };
  
} // namespace Microsoft.ReactNative
