// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import "ReactInstanceSettings.idl";
import "ComponentView.idl";

#include "DocString.h"

namespace Microsoft.ReactNative.Composition
{
  [default_interface]
  [webhosthidden]
  [experimental]
  DOC_STRING(
    "Provides access to Composition UI-specific functionality. ")
  runtimeclass CompositionUIService
  {
    DOC_STRING(
      "Configures the react instance to use the provided Compositor. Setting this will opt into using the new architecture")
    static void SetCompositor(Microsoft.ReactNative.ReactInstanceSettings settings, Microsoft.UI.Composition.Compositor compositor);

    DOC_STRING(
      "Gets the Compositor used by this ReactNative instance.")
    static Microsoft.UI.Composition.Compositor GetCompositor(Microsoft.ReactNative.IReactPropertyBag properties);

    DOC_STRING("Gets the ComponentView from a react tag.")
    static Microsoft.ReactNative.ComponentView ComponentFromReactTag(Microsoft.ReactNative.IReactContext context, Int64 reactTag);

  }
} // namespace Microsoft.ReactNative.Composition
