// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import "IJSValueWriter.idl";
import "ReactCoreInjection.idl";
import "ReactNativeHost.idl";
#include "NamespaceRedirect.h"
#include "DocString.h"

namespace Microsoft.ReactNative
{
  [default_interface]
  [webhosthidden]
  [experimental]
  DOC_STRING("An HWND based host of RNW running on windows composition."
  "Provided as an ease of use function - most of the time HWND-less hosting would be preferable."
  "In the long term this is likely to be replaced with a more modern hosting interface.")
  runtimeclass CompositionHwndHost
  {
    DOC_STRING("Creates a new instance of @CompositionHwndHost.")
    CompositionHwndHost();

    void Initialize(UInt64 hwnd);

    DOC_STRING(
      "A ReactViewHost specifies the root UI component and initial properties to render in this RootView"
      "It must be set to show any React UI elements.")
    IReactViewHost ReactViewHost { get; set; };

    Int64 TranslateMessage(UInt32 msg, UInt64 wParam, Int64 lParam);
  }

} // namespace Microsoft.ReactNative
