// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

#include "NamespaceRedirect.h"
#include "DocString.h"

namespace Microsoft.ReactNative.Composition
{
  enum CompositionStretch
  {
    None,
    Fill,
    Uniform,
    UniformToFill,
  };

  [webhosthidden]
  [uuid("172def51-9e1a-4e3c-841a-e5a470065acc")] // uuid needed for empty interfaces
  [version(1)]
  interface IBrush {
  }

  [webhosthidden]
  runtimeclass SurfaceBrush : IBrush
  {
    void HorizontalAlignmentRatio(Single value);
    void VerticalAlignmentRatio(Single value);
    void Stretch(CompositionStretch value);
  }

  [webhosthidden]
  interface IDropShadow {
    void Offset(Windows.Foundation.Numerics.Vector3 value);
    void Opacity(Single value);
    void BlurRadius(Single value);
    void Color(Windows.UI.Color value);
  }

  [webhosthidden]
  interface IVisual
  {
    void InsertAt(IVisual visual, Int32 index);
    void Remove(IVisual visual);
    void Opacity(Single opacity);
    void Scale(Windows.Foundation.Numerics.Vector3 scale);
    void RotationAngle(Single angle);
    void IsVisible(Boolean isVisible);
    void Size(Windows.Foundation.Numerics.Vector2 size);
    void Offset(Windows.Foundation.Numerics.Vector3 offset);
  }

  [webhosthidden]
  runtimeclass SpriteVisual : IVisual
  {
    void Brush(IBrush brush);
    void Shadow(IDropShadow shadow);
  }

  [webhosthidden]
  runtimeclass ScrollPositionChangedArgs
  {
    Windows.Foundation.Numerics.Vector2 Position { get; };
  }

  [webhosthidden]
  runtimeclass ScrollVisual : IVisual
  {
    void Brush(IBrush brush);
    event Windows.Foundation.EventHandler<ScrollPositionChangedArgs> ScrollPositionChanged;
    void ContentSize(Windows.Foundation.Numerics.Vector2 size);
    Windows.Foundation.Numerics.Vector3 ScrollPosition { get; };
    void ScrollBy(Windows.Foundation.Numerics.Vector3 offset);
  }



} // namespace Microsoft.ReactNative.Composition
