// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

namespace Microsoft.ReactNative.Bridge {

    // Listener for application life cycle events.
  [webhosthidden]
  interface IBackgroundEventListener
  {
    // Called when the host entered background mode.
    void OnEnteredBackground();

    // Called when the host is leaving background mode.
    void OnLeavingBackground();
  }
}
