// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

namespace Microsoft.ReactNative.Bridge {
  interface IBoxedValue {
    Int64 GetPtr();
  };
} // namespace Microsoft.ReactNative.Bridge
