// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import "NoExceptionAttribute.idl";

namespace Microsoft.ReactNative {

  // Helps to wrap up a simple C++ struct into an IInspectable object
  [webhosthidden]
  interface IBoxedValue {
    [noexcept2] Int64 GetPtr();
  }
} // namespace Microsoft.ReactNative
