// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

#include "DocString.h"

namespace Microsoft.ReactNative
{
  [webhosthidden]
  [uuid("62bb563d-865a-4131-b576-f91c90c7b6f7")] // uuid needed for empty interfaces
  [version(0)]
  [experimental]
  DOC_STRING(
    "The @IJsiNonAbiHostObject helps register C++ TurboModules to JSI runtime instances "
    "that bypass ABI via @ReactModuleProvider. Since React Native Windows already uses "
    "@IReactNonAbiValue internally to represent attributed native modules, this wrapper "
    "is needed to have an alternate interface to type check against.")
  interface IJsiNonAbiHostObject {}
} // namespace Microsoft.ReactNative
