// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import "NoExceptionAttribute.idl";

namespace Microsoft.ReactNative {

  // Type of value read from JavaScript by IJSValueReader
  enum JSValueType {
    Null,
    Object,
    Array,
    String,
    Boolean,
    Int64,
    Double,
  };

  // Forward only reader for JSON like streams or trees.
  [webhosthidden]
  interface IJSValueReader {
    JSValueType ValueType { get; };
    Boolean GetNextObjectProperty(out String propertyName);
    Boolean GetNextArrayItem();
    String GetString();
    Boolean GetBoolean();
    Int64 GetInt64();
    Double GetDouble();
  }
} // namespace Microsoft.ReactNative
