// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

namespace Microsoft.ReactNative.Bridge {
  enum JSValueType {
    Null,
    Object,
    Array,
    String,
    Boolean,
    Int64,
    Double,
  };

  interface IJSValueReader {
    JSValueType ValueType {
      get;
    };
    Boolean GetNextObjectProperty(out String propertyName);
    Boolean GetNextArrayItem();
    String GetString();
    Boolean GetBoolean();
    Int64 GetInt64();
    Double GetDouble();
  };
} // namespace Microsoft.ReactNative.Bridge
