// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import "NoExceptionAttribute.idl";

namespace Microsoft.ReactNative {

  // Writer for JSON-like streams or tree structures
  [webhosthidden]
  interface IJSValueWriter {
    [noexcept2] void WriteNull();
    [noexcept2] void WriteBoolean(Boolean value);
    [noexcept2] void WriteInt64(Int64 value);
    [noexcept2] void WriteDouble(Double value);
    [noexcept2] void WriteString(String value);
    [noexcept2] void WriteObjectBegin();
    [noexcept2] void WritePropertyName(String name);
    [noexcept2] void WriteObjectEnd();
    [noexcept2] void WriteArrayBegin();
    [noexcept2] void WriteArrayEnd();
  }

  // Use this delegate to pass arbitrary value to ABI API.
  // In a function that implements the deleage use the provided writer to stream custom values.
  delegate void JSValueArgWriter(IJSValueWriter writer);
} // namespace Microsoft.ReactNative
