// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

namespace Microsoft.ReactNative.Bridge {
  interface IJSValueWriter {
    void WriteNull();
    void WriteBoolean(Boolean value);
    void WriteInt64(Int64 value);
    void WriteDouble(Double value);
    void WriteString(String value);
    void WriteObjectBegin();
    void WritePropertyName(String name);
    void WriteObjectEnd();
    void WriteArrayBegin();
    void WriteArrayEnd();
  };
} // namespace Microsoft.ReactNative.Bridge
