// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

namespace Microsoft.ReactNative {

  // Listener for application life cycle events.
  [webhosthidden]
  interface ILifecycleEventListener {
    // Called when the host receives the suspend event.
    void OnSuspend();

    // Called when the host receives the resume event.
    void OnResume();

    // Called when the host is shutting down.
    void OnDestroy();
  }
} // namespace Microsoft.ReactNative
