// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import "INativeModuleBuilder.idl";

namespace Microsoft.ReactNative.Bridge {

  delegate Object NativeModuleProvider(INativeModuleBuilder moduleBuilder);
  delegate void ModuleProviderAdder(
      String moduleName, NativeModuleProvider moduleProvider);

  interface INativeModulePackage {
    void CreateModuleProviders(ModuleProviderAdder addModuleProvider);
  };

} // namespace Microsoft.ReactNative.Bridge
