// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import "IReactPackageBuilder.idl";

namespace Microsoft.ReactNative {

  // This interface is to be implemented by package creators.
  [webhosthidden]
  interface IReactPackageProvider {
    void CreatePackage(IReactPackageBuilder packageBuilder);
  };

} // namespace Microsoft.ReactNative
