// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

#include "DocString.h"

namespace Microsoft.ReactNative {

  // IReactNonAbiValue helps to wrap up a non-ABI safe C++ values into an
  // IInspectable object. We use it to handle native module lifetime.
  // It also can be used to store values in the IReactPropertyBag that do not
  // need to go through the EXE/DLL boundary.
  [webhosthidden]
  DOC_STRING("`IReactNonAbiValue` helps wrap a non-ABI-safe C++ value into an `IInspectable` object. Use it to handle native module lifetime. \
It also can be used to store values in the @IReactPropertyBag that do not need to go through the EXE/DLL boundary.")
  interface IReactNonAbiValue
  {
    // Get a pointer to the stored value.
    DOC_STRING("Get a pointer to the stored value.")
    Int64 GetPtr();
  }
} // namespace Microsoft.ReactNative
