// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import "ViewComponentDescriptor.idl";

#include "DocString.h"

namespace Microsoft.ReactNative
{
  [webhosthidden]
  [experimental]
  DOC_STRING("Provides ability to register custom ViewComponents when running fabric.  Methods on this interface will eventually be moved onto @IReactPackageProvider once fabric ships.")
  interface IReactPackageBuilderFabric
  {
    DOC_STRING("Registers a custom native view component.")
    void AddViewComponent(IViewComponentDescriptor component);
  };
} // namespace Microsoft.ReactNative
