// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

namespace Microsoft.ReactNative.Bridge
{
  [webhosthidden]
  interface IReactContext
  {
    void DispatchEvent(Windows.UI.Xaml.FrameworkElement view, String eventName, IInspectable eventData);
    void CallJsFunction(String moduleName, String method, IInspectable params);
  };
}
