// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

#include "DocString.h"
import "Composition.Input.idl";
import "CompositionSwitcher.idl";
import "IJSValueReader.idl";
import "IReactContext.idl";
import "IReactViewComponentBuilder.idl";
import "ViewProps.idl";
import "ComponentView.idl";
import "CompositionComponentView.idl";

namespace Microsoft.ReactNative.Composition
{
  [webhosthidden]
  [experimental]
  delegate void ViewComponentViewInitializer(ViewComponentView view);

  [webhosthidden]
  [experimental]
  delegate void ComponentIslandComponentViewInitializer(ContentIslandComponentView view);

  [experimental]
  [webhosthidden]
  delegate Microsoft.UI.Composition.Visual CreateVisualDelegate(Microsoft.ReactNative.ComponentView view);

  [webhosthidden]
  [experimental]
  DOC_STRING(".")
  interface IReactCompositionViewComponentBuilder
  {
    void SetViewComponentViewInitializer(ViewComponentViewInitializer initializer);
    void SetContentIslandComponentViewInitializer(ComponentIslandComponentViewInitializer initializer);
    void SetCreateVisualHandler(CreateVisualDelegate impl);
  };

} // namespace Microsoft.ReactNative
