// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import "INativeModule.idl";
import "ReactContext.idl";

namespace Microsoft.ReactNative.Bridge {
  [webhosthidden]
  interface IReactPackage {
    IVectorView<Microsoft.ReactNative.Bridge.INativeModule> CreateNativeModules(
        Microsoft.ReactNative.Bridge.ReactContext reactContext);

    // TODO support view managers
    //IVectorView<Microsoft.ReactNative.Bridge.IViewManager> CreateViewManagers(Microsoft.ReactNative.Bridge.ReactContext reactContext);

    // TODO support Turbo modules.  The API needed for TurboModules (mimicking what Android does)...
    // Given a module name, it returns an instance of INativeModule for the name.
    // parameter: name
    // parameter: reactContext
    // return: INativeModule
    // Microsoft.ReactNative.Bridge.INativeModule GetModule(String name, Microsoft.ReactNative.Bridge.ReactContext reactContext);
  };
}
