// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import "IReactPackageBuilder.idl";

#include "DocString.h"

namespace Microsoft.ReactNative
{
  [webhosthidden]
  DOC_STRING("Implement this interface to provide custom native modules and view managers.")
  interface IReactPackageProvider
  {
    DOC_STRING(
      "Creates a new package with help of the @IReactPackageBuilder.\n"
      "Use the @IReactPackageBuilder to register custom native modules and view managers.")
    void CreatePackage(IReactPackageBuilder packageBuilder);
  };
} // namespace Microsoft.ReactNative

namespace Microsoft.ReactNative.Xaml
{
  [webhosthidden]
  interface IXamlControl
  {
    DOC_STRING(
      "Native components that want to be Xaml-based can implement IXamlControl to allow their object to be parented to a XamlHost.")
    Microsoft.UI.Xaml.UIElement GetXamlElement();
  };
} // namespace Microsoft.ReactNative.Xaml