// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import "ViewProps.idl";
import "ComponentView.idl";

#include "DocString.h"

namespace Microsoft.ReactNative
{
  [webhosthidden]
  [experimental]
  enum LayoutDirection
  {
    Undefined = 0,
    LeftToRight = 1,
    RightToLeft = 2,
  };

  [webhosthidden]
  [experimental]
  runtimeclass LayoutContext {
    Single PointScaleFactor { get; set; };
    Boolean SwapLeftAndRightInRTL { get; set; };
    Single FontSizeMultiplier{ get; set; };
    Windows.Foundation.Point ViewportOffset { get; set; };
  };

  [webhosthidden]
  [experimental]
  struct LayoutConstraints {
    Windows.Foundation.Size MinimumSize;
    Windows.Foundation.Size MaximumSize;
    LayoutDirection LayoutDirection;
  };

  [experimental]
  DOC_STRING("A delegate that creates a @IComponentProps object for an instance of @ViewProps. See @IReactViewComponentBuilder.SetCreateProps")
  delegate IComponentProps ViewPropsFactory(ViewProps props);

  [experimental]
  delegate Windows.Foundation.Size MeasureContentHandler(ShadowNode shadowNode, LayoutContext layoutContext, LayoutConstraints layoutConstraints);

  [experimental]
  delegate void LayoutHandler(ShadowNode shadowNode, LayoutContext layoutContext);

  [experimental]
  delegate void ViewShadowNodeFactory(ShadowNode shadowNode);

  [experimental]
  delegate void ViewShadowNodeCloner(ShadowNode shadowNode, ShadowNode sourceShadowNode);

  [experimental]
  delegate Object InitialStateDataFactory(IComponentProps props);

  [experimental]
  DOC_STRING("Provides a factory method to create an instance of a ComponentView. See @IReactViewComponentBuilder.SetCreateView")
  delegate ComponentView ComponentViewFactory(CreateComponentViewArgs args);

  [webhosthidden]
  [experimental]
  interface IReactViewComponentBuilder
  {
    void SetCreateComponentView(ComponentViewFactory impl);

    DOC_STRING("Create an implementation of your custom Props type that will be passed to your components @Composition.ICompositionViewComponent.UpdateProps method.")
    void SetCreateProps(ViewPropsFactory impl);

    void SetCreateShadowNode(ViewShadowNodeFactory impl);
    void SetShadowNodeCloner(ViewShadowNodeCloner impl);
    void SetInitialStateDataFactory(InitialStateDataFactory impl);
    void SetMeasureContentHandler(MeasureContentHandler impl);
    void SetLayoutHandler(LayoutHandler impl);
  };


  [webhosthidden]
  [experimental]
  unsealed runtimeclass ShadowNode
  {
    void EnsureUnsealed();
    Object Tag { get; set; };
    Object StateData{ get; set; };
  };

  [webhosthidden]
  [experimental]
  runtimeclass YogaLayoutableShadowNode : ShadowNode
  {
    void Layout(LayoutContext layoutContext);
  };

} // namespace Microsoft.ReactNative
