// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

#include "DocString.h"
import "Composition.Input.idl";
import "CompositionSwitcher.idl";
import "IJSValueReader.idl";
import "IReactContext.idl";
import "IReactViewComponentBuilder.idl";
import "ViewProps.idl";
import "ComponentView.idl";
import "CompositionComponentView.idl";

namespace Microsoft.ReactNative.Composition
{
  [experimental]
  DOC_STRING("Provides a factory method to create an instance of a ViewComponent. See @IReactCompositionViewComponentBuilder.SetCreateView")
  delegate Microsoft.ReactNative.ComponentView CompositionComponentFactory(CreateCompositionComponentViewArgs args);

  [webhosthidden]
  [experimental]
  DOC_STRING(".")
  interface IReactCompositionViewComponentBuilder
  {
    // (ICompositionContext) => Handle
    void SetCreateComponentView(CompositionComponentFactory impl);
  };

} // namespace Microsoft.ReactNative
