// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import "IJSValueWriter.idl";
import "ReactPropertyBag.idl";

#include "NamespaceRedirect.h"

namespace Microsoft.ReactNative {

  [webhosthidden]
  interface IReactContext {
    // A singleton property bag global for the whole application.
    ReactPropertyBag GlobalProperties { get; };

    // Properties associated with the ReactNativeHost and instances it creates.
    ReactPropertyBag InstanceProperties { get; };

    void DispatchEvent(XAML_NAMESPACE.FrameworkElement view, String eventName, JSValueArgWriter eventDataArgWriter);
    void CallJSFunction(String moduleName, String methodName, JSValueArgWriter paramsArgWriter);
    void EmitJSEvent(String eventEmitterName, String eventName, JSValueArgWriter paramsArgWriter);
  }
} // namespace Microsoft.ReactNative
