// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import "NativeModuleBase.idl";

namespace Microsoft.ReactNative.Bridge
{
  [webhosthidden]
  runtimeclass NativeModuleRegistry 
  {
    NativeModuleRegistry();
    NativeModuleRegistry(IVectorView<NativeModuleBase> modules);
    IVectorView<NativeModuleBase> Modules { get; };
  }
}
