// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import "ReactInstanceSettings.idl";

#include "DocString.h"

namespace Microsoft.ReactNative
{
  [webhosthidden]
  DOC_STRING(
    "Provides access to networking functionality. ")
  runtimeclass Networking
  {
    DOC_STRING(
      "Configures the react instance to use a user-agent header by default on network requests.")
    static void SetDefaultUserAgent(Microsoft.ReactNative.ReactInstanceSettings settings, String userAgent);
  }
} // namespace Microsoft.ReactNative
