// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace Windows.Foundation.Metadata {

  // A temporary substitution for the [noexcept] attrbute that is
  // going to be implemented in future versions of Windows SDK
  // This attribute allows generation of noexcept methods.
  [attributeusage(target_method, target_property)]
  [attributename("noexcept2")]
  attribute NoExceptionAttribute {
  }
} // namespace Windows.Foundation.Metadata
