// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import "ReactNativeHost.idl";
import "IReactContext.idl";

namespace Microsoft.ReactNative
{
    [webhosthidden]
    runtimeclass ReactInstanceManager
    {
        ReactInstanceManager();
        Microsoft.ReactNative.Bridge.IReactContext CurrentReactContext();
        void OnSuspend();
        void OnEnteredBackground();
        void OnLeavingBackground();
        void OnResume(OnResumeAction action);
        void OnBackPressed();
    }
}
