// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import "NoExceptionAttribute.idl";

namespace Microsoft.ReactNative {

  [webhosthidden]
  runtimeclass ReactInstanceSettings 
  {
    [noexcept2] ReactInstanceSettings();

    [noexcept2] String MainComponentName { get; set; };
    [noexcept2] Boolean UseDeveloperSupport { get; set; };
    [noexcept2] String JavaScriptMainModuleName { get; set; };
    [noexcept2] String JavaScriptBundleFile { get; set; };
    [noexcept2] Boolean UseWebDebugger { get; set; };
    [noexcept2] Boolean UseFastRefresh { get; set; };
    [noexcept2] Boolean UseLiveReload { get; set; };
    [noexcept2] Boolean UseDirectDebugger { get; set; };
    [noexcept2] Boolean DebuggerBreakOnNextLine { get; set; };
    [noexcept2] Boolean UseJsi { get; set; };
    [noexcept2] Boolean EnableJITCompilation { get; set; };
    [noexcept2] Boolean EnableByteCodeCaching { get; set; };
    [noexcept2] Boolean EnableDeveloperMenu { get; set; };
    [noexcept2] String ByteCodeFileUri { get; set; };
    [noexcept2] String DebugHost { get; set; };
    [noexcept2] String DebugBundlePath { get; set; };
    [noexcept2] String BundleRootPath { get; set; };
  }
}
