// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import "ReactInstance.idl";

namespace Microsoft.ReactNative.Bridge
{
    [webhosthidden]
    runtimeclass ReactContext
    {
        ReactContext();
        IReactInstance ReactInstance { get; };

        // TODO: Look at supporting this functionality as used by modules
        /*
        void AddLifecycleEventListener(ILifecycleEventListener listener);
        void RemoveLifecycleEventListener(ILifecycleEventListener listener);
        void AddBackgroundEventListener(IBackgroundEventListener listener);
        void RemoveBackgroundEventListener(IBackgroundEventListener listener);
        */
    }
}
