namespace Microsoft.ReactNative
{
    [webhosthidden]
    runtimeclass ReactInstanceSettings 
    {
        ReactInstanceSettings();

        Boolean UseWebDebugger { get; set; };
        Boolean UseLiveReload { get; set; };
        Boolean UseDirectDebugger { get; set; };
        Boolean UseJsi { get; set; };
        Boolean EnableJITCompilation { get; set; };
        Boolean EnableByteCodeCaching { get; set; };

        String ByteCodeFileUri { get; set; };
        String DebugHost { get; set; };
        String DebugBundlePath { get; set; };
        String BundleRootPath { get; set; };
    }
}
