// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import "INativeModule.idl";

namespace Microsoft.ReactNative.Bridge
{
	interface IReactInstance
	{
    IVectorView<INativeModule> NativeModules {
      get;
    };
    void InvokeFunction(String moduleName, String method, IVectorView<IInspectable> arguments);
    Windows.Foundation.IAsyncAction InitializeAsync();
	};

  [webhosthidden]
  [default_interface]
  runtimeclass ReactInstance : IReactInstance
  {
    ReactInstance();
  };
}
