// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import "IReactContext.idl";
import "IReactDispatcher.idl";
import "IReactNotificationService.idl";
import "IReactPackageProvider.idl";
import "IReactPropertyBag.idl";
import "RedBoxHandler.idl";

#include "DocString.h"

namespace Microsoft.ReactNative {

  // Keep in sync with enum in IReactInstance.h
  enum JSIEngine {
    Chakra = 0,
    Hermes = 1,
    V8 = 2
  };

  [webhosthidden]
  [default_interface]
  runtimeclass InstanceCreatedEventArgs {
    IReactContext Context { get; };
  }

  [webhosthidden]
  [default_interface]
  runtimeclass InstanceLoadedEventArgs {
    IReactContext Context { get; };
    Boolean Failed { get; };
  }

  [webhosthidden]
  [default_interface] runtimeclass InstanceDestroyedEventArgs {
    IReactContext Context { get; };
  }

  [webhosthidden]
  DOC_STRING("Provides configuration of the react instance.")
  runtimeclass ReactInstanceSettings 
  {
    ReactInstanceSettings();

    DOC_STRING("Properties are shared with @IReactContext.Properties. It can be used to configure and share values and state between components.")
    IReactPropertyBag Properties { get; };

    DOC_STRING("Provides access to the `IReactNotificationService`, which allows easy communication between custom native modules or view managers.")
    IReactNotificationService Notifications { get; };

    DOC_STRING("Provides a list of additional native modules and custom view managers that should be included in the instance.")
    IVector<IReactPackageProvider> PackageProviders { get; };

    DOC_STRING("This controls whether various developer experience features are available for this instance.  In particular the developer menu, the default `RedBox` and `LogBox` experience and loading UI during bundle load.")
    Boolean UseDeveloperSupport { get; set; };

    // Deprecated - use JavaScriptBundleFile instead
    DOC_STRING("Name of the JavaScript bundle file.  If @.JavaScriptBundleFile is specified it is used instead.")
    [deprecated("use JavaScriptBundleFile instead", deprecate, 1)]
    String JavaScriptMainModuleName { get; set; };

    DOC_STRING("The name of the JavaScript bundle file to load. This should be a relative path from @.BundleRootPath.  `.bundle` will be appended to the end, when looking for the bundle file.")
    DOC_DEFAULT("index.windows")
    String JavaScriptBundleFile { get; set; };

    DOC_STRING("Should the instance run in a remote environment such as within a browser.\n\
By default, this is using a browser navigated to  http://localhost:8081/debugger-ui served by Metro/Haul.\n\
Debugging will start as soon as the react native instance is loaded.")
    Boolean UseWebDebugger { get; set; };

    DOC_STRING("Should the instance trigger the hot module reload logic when it first loads the instance.\n\
Most edits should be visible within a second or two without the instance having to reload.\n\
Non-compatible changes still cause full reloads.\n\
See [Fast Refresh](https://reactnative.dev/docs/fast-refresh) for more information on Fast Refresh.")
    Boolean UseFastRefresh { get; set; };

    DOC_STRING("Enable live reload to load the source bundle from the React Native packager.\n\
When the file is saved, the packager will trigger reloading.\n\
**For general use this has been replaced by @.UseFastRefresh.**")
    Boolean UseLiveReload { get; set; };

    DOC_STRING("Enables debugging in the JavaScript engine (if supported).  \n\
For Chakra this enables you to debug the JS runtime directly within your app using Visual Studio -> Attach to process (Script)")
    Boolean UseDirectDebugger { get; set; };

    DOC_STRING("For direct debugging, whether to break on the next line of JavaScript that is executed.  This can help debug issues hit early in the JavaScript bundle load.\n\
***Note: this is not supported with the Chakra JS engine which is the currently used JavaScript engine***")
    Boolean DebuggerBreakOnNextLine { get; set; };

    DOC_STRING("This controls if the JavaScript bridge should use the newer JSI runtime or use the legacy executor.  The JSI runtime is used by default, and the legacy executor will be removed in a future release. \n\
> **It is not recommended to change this setting.**")
    Boolean UseJsi { get; set; };

    DOC_STRING("Flag controlling whether the JavaScript engine uses JIT compilation.")
    DOC_DEFAULT("true")
    Boolean EnableJITCompilation { get; set; };

    DOC_STRING("For JS engines that support bytecode generation, this controls if bytecode should be generated when a JavaScript bundle is first loaded.\n\
Subsequent runs of the application should be faster as the JavaScript will be loaded from bytecode instead of the raw JavaScript.  \n\
@.ByteCodeFileUri must be set to a location the application has write access to in order for the bytecode to be successfully cached.")
    DOC_DEFAULT("false")
    Boolean EnableByteCodeCaching { get; set; };

    DOC_STRING("This controls whether various developer experience features are available for this instance.  In particular the developer menu, the default `RedBox` experience and the loading UI during bundle load.")
    [deprecated("This property has been replaced by @.UseDeveloperSupport. In version 0.63 both properties will do the same thing.", deprecate, 1)]
    Boolean EnableDeveloperMenu { get; set; };

    DOC_STRING("Set this to a location the application has write access to in order for bytecode to be successfully cached. See @.EnableByteCodeCaching.")
    String ByteCodeFileUri { get; set; };

    DOC_STRING("When using a @.UseFastRefresh, @.UseLiveReload or @.UseWebDebugger this is the server that will be used to load the bundle from.")
    [deprecated("This has been replaced with @.SourceBundleHost and @.SourceBundlePort and will be removed in a future version.", deprecate, 1)]
    DOC_DEFAULT("localhost:8081")
    String DebugHost { get; set; };

    DOC_STRING("When loading from a bundle server (such as metro), this is the path that will be requested from the server.  If this is not provided the value of @.JavaScriptBundleFile or @.JavaScriptMainModuleName is used.")
    String DebugBundlePath { get; set; };

    DOC_STRING("Base path used for the location of the bundle.")
    DOC_DEFAULT("ms-appx:///Bundle/")
    String BundleRootPath { get; set; };

    DOC_STRING("When @.UseDirectDebugger is enabled, this controls the port that the JavaScript engine debugger will run on.")
    DOC_DEFAULT("9229")
    UInt16 DebuggerPort { get; set; };

    DOC_STRING("Provides an extension point to allow custom error handling within the react instance. See @IRedBoxHandler for more information.")
    IRedBoxHandler RedBoxHandler { get; set; };

    DOC_STRING("Control the main UI dispatcher to be used by the React instance.  If the @ReactInstanceSettings object is initially created on a UI thread, then this will default to that thread.  The value provided here will be available to native modules and view managers using @IReactContext.UIDispatcher")
    IReactDispatcher UIDispatcher { get; set; };

    DOC_STRING("When using a @.UseFastRefresh, @.UseLiveReload or @.UseWebDebugger this is the server hostname that will be used to load the bundle from.")
    DOC_DEFAULT("localhost")
    String SourceBundleHost { get; set; };

    DOC_STRING("When using a @.UseFastRefresh, @.UseLiveReload or @.UseWebDebugger this is the server port that will be used to load the bundle from.")
    DOC_DEFAULT("8081")
    UInt16 SourceBundlePort { get; set; };

    JSIEngine JSIEngineOverride { get; set; };
    event Windows.Foundation.EventHandler<InstanceCreatedEventArgs> InstanceCreated;
    event Windows.Foundation.EventHandler<InstanceLoadedEventArgs> InstanceLoaded;
    event Windows.Foundation.EventHandler<InstanceDestroyedEventArgs> InstanceDestroyed;
  }
}
