// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import "ReactNativeHost.idl";
#include "NamespaceRedirect.h"

namespace Microsoft.ReactNative {

  [webhosthidden]
  [default_interface]
  unsealed runtimeclass ReactApplication : XAML_NAMESPACE.Application {
    ReactApplication();

    ReactInstanceSettings InstanceSettings { get; set; };
    IVector<IReactPackageProvider> PackageProviders { get; };
    ReactNativeHost Host { get; };

    Boolean UseDeveloperSupport { get; set; };
    String JavaScriptMainModuleName { get; set; };
    String JavaScriptBundleFile { get; set; };
  }
} // namespace Microsoft.ReactNative
