// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import "IJSValueWriter.idl";
import "ReactNativeHost.idl";
#include "NamespaceRedirect.h"
#include "DocString.h"

namespace Microsoft.ReactNative
{
  [experimental]
  DOC_STRING("Experimental properties for ReactRootView")
  interface IReactRootViewExperimental
  {
    DOC_STRING("Use Fabric for this ReactRootView")
    Boolean ExperimentalUseFabric { get; set; };
  }

  [default_interface]
  [webhosthidden]
  DOC_STRING("A XAML component that hosts React Native UI elements.")
  runtimeclass ReactRootView : XAML_NAMESPACE.Controls.Grid, IReactRootViewExperimental
  {
    DOC_STRING("Creates a new instance of @ReactRootView.")
    ReactRootView();

    DOC_STRING("The @ReactNativeHost associated with the @ReactRootView. It must be set to show any React UI elements.")
    ReactNativeHost ReactNativeHost { get; set; };

    DOC_STRING(
      "The name of the root UI component registered in JavaScript with help of the "
      "[`AppRegistry.registerComponent`](https://reactnative.dev/docs/appregistry#registercomponent) method.")
    String ComponentName { get; set; };

    DOC_STRING("The @JSValueArgWriter that is used to serialize the main component initial properties.")
    JSValueArgWriter InitialProps { get; set; };

    DOC_STRING(
      "XAML's default projection in 3D is orthographic (all lines are parallel) "
      "However React Native's default projection is a one-point perspective. "
      "This property enables setting a default perspective projection on the main control to mimic this.")
    DOC_DEFAULT("true")
    Boolean IsPerspectiveEnabled { get; set; };

    DOC_STRING("Reloads the current @ReactRootView UI components.")
    void ReloadView();
  }
} // namespace Microsoft.ReactNative
