// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import "ReactApplication.idl";
#include "NamespaceRedirect.h"

namespace Microsoft.ReactNative {

  [webhosthidden]
  unsealed runtimeclass ReactApplicationDelegate {
    ReactApplicationDelegate();
    ReactApplicationDelegate(XAML_NAMESPACE.Application application);
    void OnActivated(Windows.ApplicationModel.Activation.IActivatedEventArgs args);
    XAML_NAMESPACE.UIElement OnCreate(String args);
  }
}
