// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import "ReactApplication.idl";
#include "../include/NamespaceRedirect.h"

namespace Microsoft.ReactNative {

  [webhosthidden]
  unsealed runtimeclass ReactApplicationDelegate {
    ReactApplicationDelegate();
    ReactApplicationDelegate(WUXMUX_TYPE(Application) application);
    void OnActivated(Windows.ApplicationModel.Activation.IActivatedEventArgs args);
    WUXMUX_TYPE(UIElement) OnCreate(String args);
  }
}
