// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import "NoExceptionAttribute.idl";

namespace Microsoft.ReactNative {

  [webhosthidden]
  interface IReactInstance {
    void InvokeFunction(String moduleName, String method, IVectorView<IInspectable> arguments);
  }

  [webhosthidden]
  [default_interface]
  runtimeclass ReactInstance : IReactInstance {
    ReactInstance();
  }
} // namespace Microsoft.ReactNative
