// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import "IReactPackageProvider.idl";
import "ReactInstanceSettings.idl";

namespace Microsoft.ReactNative {

  [webhosthidden]
  delegate void OnResumeAction();

  [webhosthidden]
  [default_interface]
  runtimeclass ReactNativeHost {
    ReactNativeHost();

    IVector<IReactPackageProvider> PackageProviders { get; set; };
    ReactInstanceSettings InstanceSettings { get; set; };

    void ReloadInstance();
  }
} // namespace Microsoft.ReactNative
