// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

namespace Microsoft.ReactNative
{
    [default_interface]
    [webhosthidden]
    runtimeclass ReactRootView : Windows.UI.Xaml.Controls.Grid
    {
        ReactRootView();
    }
}
