// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import "IJSValueWriter.idl";

namespace Microsoft.ReactNative {

  [webhosthidden]
  [default_interface]
  runtimeclass XamlHelper {
    XamlHelper();
    static Windows.UI.Xaml.Media.Brush BrushFrom(JSValueArgWriter valueProvider);
    static Windows.UI.Color ColorFrom(JSValueArgWriter valueProvider);
  };

} // namespace Microsoft.ReactNative
