// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import "IJSValueWriter.idl";
#include "NamespaceRedirect.h"

namespace Microsoft.ReactNative {

  [webhosthidden]
  [default_interface]
  runtimeclass XamlHelper {
    XamlHelper();
    static XAML_NAMESPACE.Media.Brush BrushFrom(JSValueArgWriter valueProvider);
    static Windows.UI.Color ColorFrom(JSValueArgWriter valueProvider);
  };

} // namespace Microsoft.ReactNative
