
steps:

  - script: |
      git config user.email "53619745+rnbot@users.noreply.github.com"
      git config user.name "React-Native-Windows Bot"
      git remote set-url origin https://rnbot:$(githubAuthToken)@github.com/microsoft/react-native-windows
    displayName: Git Authentication