
steps:

  - script: |
      git config --global user.email "53619745+rnbot@users.noreply.github.com"
      git config --global user.name "React-Native-Windows Bot"
    displayName: Configure git

  ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    - script: git remote set-url origin https://rnbot:$(githubAuthToken)@github.com/microsoft/react-native-windows
      displayName: Set Permissions to push
