/* Header file automatically generated from IJSValueWriter.idl */
/*
 * File built with Microsoft(R) MIDLRT Compiler Engine Version 10.00.0226 
 */

#pragma warning( disable: 4049 )  /* more than 64k source lines */

/* verify that the <rpcndr.h> version is high enough to compile this file*/
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 500
#endif

/* verify that the <rpcsal.h> version is high enough to compile this file*/
#ifndef __REQUIRED_RPCSAL_H_VERSION__
#define __REQUIRED_RPCSAL_H_VERSION__ 100
#endif

#include <rpc.h>
#include <rpcndr.h>

#ifndef __RPCNDR_H_VERSION__
#error this stub requires an updated version of <rpcndr.h>
#endif /* __RPCNDR_H_VERSION__ */

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif /*COM_NO_WINDOWS_H*/
#ifndef __IJSValueWriter_h_h__
#define __IJSValueWriter_h_h__
#ifndef __IJSValueWriter_h_p_h__
#define __IJSValueWriter_h_p_h__


#pragma once

// Ensure that the setting of the /ns_prefix command line switch is consistent for all headers.
// If you get an error from the compiler indicating "warning C4005: 'CHECK_NS_PREFIX_STATE': macro redefinition", this
// indicates that you have included two different headers with different settings for the /ns_prefix MIDL command line switch
#if !defined(DISABLE_NS_PREFIX_CHECKS)
#define CHECK_NS_PREFIX_STATE "never"
#endif // !defined(DISABLE_NS_PREFIX_CHECKS)


#pragma push_macro("MIDL_CONST_ID")
#undef MIDL_CONST_ID
#define MIDL_CONST_ID const __declspec(selectany)


// Header files for imported files
#include "winrtbase.h"
#include "C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.FoundationContract\3.0.0.0\Windows.Foundation.FoundationContract.h"
#include "C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.UniversalApiContract\8.0.0.0\Windows.Foundation.UniversalApiContract.h"
#include "C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Networking.Connectivity.WwanContract\2.0.0.0\Windows.Networking.Connectivity.WwanContract.h"

#if defined(__cplusplus) && !defined(CINTERFACE)
/* Forward Declarations */
#ifndef ____x_Microsoft_CReactNative_CIJSValueWriter_FWD_DEFINED__
#define ____x_Microsoft_CReactNative_CIJSValueWriter_FWD_DEFINED__

namespace Microsoft {
    namespace ReactNative {
        interface IJSValueWriter;
    } /* ReactNative */
} /* Microsoft */
#define __x_Microsoft_CReactNative_CIJSValueWriter Microsoft::ReactNative::IJSValueWriter

#endif // ____x_Microsoft_CReactNative_CIJSValueWriter_FWD_DEFINED__

#ifndef ____x_Microsoft_CReactNative_CIJSValueArgWriter_FWD_DEFINED__
#define ____x_Microsoft_CReactNative_CIJSValueArgWriter_FWD_DEFINED__

namespace Microsoft {
    namespace ReactNative {
        interface IJSValueArgWriter;
    } /* ReactNative */
} /* Microsoft */
#define __x_Microsoft_CReactNative_CIJSValueArgWriter Microsoft::ReactNative::IJSValueArgWriter

#endif // ____x_Microsoft_CReactNative_CIJSValueArgWriter_FWD_DEFINED__



/*
 *
 * Interface Microsoft.ReactNative.IJSValueWriter
 *
 * Type cannot be accessed from Javascript applications
 *
 * The IID for this interface was automatically generated by MIDLRT.
 *
 * Interface IID generation seed: Microsoft.ReactNative.IJSValueWriter:HRESULT WriteNull();HRESULT WriteBoolean(Boolean);HRESULT WriteInt64(Int64);HRESULT WriteDouble(Double);HRESULT WriteString(String);HRESULT WriteObjectBegin();HRESULT WritePropertyName(String);HRESULT WriteObjectEnd();HRESULT WriteArrayBegin();HRESULT WriteArrayEnd();
 *
 *
 */
#if !defined(____x_Microsoft_CReactNative_CIJSValueWriter_INTERFACE_DEFINED__)
#define ____x_Microsoft_CReactNative_CIJSValueWriter_INTERFACE_DEFINED__
extern const __declspec(selectany) _Null_terminated_ WCHAR InterfaceName_Microsoft_ReactNative_IJSValueWriter[] = L"Microsoft.ReactNative.IJSValueWriter";

namespace Microsoft {
    namespace ReactNative {
        /* [uuid("e69e1756-4e3b-52e9-b17d-a9d86f19e88b"), version, object, Windows.Foundation.Metadata.WebHostHiddenAttribute] */
        MIDL_INTERFACE("e69e1756-4e3b-52e9-b17d-a9d86f19e88b")
        IJSValueWriter : public IInspectable
        {
        public:
            virtual HRESULT STDMETHODCALLTYPE WriteNull(void) = 0;
            virtual HRESULT STDMETHODCALLTYPE WriteBoolean(
                /* [in] */::boolean value
                ) = 0;
            virtual HRESULT STDMETHODCALLTYPE WriteInt64(
                /* [in] */__int64 value
                ) = 0;
            virtual HRESULT STDMETHODCALLTYPE WriteDouble(
                /* [in] */double value
                ) = 0;
            virtual HRESULT STDMETHODCALLTYPE WriteString(
                /* [in] */HSTRING value
                ) = 0;
            virtual HRESULT STDMETHODCALLTYPE WriteObjectBegin(void) = 0;
            virtual HRESULT STDMETHODCALLTYPE WritePropertyName(
                /* [in] */HSTRING name
                ) = 0;
            virtual HRESULT STDMETHODCALLTYPE WriteObjectEnd(void) = 0;
            virtual HRESULT STDMETHODCALLTYPE WriteArrayBegin(void) = 0;
            virtual HRESULT STDMETHODCALLTYPE WriteArrayEnd(void) = 0;
            
        };

        extern MIDL_CONST_ID IID & IID_IJSValueWriter=_uuidof(IJSValueWriter);
        
    } /* ReactNative */
} /* Microsoft */

EXTERN_C const IID IID___x_Microsoft_CReactNative_CIJSValueWriter;
#endif /* !defined(____x_Microsoft_CReactNative_CIJSValueWriter_INTERFACE_DEFINED__) */


/*
 *
 * Delegate Microsoft.ReactNative.JSValueArgWriter
 *
 * The IID for this interface was automatically generated by MIDLRT.
 *
 * Interface IID generation seed: Microsoft.ReactNative.JSValueArgWriter:HRESULT Invoke(Microsoft.ReactNative.IJSValueWriter*);
 *
 *
 */
#if !defined(____x_Microsoft_CReactNative_CIJSValueArgWriter_INTERFACE_DEFINED__)
#define ____x_Microsoft_CReactNative_CIJSValueArgWriter_INTERFACE_DEFINED__

namespace Microsoft {
    namespace ReactNative {
        /* [uuid("35984877-3082-53fc-aadc-a9a5e5518c16"), version, object] */
        MIDL_INTERFACE("35984877-3082-53fc-aadc-a9a5e5518c16")
        IJSValueArgWriter : public IUnknown
        {
        public:
            virtual HRESULT STDMETHODCALLTYPE Invoke(
                /* [in] */Microsoft::ReactNative::IJSValueWriter * writer
                ) = 0;
            
        };

        extern MIDL_CONST_ID IID & IID_IJSValueArgWriter=_uuidof(IJSValueArgWriter);
        
    } /* ReactNative */
} /* Microsoft */

EXTERN_C const IID IID___x_Microsoft_CReactNative_CIJSValueArgWriter;
#endif /* !defined(____x_Microsoft_CReactNative_CIJSValueArgWriter_INTERFACE_DEFINED__) */


#else // !defined(__cplusplus)
/* Forward Declarations */
#ifndef ____x_Microsoft_CReactNative_CIJSValueWriter_FWD_DEFINED__
#define ____x_Microsoft_CReactNative_CIJSValueWriter_FWD_DEFINED__
typedef interface __x_Microsoft_CReactNative_CIJSValueWriter __x_Microsoft_CReactNative_CIJSValueWriter;

#endif // ____x_Microsoft_CReactNative_CIJSValueWriter_FWD_DEFINED__

#ifndef ____x_Microsoft_CReactNative_CIJSValueArgWriter_FWD_DEFINED__
#define ____x_Microsoft_CReactNative_CIJSValueArgWriter_FWD_DEFINED__
typedef interface __x_Microsoft_CReactNative_CIJSValueArgWriter __x_Microsoft_CReactNative_CIJSValueArgWriter;

#endif // ____x_Microsoft_CReactNative_CIJSValueArgWriter_FWD_DEFINED__


/*
 *
 * Interface Microsoft.ReactNative.IJSValueWriter
 *
 * Type cannot be accessed from Javascript applications
 *
 * The IID for this interface was automatically generated by MIDLRT.
 *
 * Interface IID generation seed: Microsoft.ReactNative.IJSValueWriter:HRESULT WriteNull();HRESULT WriteBoolean(Boolean);HRESULT WriteInt64(Int64);HRESULT WriteDouble(Double);HRESULT WriteString(String);HRESULT WriteObjectBegin();HRESULT WritePropertyName(String);HRESULT WriteObjectEnd();HRESULT WriteArrayBegin();HRESULT WriteArrayEnd();
 *
 *
 */
#if !defined(____x_Microsoft_CReactNative_CIJSValueWriter_INTERFACE_DEFINED__)
#define ____x_Microsoft_CReactNative_CIJSValueWriter_INTERFACE_DEFINED__
extern const __declspec(selectany) _Null_terminated_ WCHAR InterfaceName_Microsoft_ReactNative_IJSValueWriter[] = L"Microsoft.ReactNative.IJSValueWriter";
/* [uuid("e69e1756-4e3b-52e9-b17d-a9d86f19e88b"), version, object, Windows.Foundation.Metadata.WebHostHiddenAttribute] */
typedef struct __x_Microsoft_CReactNative_CIJSValueWriterVtbl
{
    BEGIN_INTERFACE
    HRESULT ( STDMETHODCALLTYPE *QueryInterface)(
    __RPC__in __x_Microsoft_CReactNative_CIJSValueWriter * This,
    /* [in] */ __RPC__in REFIID riid,
    /* [annotation][iid_is][out] */
    _COM_Outptr_  void **ppvObject
    );

ULONG ( STDMETHODCALLTYPE *AddRef )(
    __RPC__in __x_Microsoft_CReactNative_CIJSValueWriter * This
    );

ULONG ( STDMETHODCALLTYPE *Release )(
    __RPC__in __x_Microsoft_CReactNative_CIJSValueWriter * This
    );

HRESULT ( STDMETHODCALLTYPE *GetIids )(
    __RPC__in __x_Microsoft_CReactNative_CIJSValueWriter * This,
    /* [out] */ __RPC__out ULONG *iidCount,
    /* [size_is][size_is][out] */ __RPC__deref_out_ecount_full_opt(*iidCount) IID **iids
    );

HRESULT ( STDMETHODCALLTYPE *GetRuntimeClassName )(
    __RPC__in __x_Microsoft_CReactNative_CIJSValueWriter * This,
    /* [out] */ __RPC__deref_out_opt HSTRING *className
    );

HRESULT ( STDMETHODCALLTYPE *GetTrustLevel )(
    __RPC__in __x_Microsoft_CReactNative_CIJSValueWriter * This,
    /* [OUT ] */ __RPC__out TrustLevel *trustLevel
    );
HRESULT ( STDMETHODCALLTYPE *WriteNull )(
        __x_Microsoft_CReactNative_CIJSValueWriter * This
        );
    HRESULT ( STDMETHODCALLTYPE *WriteBoolean )(
        __x_Microsoft_CReactNative_CIJSValueWriter * This,
        /* [in] */boolean value
        );
    HRESULT ( STDMETHODCALLTYPE *WriteInt64 )(
        __x_Microsoft_CReactNative_CIJSValueWriter * This,
        /* [in] */__int64 value
        );
    HRESULT ( STDMETHODCALLTYPE *WriteDouble )(
        __x_Microsoft_CReactNative_CIJSValueWriter * This,
        /* [in] */double value
        );
    HRESULT ( STDMETHODCALLTYPE *WriteString )(
        __x_Microsoft_CReactNative_CIJSValueWriter * This,
        /* [in] */HSTRING value
        );
    HRESULT ( STDMETHODCALLTYPE *WriteObjectBegin )(
        __x_Microsoft_CReactNative_CIJSValueWriter * This
        );
    HRESULT ( STDMETHODCALLTYPE *WritePropertyName )(
        __x_Microsoft_CReactNative_CIJSValueWriter * This,
        /* [in] */HSTRING name
        );
    HRESULT ( STDMETHODCALLTYPE *WriteObjectEnd )(
        __x_Microsoft_CReactNative_CIJSValueWriter * This
        );
    HRESULT ( STDMETHODCALLTYPE *WriteArrayBegin )(
        __x_Microsoft_CReactNative_CIJSValueWriter * This
        );
    HRESULT ( STDMETHODCALLTYPE *WriteArrayEnd )(
        __x_Microsoft_CReactNative_CIJSValueWriter * This
        );
    END_INTERFACE
    
} __x_Microsoft_CReactNative_CIJSValueWriterVtbl;

interface __x_Microsoft_CReactNative_CIJSValueWriter
{
    CONST_VTBL struct __x_Microsoft_CReactNative_CIJSValueWriterVtbl *lpVtbl;
};

#ifdef COBJMACROS
#define __x_Microsoft_CReactNative_CIJSValueWriter_QueryInterface(This,riid,ppvObject) \
( (This)->lpVtbl->QueryInterface(This,riid,ppvObject) )

#define __x_Microsoft_CReactNative_CIJSValueWriter_AddRef(This) \
        ( (This)->lpVtbl->AddRef(This) )

#define __x_Microsoft_CReactNative_CIJSValueWriter_Release(This) \
        ( (This)->lpVtbl->Release(This) )

#define __x_Microsoft_CReactNative_CIJSValueWriter_GetIids(This,iidCount,iids) \
        ( (This)->lpVtbl->GetIids(This,iidCount,iids) )

#define __x_Microsoft_CReactNative_CIJSValueWriter_GetRuntimeClassName(This,className) \
        ( (This)->lpVtbl->GetRuntimeClassName(This,className) )

#define __x_Microsoft_CReactNative_CIJSValueWriter_GetTrustLevel(This,trustLevel) \
        ( (This)->lpVtbl->GetTrustLevel(This,trustLevel) )

#define __x_Microsoft_CReactNative_CIJSValueWriter_WriteNull(This) \
    ( (This)->lpVtbl->WriteNull(This) )

#define __x_Microsoft_CReactNative_CIJSValueWriter_WriteBoolean(This,value) \
    ( (This)->lpVtbl->WriteBoolean(This,value) )

#define __x_Microsoft_CReactNative_CIJSValueWriter_WriteInt64(This,value) \
    ( (This)->lpVtbl->WriteInt64(This,value) )

#define __x_Microsoft_CReactNative_CIJSValueWriter_WriteDouble(This,value) \
    ( (This)->lpVtbl->WriteDouble(This,value) )

#define __x_Microsoft_CReactNative_CIJSValueWriter_WriteString(This,value) \
    ( (This)->lpVtbl->WriteString(This,value) )

#define __x_Microsoft_CReactNative_CIJSValueWriter_WriteObjectBegin(This) \
    ( (This)->lpVtbl->WriteObjectBegin(This) )

#define __x_Microsoft_CReactNative_CIJSValueWriter_WritePropertyName(This,name) \
    ( (This)->lpVtbl->WritePropertyName(This,name) )

#define __x_Microsoft_CReactNative_CIJSValueWriter_WriteObjectEnd(This) \
    ( (This)->lpVtbl->WriteObjectEnd(This) )

#define __x_Microsoft_CReactNative_CIJSValueWriter_WriteArrayBegin(This) \
    ( (This)->lpVtbl->WriteArrayBegin(This) )

#define __x_Microsoft_CReactNative_CIJSValueWriter_WriteArrayEnd(This) \
    ( (This)->lpVtbl->WriteArrayEnd(This) )


#endif /* COBJMACROS */


EXTERN_C const IID IID___x_Microsoft_CReactNative_CIJSValueWriter;
#endif /* !defined(____x_Microsoft_CReactNative_CIJSValueWriter_INTERFACE_DEFINED__) */


/*
 *
 * Delegate Microsoft.ReactNative.JSValueArgWriter
 *
 * The IID for this interface was automatically generated by MIDLRT.
 *
 * Interface IID generation seed: Microsoft.ReactNative.JSValueArgWriter:HRESULT Invoke(Microsoft.ReactNative.IJSValueWriter*);
 *
 *
 */
#if !defined(____x_Microsoft_CReactNative_CIJSValueArgWriter_INTERFACE_DEFINED__)
#define ____x_Microsoft_CReactNative_CIJSValueArgWriter_INTERFACE_DEFINED__
/* [uuid("35984877-3082-53fc-aadc-a9a5e5518c16"), version, object] */
typedef struct __x_Microsoft_CReactNative_CIJSValueArgWriterVtbl
{
    BEGIN_INTERFACE
    HRESULT ( STDMETHODCALLTYPE *QueryInterface )(
    __RPC__in __x_Microsoft_CReactNative_CIJSValueArgWriter * This,
    /* [in] */ __RPC__in REFIID riid,
    /* [annotation][iid_is][out] */
    _COM_Outptr_  void **ppvObject);

ULONG ( STDMETHODCALLTYPE *AddRef )(
    __RPC__in __x_Microsoft_CReactNative_CIJSValueArgWriter * This);

ULONG ( STDMETHODCALLTYPE *Release )(
    __RPC__in __x_Microsoft_CReactNative_CIJSValueArgWriter * This);
HRESULT ( STDMETHODCALLTYPE *Invoke )(
        __x_Microsoft_CReactNative_CIJSValueArgWriter * This,
        /* [in] */__x_Microsoft_CReactNative_CIJSValueWriter * writer
        );
    END_INTERFACE
    
} __x_Microsoft_CReactNative_CIJSValueArgWriterVtbl;

interface __x_Microsoft_CReactNative_CIJSValueArgWriter
{
    CONST_VTBL struct __x_Microsoft_CReactNative_CIJSValueArgWriterVtbl *lpVtbl;
};

#ifdef COBJMACROS
#define __x_Microsoft_CReactNative_CIJSValueArgWriter_QueryInterface(This,riid,ppvObject) \
( (This)->lpVtbl->QueryInterface(This,riid,ppvObject) )

#define __x_Microsoft_CReactNative_CIJSValueArgWriter_AddRef(This) \
        ( (This)->lpVtbl->AddRef(This) )

#define __x_Microsoft_CReactNative_CIJSValueArgWriter_Release(This) \
        ( (This)->lpVtbl->Release(This) )

#define __x_Microsoft_CReactNative_CIJSValueArgWriter_Invoke(This,writer) \
    ( (This)->lpVtbl->Invoke(This,writer) )


#endif /* COBJMACROS */


EXTERN_C const IID IID___x_Microsoft_CReactNative_CIJSValueArgWriter;
#endif /* !defined(____x_Microsoft_CReactNative_CIJSValueArgWriter_INTERFACE_DEFINED__) */


#endif // defined(__cplusplus)
#pragma pop_macro("MIDL_CONST_ID")
#endif // __IJSValueWriter_h_p_h__

#endif // __IJSValueWriter_h_h__
