// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace Microsoft.ReactNative.Xaml
{
    [webhosthidden][default_interface] runtimeclass XamlApplication : Microsoft.UI.Xaml.Application,
      Microsoft.UI.Xaml.Markup.IXamlMetadataProvider
    {
        XamlApplication();

        static void EnsureCreated();

        static XamlApplication Current {
          get;
        };

        void AddMetadataProvider(Microsoft.UI.Xaml.Markup.IXamlMetadataProvider otherProvider);
    }
}
