trigger:
- test-net-asp

pool:
  name: GreenRNW

steps:
- pwsh: |
    Write-Warning 'Printing PATH'
    $env:PATH -split ';'
  displayName: Get ENV info

- checkout: self
  clean: false
  fetchDepth: 1
  continueOnError: false

- pwsh: |
    Write-Host "[$(Get-Command -ShowCommandInfo -Name git.exe)]"
    Write-Warning 'Printing PATH'
  displayName: Find Git

- task: DotNetCoreCLI@2
  displayName: Restore Packages for Test Website
  inputs:
    command: restore
    projects: vnext/TestServices/Microsoft.ReactNative.Test.Services.csproj

- task: DotNetCoreCLI@2
  displayName: Build Test Website
  inputs:
    command: build
    projects: vnext/TestServices/Microsoft.ReactNative.Test.Services.csproj

- task: DotNetCoreCLI@2
  displayName: Publish Test Website
  inputs:
    command: publish
    projects: vnext/TestServices/Microsoft.ReactNative.Test.Services.csproj
