# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- test-net-asp

pool:
  name: GreenRNW

steps:
- pwsh: |
    Write-Warning 'Printing PATH'
    $env:PATH -split ';'
  displayName: Get ENV info

- checkout: self
  clean: false
  fetchDepth: 1
  continueOnError: false

- pwsh: |
    Write-Host "[$(Get-Command -ShowCommandInfo -Name git.exe)]"
    Write-Warning 'Printing PATH'
  displayName: Find Git location

- task: DotNetCoreCLI@2
  enabled: true
  inputs:
    command: restore
    projects: vnext/TestServices/Microsoft.ReactNative.Test.Services.csproj
