trigger:
- test-net-asp

pool:
  name: GreenRNW

variables:
  system.debug: true

steps:
- pwsh: |
    Write-Warning 'Printing PATH'
    $env:PATH -split ';'
  displayName: Get ENV info

- checkout: self
  clean: false
  fetchDepth: 1
  continueOnError: false

- pwsh: |
    Write-Host "[$(Get-Command -ShowCommandInfo -Name git.exe)]"
    Write-Warning 'Printing PATH'
  displayName: Find Git

- task: DotNetCoreCLI@2
  displayName: Restore Packages for Test Website
  inputs:
    command: restore
    projects: vnext/TestServices/Microsoft.ReactNative.Test.Services.csproj

- task: DotNetCoreCLI@2
  displayName: Build Test Website
  inputs:
    command: build
    projects: vnext/TestServices/Microsoft.ReactNative.Test.Services.csproj

- task: DotNetCoreCLI@2
  displayName: Publish Test Website
  inputs:
    command: publish
    publishWebProjects: false
    zipAfterPublish: false
    projects: vnext/TestServices/Microsoft.ReactNative.Test.Services.csproj

- pwsh: |
    # Expected output: something like x64\Debug\Microsoft.ReactNative.Test.Services\Publish\
    Write-Warning 'Showing published artifacts'
    Get-ChildItem -Name -Recurse -File vnext/target/
  displayName: Show published content

- pwsh: |
    Install-WindowsFeature -Name WebServer
  displayName: Install IIS
