# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- test-net-asp

pool:
  name: GreenRNW

steps:
- pwsh: |
    Write-Warning 'Printing PATH:'
    $env:PATH -split ';'
  displayName: Get ENV info

- checkout: self
  clean: false
  fetchDepth: 1
  continueOnError: true

  # - checkout: string # Required as first property. Configures checkout for the specified repository.
  #   clean: string # If true, run git clean -ffdx followed by git reset --hard HEAD before fetching.
  #   fetchDepth: string # Depth of Git graph to fetch.
  #   fetchTags: string # Set to 'true' to sync tags when fetching the repo, or 'false' to not sync tags. See remarks for the default behavior.
  #   lfs: string # Set to 'true' to download Git-LFS files. Default is not to download them.
  #   persistCredentials: string # Set to 'true' to leave the OAuth token in the Git config after the initial fetch. The default is not to leave it.
  #   submodules: string # Set to 'true' for a single level of submodules or 'recursive' to get submodules of submodules. Default is not to fetch submodules.
  #   path: string # Where to put the repository. The root directory is $(Pipeline.Workspace).
  #   condition: string # Evaluate this condition expression to determine whether to run this task.
  #   continueOnError: boolean # Continue running even on failure?
  #   displayName: string # Human-readable name for the task.
  #   target: string | target # Environment in which to run this task.
  #   enabled: boolean # Run this task when the job runs?
  #   env: # Variables to map into the process's environment.
  #     string: string # Name/value pairs
  #   name: string # ID of the step.
  #   timeoutInMinutes: string # Time to wait for this task to complete before the server kills it.
  #   retryCountOnTaskFailure: string # Number of retries if the task fails.

- pwsh: |
    Write-Host "[$(Get-Command git.exe)]"
  displayName: Find Git location

- task: DotNetCoreCLI@2
  enabled: false
  inputs:
    command: restore
    projects: vnext/TestServices/Microsoft.ReactNative.Test.Services.csproj
