name: 0.0.$(Date:yyMM.d)$(Rev:rrr)

parameters:
- name: stopOnNoCI
  displayName: Stop if latest commit is ***NO_CI***
  type: boolean
  default: true
- name: AgentPool
  type: object
  default:
    Medium:
      name: rnw-pool-4-microsoft
      demands: ImageOverride -equals rnw-img-node16
    Large:
      name: rnw-pool-8-microsoft
      demands: ImageOverride -equals rnw-img-node16

variables:
  - template: variables/windows.yml
  - group: RNW Secrets
  - name: NugetSecurityAnalysisWarningLevel
    value: 'warn'

trigger: none
pr: none

jobs:
  - job: RnwUniversalCompliance
    displayName: RNW Universal Compliance
    pool: ${{ parameters.AgentPool.Large }}

    steps:
      - template: templates/prepare-js-env.yml

      - powershell: |
          Write-Error "Stopping because commit message contains ***NO_CI***."
        displayName: Stop pipeline if latest commit message contains ***NO_CI***
        condition: and(${{ parameters.stopOnNoCI }}, contains(variables['Build.SourceVersionMessage'], '***NO_CI***'))

      - template: templates/set-version-vars.yml
        parameters:
          buildEnvironment: Continuous

      - template: templates/publish-version-vars.yml

      - template: templates/prepare-build-env.yml
        parameters:
          platform: x64
          configuration: Release
          buildEnvironment: Continuous

      - template: templates/apply-published-version-vars.yml

      # Pre-build compliance tasks

      # - powershell: |
      #     $customProps = "<?xml version=`"1.0`" encoding=`"utf-8`"?>
      #     <Project ToolsVersion=`"4.0`" xmlns=`"http://schemas.microsoft.com/developer/msbuild/2003`">
      #       <!-- This file is read by XES, which we use in our Release builds. -->
      #       <PropertyGroup Label=`"Version`">
      #         <XesUseOneStoreVersioning>true</XesUseOneStoreVersioning>
      #         <XesBaseYearForStoreVersion>2022</XesBaseYearForStoreVersion>
      #         <VersionMajor>$env:RNW_PKG_VERSION_MAJOR</VersionMajor>
      #         <VersionMinor>$env:RNW_PKG_VERSION_MINOR</VersionMinor>
      #         <VersionInfoProductName>React-Native-Windows</VersionInfoProductName>
      #       </PropertyGroup>
      #     </Project>"
      #     $customPropsFile = Join-Path (Get-Location) "custom.props"
      #     Write-Host "Outputting to $customPropsFile"
      #     Write-Host $customProps
      #     Set-Content $customPropsFile -Value $customProps
      #   displayName: Create custom.props file
      #   workingDirectory: $(Build.SourcesDirectory)

      # - task: PkgESSetupBuild@12
      #   displayName: Package ES - Setup Build
      #   inputs:
      #     disableOutputRedirect: true

      # Build

      - template: templates/msbuild-sln.yml
        parameters:
          solutionDir: vnext
          solutionName: Microsoft.ReactNative.sln
          buildPlatform: x64
          buildConfiguration: Release

      # Post-build compliance tasks

      # https://www.1eswiki.com/index.php?title=PoliCheck_Build_Task
      # Scans the text of source code, comments, and content for terminology that could be sensitive for legal, cultural, or geopolitical reasons.
      - task: securedevelopmentteam.vss-secure-development-tools.build-task-policheck.PoliCheck@2
        displayName: 'Run PoliCheck'
        inputs:
          targetType: F
          targetArgument: $(Build.SourcesDirectory)
          result: PoliCheck.xml
          optionsFC: 1
          optionsXS: 1
          # optionsUEPath: $(Build.SourcesDirectory)\PolicheckExclusions.xml
          optionsHMENABLE: 0
        continueOnError: true
