name: RNW CI $(Date:yyyyMMdd).$(Rev:r)

trigger: none # will disable CI builds entirely
pr: none

variables:
  - template: variables/msbuild.yml
  - group: RNW Secrets
  - group: platform-override-zero-permission-token

stages:
  - stage: Setup
    jobs:
      - job: Setup
        variables:
          - template: variables/vs2019.yml
        pool:
          vmImage: windows-2019
        steps:
          - template: templates/configure-git.yml

          - template: templates/yarn-install.yml

          - script: npx --no-install beachball bump --branch origin/$(Build.SourceBranchName) --yes
            displayName: beachball bump

          - template: templates/set-version-vars.yml
            parameters:
              buildEnvironment: Continuous

          - template: templates/publish-version-vars.yml

  - template: stages.yml
    parameters:
      buildEnvironment: Continuous
