name: RNW CI $(Date:yyyyMMdd).$(Rev:r)

trigger: none # will disable CI builds entirely
pr: none

variables:
  - group: RNW Secrets
  - group: platform-override-zero-permission-token

stages:
  - stage: Setup
    jobs:
      - template: jobs/setup.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}

  - template: stages.yml
    parameters:
      buildEnvironment: Continuous
