name: $(Date:yyyyMMdd).$(Rev:r)

trigger: none
pr: none

jobs:
  - job: PrepareRelease
    displayName: Prepare Release Bot
    pool:
      vmImage: windows-latest
    timeoutInMinutes: 30

    steps:
      - template: templates/checkout-full.yml
        parameters:
          persistCredentials: true

      - script: |
          git config user.name "React-Native-Windows Bot"
          git config user.email "53619745+rnbot@users.noreply.github.com"
        displayName: Configure Git Identity

      - template: templates/prepare-js-env.yml
        parameters:
          agentImage: HostedImage

      - script: npx prepare-release --branch $(Build.SourceBranchName) --no-color
        displayName: Prepare Release
        env:
          GH_TOKEN: $(githubAuthToken)
