# Experimental pipeline to test GitHub access via stock 1ES template
# Mirrors the publish pipeline structure but performs only git operations
# using the OAuth creds supplied by the GitHub service connection (no PATs).

name: 0.0.$(Date:yyMM.d)$(Rev:rrr)

trigger: none
pr: none

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
    customBuildTags: []
    sdl:
      credscan:
        enabled: false
      binskim:
        enabled: false
      spotBugs:
        enabled: false
    stages:
      - stage: FakePublish
        displayName: GitHub OAuth Capability Probe
        jobs:
          - job: FakeGitProbe
            displayName: Test branch push without PAT
            pool:
              name: Azure-Pipelines-1ESPT-ExDShared
            steps:
              - checkout: self
                persistCredentials: true   # reuse the GitHub connection OAuth token

              - script: |
                  echo Repository: $(Build.Repository.Name)
                  echo Source branch: $(Build.SourceBranch)
                  git --version
                displayName: Show repo info

              - script: git status -sb
                displayName: Show working tree status

              - script: |
                  set -euo pipefail
                  BRANCH="user/vmorozov/probe-$(Build.BuildId)"
                  echo "Creating branch $BRANCH"
                  git checkout -b "$BRANCH"
                  echo "release probe $(Build.BuildId)" > release-probe.txt
                  git add release-probe.txt
                  git status -sb
                  git commit -m "chore: release probe (***No CI***)"
                  git push origin HEAD
                  echo "Branch $BRANCH pushed."
                displayName: Create, commit, and push branch

              - script: git ls-remote --heads origin user/vmorozov/probe-$(Build.BuildId)
                displayName: Confirm remote branch
