name: RNW NuGet Release $(Date:yyyyMMdd).$(Rev:r)

trigger: none

resources:
  pipelines:
  - pipeline: 'Publish'
    project: 'ReactNative'
    source: 'Publish'
    trigger:
      branches:
        include:
        - -1espublish
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-latest
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling-Release
    stages:
    - stage: Release
      displayName: Publish artifacts
      jobs:
      - job: PushNpm
        displayName: npmjs.com - Publish npm packages
        variables:
        - group: RNW Secrets
        timeoutInMinutes: 0
        templateContext:
          inputs:
          - input: pipelineArtifact
            pipeline: 'Publish'
            artifactName: 'NpmPackedTarballs'
            targetPath: '$(Pipeline.Workspace)/published-packages'
          - input: pipelineArtifact
            pipeline: 'Publish'
            artifactName: 'VersionEnvVars'
            targetPath: '$(Pipeline.Workspace)/VersionEnvVars'
        steps:
        - checkout: self
          clean: false
        - task: CmdLine@2
          displayName: Apply version variables
          inputs:
            script: node $(Pipeline.Workspace)/VersionEnvVars/versionEnvVars.js
        - script: dir /s "$(Pipeline.Workspace)\published-packages"
          displayName: Show npm packages before cleanup
        - script: node .ado/scripts/npmPack.js --no-pack --check-npm --no-color "$(Pipeline.Workspace)\published-packages"
          displayName: Remove already published packages
        - script: dir /s "$(Pipeline.Workspace)\published-packages"
          displayName: Show npm packages after cleanup
        - powershell: |
            $tgzFiles = Get-ChildItem -Path "$(Pipeline.Workspace)\published-packages" -Filter "*.tgz" -Recurse
            $tgzCount = $tgzFiles.Count
            Write-Host "Found $tgzCount .tgz files"
            Write-Host "##vso[task.setvariable variable=HasPackagesToPublish]$($tgzCount -gt 0)"
          displayName: Check if there are packages to publish
        - task: 'SFP.release-tasks.custom-build-release-task.EsrpRelease@10'
          displayName: 'ESRP Release to npmjs.com'
          condition: and(succeeded(), ne(variables['NpmDistTag'], ''), eq(variables['HasPackagesToPublish'], 'true'))
          inputs:
            connectedservicename: 'ESRP-CodeSigning-OGX-JSHost-RNW'
            usemanagedidentity: false
            keyvaultname: 'OGX-JSHost-KV'
            authcertname: 'OGX-JSHost-Auth4'
            signcertname: 'OGX-JSHost-Sign3'
            clientid: '0a35e01f-eadf-420a-a2bf-def002ba898d'
            domaintenantid: 'cdc5aeea-15c5-4db6-b079-fcadd2505dc2'
            contenttype: npm
            folderlocation: '$(Pipeline.Workspace)\published-packages'
            productstate: '$(NpmDistTag)'
            owners: 'vmorozov@microsoft.com'
            approvers: 'khosany@microsoft.com'

      - job: PushPrivateAdo
        displayName: ADO - react-native
        timeoutInMinutes: 0
        templateContext:
          inputs:
          - input: pipelineArtifact
            pipeline: 'Publish'
            artifactName: 'ReactWindows-final-nuget'
            targetPath: '$(Pipeline.Workspace)/ReactWindows-final-nuget'
        steps:
        - checkout: none
        - task: NuGetToolInstaller@1
          displayName: 'Use NuGet '
        - task: NuGetAuthenticate@1
          displayName: NuGet Authenticate
          inputs:
            nuGetServiceConnections: ms/react-native ADO Feed
        - task: CmdLine@2
          displayName: NuGet push (react-native)
          inputs:
            script: nuget.exe push *.nupkg -ApiKey AzureArtifacts -Source https://pkgs.dev.azure.com/ms/_packaging/react-native/nuget/v3/index.json -NonInteractive -Verbosity Detailed -SkipDuplicate -NoSymbols
            workingDirectory: $(Pipeline.Workspace)/ReactWindows-final-nuget

      - job: PushPublicAdo
        displayName: ADO - react-native-public
        timeoutInMinutes: 0
        templateContext:
          inputs:
          - input: pipelineArtifact
            pipeline: 'Publish'
            artifactName: 'ReactWindows-final-nuget'
            targetPath: '$(Pipeline.Workspace)/ReactWindows-final-nuget'
        steps:
        - checkout: none
        - task: NuGetToolInstaller@1
          displayName: 'Use NuGet '
        - task: NuGetAuthenticate@1
          displayName: NuGet Authenticate
          inputs:
            nuGetServiceConnections: ms/react-native-public ADO Feed
        - task: CmdLine@2
          displayName: NuGet push (react-native-public)
          inputs:
            script: nuget.exe push *.nupkg -ApiKey AzureArtifacts -Source https://pkgs.dev.azure.com/ms/react-native/_packaging/react-native-public/nuget/v3/index.json -NonInteractive -Verbosity Detailed -SkipDuplicate -NoSymbols
            workingDirectory: $(Pipeline.Workspace)/ReactWindows-final-nuget

      - job: PushNuGetOrg
        displayName: nuget.org - Push nuget packages
        variables:
        - group: RNW Secrets
        timeoutInMinutes: 0
        templateContext:
          inputs:
          - input: pipelineArtifact
            pipeline: 'Publish'
            artifactName: 'ReactWindows-final-nuget'
            targetPath: '$(Pipeline.Workspace)/ReactWindows-final-nuget'
        steps:
        - checkout: none
        - task: NuGetToolInstaller@1
          displayName: 'Use NuGet '
        - task: CmdLine@2
          displayName: NuGet SetApiKey (nuget.org)
          inputs:
            script: nuget.exe SetApiKey $(nugetorg-apiKey-push)
            workingDirectory: $(Pipeline.Workspace)/ReactWindows-final-nuget
        - task: PowerShell@2
          displayName: NuGet push (nuget.org)
          inputs:
            targetType: inline
            errorActionPreference: silentlyContinue
            script: |
              if (Get-ChildItem -Path .\ -Filter '*0.0.0-canary*' -ErrorAction SilentlyContinue) { Write-Output "Canary builds found, exiting."; return 0; }
              nuget.exe push .\Microsoft.ReactNative.*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -NoSymbol -NonInteractive -Verbosity Detailed
            workingDirectory: $(Pipeline.Workspace)/ReactWindows-final-nuget
