parameters:
  - name: buildEnvironment
    type: string
    default: PullRequest
    values:
      - PullRequest
      - SecurePullRequest
      - Continuous
  - name: AgentPool
    type: object

stages:
  - stage: Setup
    jobs:
      - template: jobs/setup.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}

  - stage: Build
    displayName: Build 🔨
    dependsOn: Setup
    jobs:
      - template: jobs/universal.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}

      - template: jobs/desktop.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}

      - template: jobs/nuget-desktop.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}
      
      - template: jobs/cli-init-windows.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}
          buildNuGetOnly: true

      # Attack Surface Analyzer for SDL compliance
      - template: jobs/attack-surface-analyzer.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}
          complianceWarnOnly: true

  - stage: IntegrationTests
    displayName: Tests 🧪
    dependsOn: Setup
    jobs:
      - template: jobs/linting.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}

      - template: jobs/node-tests.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}

      - template: jobs/playground.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}

      - template: jobs/e2e-test.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}

  - stage: CLI
    displayName: Cli 🖥
    dependsOn: Setup
    jobs:
      - template: jobs/cli-init-windows.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}
          buildNuGetOnly: false

      - template: jobs/macos-tests.yml
