parameters:
  - name: buildEnvironment
    type: string
    default: PullRequest
    values:
      - PullRequest
      - SecurePullRequest
      - Continuous
  - name: AgentPool
    type: object

stages:
  - stage: Setup
    jobs:
      - template: jobs/setup.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}

  - stage: IntegrationTests
    displayName: Tests 🧪
    dependsOn: Setup
    jobs:
      - template: jobs/e2e-test.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}
