parameters:
  - name: buildEnvironment
    type: string
    default: PullRequest
    values:
      - PullRequest
      - Continuous
  - name: AgentPool
    type: object

stages:
  - stage: Setup
    jobs:
      - template: jobs/setup.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}

  - stage: Build
    displayName: Build 🔨
    dependsOn: Setup
    condition: and (succeeded(), ne( dependencies.Setup.outputs['checkPayload.shouldSkipPRBuild'], 'True' ))
    jobs:
      - template: jobs/universal.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}

      - template: jobs/desktop.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}

      - template: jobs/nuget-desktop.yml
        parameters:
          AgentPool: ${{ parameters.AgentPool }}

      - template: jobs/project-reunion.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}

      # NuGet using tests rely on "UniversalBuild" which is done in the build stage
      - template: jobs/cli-init.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}
          buildNuGetOnly: true

  - stage: IntegrationTests
    displayName: Tests 🧪
    dependsOn: Setup
    condition: and (succeeded(), ne( dependencies.Setup.outputs['checkPayload.shouldSkipPRBuild'], 'True' ))
    jobs:
      - template: jobs/jschecks.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}

      - template: jobs/node-compat.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}

      - template: jobs/macos-tests.yml

      - template: jobs/playground.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}

      - template: jobs/sample-apps.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}

      - template: jobs/e2e-test.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}

      - template: jobs/integration-test.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}

  - stage: CLI
    displayName: Cli 🖥
    dependsOn: Setup
    condition: and (succeeded(), ne( dependencies.Setup.outputs['checkPayload.shouldSkipPRBuild'], 'True' ))
    jobs:
      - template: jobs/cli-init.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}
          buildNuGetOnly: false
