parameters:
  - name: buildEnvironment
    type: string
    default: PullRequest
    values:
      - PullRequest
      - SecurePullRequest
      - Continuous
  - name: AgentPool
    type: object

stages:
  - stage: Setup
    jobs:
      - template: jobs/setup.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}

  - stage: Build
    displayName: Build 🔨
    dependsOn: Setup
    jobs:
      - template: jobs/universal.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}

      - template: jobs/desktop.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}

      - template: jobs/nuget-desktop.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}

      # Disabling CLI Stage as branch is Unsupported, see https://microsoft.github.io/react-native-windows/support
      # - template: jobs/cli-init-windows.yml
      #   parameters:
      #     buildEnvironment: ${{ parameters.buildEnvironment }}
      #     AgentPool: ${{ parameters.AgentPool }}
      #     buildNuGetOnly: true

      # # NuGet using tests rely on "UniversalBuild" which is done in the build stage
      # - template: jobs/cli-init.yml
      #   parameters:
      #     buildEnvironment: ${{ parameters.buildEnvironment }}
      #     AgentPool: ${{ parameters.AgentPool }}
      #     buildNuGetOnly: true

  - stage: IntegrationTests
    displayName: Tests 🧪
    dependsOn: Setup
    jobs:
      - template: jobs/linting.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}

      # - template: jobs/node-tests.yml
      #   parameters:
      #    buildEnvironment: ${{ parameters.buildEnvironment }}
      #    AgentPool: ${{ parameters.AgentPool }}

      - template: jobs/macos-tests.yml

      - template: jobs/playground.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}

      - template: jobs/sample-apps.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}

      - template: jobs/e2e-test.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}

      - template: jobs/integration-test.yml
        parameters:
          buildEnvironment: ${{ parameters.buildEnvironment }}
          AgentPool: ${{ parameters.AgentPool }}

  # Disabling CLI Stage as branch is Unsupported, see https://microsoft.github.io/react-native-windows/support
  # - stage: CLI
  #   displayName: Cli 🖥
  #   dependsOn: Setup
  #   jobs:
  #     - template: jobs/cli-init.yml
  #       parameters:
  #         buildEnvironment: ${{ parameters.buildEnvironment }}
  #         AgentPool: ${{ parameters.AgentPool }}
  #         buildNuGetOnly: false
      
  #     - template: jobs/cli-init-windows.yml
  #       parameters:
  #         buildEnvironment: ${{ parameters.buildEnvironment }}
  #         AgentPool: ${{ parameters.AgentPool }}
