name: $(Date:yyyyMMdd).$(Rev:r)

trigger: none # will disable CI builds entirely

pr:
  - main
  - master
  - "*-stable"

variables:
  - group: platform-override-zero-permission-token

stages:     
  - template: stages.yml
    parameters:
      buildEnvironment: PullRequest
