name: $(Date:yyyyMMdd).$(Rev:r)

trigger: none # will disable CI builds entirely

pr:
  - main
  - master
  - "*-stable"

variables:
  - template: variables/msbuild.yml
  - group: platform-override-zero-permission-token

stages:
  - stage: Setup
    jobs:
      - job: Setup
        variables:
          - template: variables/vs2019.yml
        pool:
          vmImage: windows-2019
        steps:
          - task: powershell@2
            name: checkPayload
            displayName: "Check if build is required for this PR"
            inputs:
              targetType: filePath
              filePath: .ado/scripts/shouldSkipPRBuild.ps1

          - script: npx midgard-yarn-strict@1.2.4 --scope react-native-windows-ado --frozen-lockfile --network-concurrency 40 --cache-folder \.yarnCache
            displayName: Minimal yarn install

          - template: templates/compute-beachball-branch-name.yml

          - script: npx --no-install beachball check --branch origin/$(BeachBallBranchName) --changehint "##vso[task.logissue type=error]Run `yarn change` from root of repo to generate a change file."
            displayName: Check for change files

          - script: npx --no-install beachball bump --branch origin/$(BeachBallBranchName) --yes
            displayName: beachball bump

          - template: templates/set-version-vars.yml
            parameters:
              buildEnvironment: Continuous

          - template: templates/publish-version-vars.yml

  - template: stages.yml
    parameters:
      buildEnvironment: PullRequest
