# This file defines the Windows Visual Studio PR build steps used during the CI loop
name: $(Date:yyyyMMdd).$(Rev:.r)

trigger: none # will disable CI builds entirely

pr:
  - master
  - 0.60-stable

variables:
  - template: variables/msbuild.yml
  - template: variables/vs2019.yml

jobs:
  - job: Setup
    steps:
      - task: powershell@2
        name: checkPayload
        displayName: "Check if build is required for this PR"
        inputs:
          targetType: filePath
          filePath: .ado/shouldSkipPRBuild.ps1

  - job: RNWUniversalPR
    displayName: Universal PR
    dependsOn: Setup
    condition: ne( dependencies.Setup.outputs['checkPayload.shouldSkipPRBuild'], 'True' )
    strategy:
      matrix:
        #X64Debug:
        #  BuildConfiguration: Debug
        #  BuildPlatform: x64
        #  applyRnPatches: true
        #  LayoutHeaders: true
        #X64Release:
        #  BuildConfiguration: Release
        #  BuildPlatform: x64
        #  applyRnPatches: true
        #ArmDebug:
        #  BuildConfiguration: Debug
        #  BuildPlatform: arm
        #  applyRnPatches: true
        #X86Debug:
        #  BuildConfiguration: Debug
        #  BuildPlatform: x86
        #  applyRnPatches: true
        X86Release:
          BuildConfiguration: Release
          BuildPlatform: x86
          applyRnPatches: true
        # Temporarily omitting to save disk space.
        # ArmRelease:
        #   BuildConfiguration: Release
        #   BuildPlatform: arm
        #   applyRnPatches: true
        Arm64Release:
          BuildConfiguration: Release
          BuildPlatform: arm64
          applyRnPatches: true
        UnpatchedRNX86Debug:
          BuildConfiguration: Debug
          BuildPlatform: x86
          applyRnPatches: false
    pool:
      vmImage: $(VmImage)
    timeoutInMinutes: 60
    cancelTimeoutInMinutes: 5

    steps:
      - checkout: self
        clean: false
        submodules: false

      - template: templates/build-rnw.yml
        parameters:
          applyRnPatches: $(applyRnPatches)
          yarnBuildCmd: build
          project: vnext/ReactWindows-Universal.sln
          vsComponents: ''

      - template: templates/publish-build-artifacts-for-nuget.yml
        parameters:
          artifactName: ReactWindows
          layoutHeaders: eq('true', variables['LayoutHeaders'])
          contents: |
            ReactUWP\**

  - job: RNWUniversalOtherProjectsPR
    displayName: Universal Other Projects PR
    dependsOn: Setup
    condition: ne( dependencies.Setup.outputs['checkPayload.shouldSkipPRBuild'], 'True' )
    strategy:
      matrix:
        X86Debug:
          BuildConfiguration: Debug
          BuildPlatform: x86
          applyRnPatches: true
        X64Release:
          BuildConfiguration: Release
          BuildPlatform: x64
          applyRnPatches: true
    pool:
      vmImage: $(VmImage)
    timeoutInMinutes: 60
    cancelTimeoutInMinutes: 5

    steps:
      - checkout: self
        clean: false
        submodules: false
        
      - template: templates/prepare-env.yml
        parameters:
          applyRnPatches: $(applyRnPatches)
          vsComponents: ''
          yarnBuildCmd: build

      - task: NuGetCommand@2
        displayName: NuGet restore - Playground
        inputs:
          command: restore
          restoreSolution: packages/playground/windows/Playground.sln
          verbosityRestore: Detailed # Options: quiet, normal, detailed

      - task: MSBuild@1
        displayName: MSBuild - Playground
        inputs:
          solution: packages/playground/windows/Playground.sln
          msbuildVersion: $(MSBuildVersion) # Optional. Options: latest, 16.0, 15.0, 14.0, 12.0, 4.0
          msbuildArchitecture: $(MSBuildArchitecture) # Optional. Options: x86, x64
          platform: $(BuildPlatform) # Optional
          configuration: $(BuildConfiguration) # Optional
          msbuildArguments:
            /p:PreferredToolArchitecture=$(MSBuildPreferredToolArchitecture)
            /p:PlatformToolset=$(MSBuildPlatformToolset)
            /p:BaseIntDir=$(BaseIntDir)
          clean: true # Optional
        condition: and(succeeded(), eq(variables['applyRnPatches'], 'true'))

      - task: CmdLine@2
        displayName: Create Playground bundle
        inputs:
          script: node node_modules/react-native/local-cli/cli.js bundle --entry-file Samples\index.tsx --bundle-output Playground.bundle
          workingDirectory: packages\playground

      - task: NuGetCommand@2
        displayName: NuGet restore - SampleApps
        inputs:
          command: restore
          restoreSolution: packages/microsoft-reactnative-sampleapps/windows/SampleApps.sln
          verbosityRestore: Detailed # Options: quiet, normal, detailed
        condition: and(succeeded(), eq(variables['applyRnPatches'], 'true'))

      - task: MSBuild@1
        displayName: MSBuild - SampleApps
        inputs:
          solution: packages/microsoft-reactnative-sampleapps/windows/SampleApps.sln
          msbuildVersion: $(MSBuildVersion) # Optional. Options: latest, 16.0, 15.0, 14.0, 12.0, 4.0
          msbuildArchitecture: $(MSBuildArchitecture) # Optional. Options: x86, x64
          platform: $(BuildPlatform) # Optional
          configuration: $(BuildConfiguration) # Optional
          msbuildArguments:
            /p:PreferredToolArchitecture=$(MSBuildPreferredToolArchitecture)
            /p:PlatformToolset=$(MSBuildPlatformToolset)
            /p:BaseIntDir=$(BaseIntDir)
          clean: true # Optional
        condition: and(succeeded(), eq(variables['applyRnPatches'], 'true'), ne(variables['BuildPlatform'], 'x86'), false) # Disabled. issue #3670  Unable to resolve module `warnOnce`

      # Possible related to https://social.msdn.microsoft.com/Forums/vstudio/en-US/23c8df57-9c50-476c-9f56-1fe058e75a9d/uwp-app-builds-on-local-machine-fails-on-build-agent-systemprivatecorelib-not-found
      # use X86 msbuild to avoid ##[error]...Microsoft.AppXPackage.Targets(1248,5): Error MSB3816: Loading assembly "\runtime.win7-x86.microsoft.netcore.runtime.coreclr\1.0.2\runtimes\win7-x86\lib\netstandard1.0\mscorlib.dll" failed. 
      # System.ArgumentException: A BadImageFormatException has been thrown while parsing the signature.
      # This is likely due to lack of a generic context. Ensure genericTypeArguments and genericMethodArguments are provided and contain enough context.
      - task: MSBuild@1
        displayName: MSBuild - SampleApps
        inputs:
          solution: packages/microsoft-reactnative-sampleapps/windows/SampleApps.sln
          msbuildVersion: $(MSBuildVersion) # Optional. Options: latest, 16.0, 15.0, 14.0, 12.0, 4.0
          msbuildArchitecture: x86 # Optional. Options: x86, x64
          platform: $(BuildPlatform) # Optional
          configuration: $(BuildConfiguration) # Optional
          msbuildArguments:
            /p:PreferredToolArchitecture=$(MSBuildPreferredToolArchitecture)
            /p:PlatformToolset=$(MSBuildPlatformToolset)
            /p:BaseIntDir=$(BaseIntDir)
          clean: true # Optional
        condition: and(succeeded(), eq(variables['applyRnPatches'], 'true'), eq(variables['BuildPlatform'], 'x86'), false) # Disabled. [error]vnext\Microsoft.ReactNative.SharedManaged\JSValue.cs(100,36): Error CS8107: Feature 'readonly references' is not available in C# 7.0. Please use language version 7.2 or greater.

      - task: CmdLine@2
        displayName: Create SampleApp bundle
        inputs:
          script: node node_modules/react-native/local-cli/cli.js bundle --entry-file index.windows.js --bundle-output SampleApp.bundle
          workingDirectory: packages\microsoft-reactnative-sampleapps
        condition: and(succeeded(), eq(variables['applyRnPatches'], 'true'))

      - task: CmdLine@2
        displayName: Create RNTester bundle
        inputs:
          script: node ../node_modules/react-native/local-cli/cli.js bundle --entry-file .\RNTester.js --bundle-output RNTester.windows.bundle --platform windows
          workingDirectory: vnext
        condition: and(succeeded(), eq(variables['applyRnPatches'], 'true'))


  - job: RNWDesktopPR
    displayName: Desktop PR
    dependsOn: Setup
    condition: ne( dependencies.Setup.outputs['checkPayload.shouldSkipPRBuild'], 'True' )
    strategy:
      matrix:
        X64Debug:
          BuildConfiguration: Debug
          BuildPlatform: x64
        X86Debug:
          BuildConfiguration: Debug
          BuildPlatform: x86
        X64Release:
          BuildConfiguration: Release
          BuildPlatform: x64
        X86Release:
          BuildConfiguration: Release
          BuildPlatform: x86

    pool:
      vmImage: $(VmImage)
    timeoutInMinutes: 60 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them

    variables:
      Desktop.IntegrationTests.Filter: (FullyQualifiedName!~WebSocketJSExecutorIntegrationTest)&(FullyQualifiedName!~WebSocket)

    steps:
      - checkout: self
        clean: false
        submodules: false

      - task: VisualStudioTestPlatformInstaller@1
        inputs:
          testPlatformVersion: 16.3.0

      - template: templates/build-rnw.yml
        parameters:
          yarnBuildCmd: build
          project: vnext/ReactWindows-Desktop.sln
          msbuildArguments:
            /p:RNW_PKG_VERSION_STR="Private Build"
            /p:RNW_PKG_VERSION="1000,0,0,0"

      - task: CmdLine@2
        displayName: Build react-native-win32 RNTester bundle
        inputs:
          script: yarn bundle
          workingDirectory: packages/react-native-win32
        condition: and(succeeded(), eq(variables['BuildConfiguration'], 'Debug'), eq(variables['BuildPlatform'], 'x64'))

      - task: VSTest@2
        displayName: Run Desktop Unit Tests
        timeoutInMinutes: 5 # Set smaller timeout , due to hangs
        inputs:
          testSelector: testAssemblies
          testAssemblyVer2: |
            React.Windows.Desktop.UnitTests/React.Windows.Desktop.UnitTests.dll
            JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.exe
          pathtoCustomTestAdapters: $(GoogleTestAdapterPath)
          searchFolder: $(Build.SourcesDirectory)/vnext/target/$(BuildPlatform)/$(BuildConfiguration)
          runTestsInIsolation: true
          platform: $(BuildPlatform)
          configuration: $(BuildConfiguration)
          publishRunAttachments: true
          collectDumpOn: onAbortOnly
          vsTestVersion: toolsInstaller

      - template: templates/stop-packagers.yml

      - task: PowerShell@2
        displayName: Set up test servers
        inputs:
          targetType: filePath # filePath | inline
          filePath: $(Build.SourcesDirectory)\vnext\Scripts\Tfs\Start-TestServers.ps1
          arguments: -SourcesDirectory $(Build.SourcesDirectory)\vnext -Preload -SleepSeconds 120

      - task: VSTest@2
        displayName: Run Desktop Integration Tests
        inputs:
          testSelector: testAssemblies
          testAssemblyVer2: React.Windows.Desktop.IntegrationTests\React.Windows.Desktop.IntegrationTests.dll
          searchFolder: $(Build.SourcesDirectory)\vnext\target\$(BuildPlatform)\$(BuildConfiguration)
          testFiltercriteria: $(Desktop.IntegrationTests.Filter)
          runTestsInIsolation: true
          platform: $(BuildPlatform)
          configuration: $(BuildConfiguration)
          publishRunAttachments: true
          collectDumpOn: onAbortOnly
          vsTestVersion: toolsInstaller
          otherConsoleOptions: '/blame -- RunConfiguration.TestSessionTimeout=300000'
        condition: and(succeeded(), ne(variables['BuildConfiguration'], 'Debug'))

      - task: VSTest@2
        displayName: List Desktop Integration Tests
        inputs:
          testSelector: testAssemblies
          testAssemblyVer2: React.Windows.Desktop.IntegrationTests\React.Windows.Desktop.IntegrationTests.dll
          searchFolder: $(Build.SourcesDirectory)\vnext\target\$(BuildPlatform)\$(BuildConfiguration)
          testFiltercriteria: $(Desktop.IntegrationTests.Filter)
          runTestsInIsolation: false
          platform: $(BuildPlatform)
          configuration: $(BuildConfiguration)
          publishRunAttachments: false
          collectDumpOn: onAbortOnly
          vsTestVersion: toolsInstaller
          otherConsoleOptions: '/ListTests'
        condition: failed()

      - task: VSTest@2
        displayName: Re-Run Desktop Integration Tests
        inputs:
          testSelector: testAssemblies
          testAssemblyVer2: React.Windows.Desktop.IntegrationTests\React.Windows.Desktop.IntegrationTests.dll
          searchFolder: $(Build.SourcesDirectory)\vnext\target\$(BuildPlatform)\$(BuildConfiguration)
          testFiltercriteria: $(Desktop.IntegrationTests.Filter)
          runTestsInIsolation: true
          platform: $(BuildPlatform)
          configuration: $(BuildConfiguration)
          publishRunAttachments: true
          collectDumpOn: onAbortOnly
          vsTestVersion: toolsInstaller
          otherConsoleOptions: '/blame -- RunConfiguration.TestSessionTimeout=300000'
        condition: failed()

      - task: PowerShell@2
        displayName: Check the metro bundle server
        inputs:
          targetType: 'inline'
          script: Invoke-WebRequest -Uri "http://localhost:8081/IntegrationTests/IntegrationTestsApp.bundle?platform=windesktop&dev=true"
        condition: failed()

      - template: templates/stop-packagers.yml

      - template: templates/publish-build-artifacts-for-nuget.yml
        parameters:
          artifactName: ReactWindows
          contents: |
            React.Windows.Desktop.DLL\**
            React.Windows.Desktop.Test.DLL\**

  - job: CliInit
    displayName: Verify react-native init
    dependsOn: Setup
    condition: ne( dependencies.Setup.outputs['checkPayload.shouldSkipPRBuild'], 'True' )
    strategy:
      matrix:
        DebugCpp:
          language: cpp
          configuration: Debug
        DebugCs:
          language: cs
          configuration: Debug
        ReleaseCpp:
          language: cpp
          configuration: Release
        ReleaseCs:
          language: cs
          configuration: Release

    timeoutInMinutes: 40 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them
    pool:
      vmImage: $(VmImage)
    steps:
      - task: UseNode@1
        inputs:
          version: '10.x'

      - template: templates/react-native-init.yml
        parameters:
          version: 0.60.6
          platform: x64
          vsComponents: ''

  - job: RNWFormatting
    displayName: Verify change files + lint
    dependsOn: Setup
    condition: ne( dependencies.Setup.outputs['checkPayload.shouldSkipPRBuild'], 'True' )
    pool:
      vmImage: $(VmImage)
    timeoutInMinutes: 10 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them
    steps:
      - checkout: self # self represents the repo where the initial Pipelines YAML file was found
        clean: true # whether to fetch clean each time
        fetchDepth: 2 # the depth of commits to ask Git to fetch
        lfs: false # whether to download Git-LFS files
        submodules: false # set to 'true' for a single level of submodules or 'recursive' to get submodules of submodules
        persistCredentials: false # set to 'true' to leave the OAuth token in the Git config after the initial fetch

      - task: CmdLine@2
        displayName: yarn install
        inputs:
          script: yarn install --frozen-lockfile

      - task: CmdLine@2
        displayName: Check for change files
        inputs:
          script: node ./node_modules/beachball/bin/beachball.js check --changehint "Run `yarn change` from root of repo to generate a change file."

      - task: CmdLine@2
        displayName: yarn format:verify
        inputs:
          script: yarn format:verify

      - task: CmdLine@2
        displayName: yarn buildci
        inputs:
          script: yarn buildci

      - task: CmdLine@2
        displayName: yarn lint
        inputs:
          script: yarn lint

      - task: CmdLine@2
        displayName: yarn api
        inputs:
          script: yarn api

  - template: templates/e2e-test-job.yml # Template reference
    parameters:
      name: E2ETest
      BuildPlatform: x64
      applyRnPatches: true

  - job: RNWNugetPR
    displayName: Build and Pack Nuget
    dependsOn:
      - Setup
      - RNWUniversalPR
      - RNWDesktopPR
    condition: ne( dependencies.Setup.outputs['checkPayload.shouldSkipPRBuild'], 'True' )
    pool:
      vmImage: $(VmImage)
    timeoutInMinutes: 30
    cancelTimeoutInMinutes: 5
    steps:
      - checkout: self
        fetchDepth: 15

      # The commit tag in the nuspec requires that we use at least nuget 4.6
      - task: NuGetToolInstaller@0
        inputs:
          versionSpec: ">=4.6.0"

      # Exclude ReactUWP from nuget because we didn't build all the flavours.
      - task: PowerShell@2
        displayName: Exclude ReactUWP from ReactUwp.nuspec
        inputs:
          targetType: inline # filePath | inline
          script: |
            ((Get-Content -path vnext\Scripts\ReactUwp.nuspec -Raw) -replace ".*ReactUWP\\React.UWP.*","") | Set-Content -Path vnext\Scripts\ReactUwp.nuspec

      - template: templates/prep-and-pack-nuget.yml
