#
# The PR pipeline entry point.
# This file is a copy of pr-pipeline.yml kept for backward compatibility
# with *-stable branches that haven't been updated yet.
# Once all branches use pr-pipeline.yml, this file can be deleted.
#

name: $(Date:yyyyMMdd).$(Rev:r)

trigger: none

pr:
  - main
  - master
  - "*-stable"

variables:
  - group: platform-override-zero-permission-token

extends:
  template: build-template.yml@self
  parameters:
    buildEnvironment: PullRequest
    AgentPool:
      Medium:
        name: rnw-pool-4
        demands: ImageOverride -equals rnw-img-vs2022-node22
      Large:
        name: rnw-pool-8
        demands: ImageOverride -equals rnw-img-vs2022-node22
