name: $(Date:yyyyMMdd).$(Rev:r)

trigger: none # will disable CI builds entirely

pr:
  - main
  - master
  - "*-stable"

variables:
  - group: platform-override-zero-permission-token

parameters:
  - name: AgentPool
    type: object
    default:
      Small:
        name: rnw-pool-2
        demands: ImageOverride -equals rnw-img-vs2022-node20
      Medium:
        name: rnw-pool-4
        demands: ImageOverride -equals rnw-img-vs2022-node20
      Large:
        name: rnw-pool-8
        demands: ImageOverride -equals rnw-img-vs2022-node20

stages:
  - template: stages.yml
    parameters:
      buildEnvironment: SecurePullRequest
      AgentPool: ${{ parameters.AgentPool }}
