name: Generate Release Notes

# commenting out the trigger for now, find way to run this script in some 'yarn release-notes' command
# on:
#   push:
#     paths:
#       - '.github/workflows/generate-release-notes.yml'
#   pull_request:
#     paths:
#       - '.github/workflows/generate-release-notes.yml'

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: anupriya13/react-native-windows
          fetch-depth: 0
          ref: ${{ github.head_ref != '' && github.head_ref || github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.12

      - name: Install dependencies
        run: pip install requests

      - name: Generate release notes file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: '0.79.0' # Adjust this release as needed
          START_DATE: '2025-05-06' # Adjust this date as needed
          END_DATE: '2025-05-30' # Adjust this date as needed
        run: |
          python .github/scripts/generate_release_notes.py > release_notes.md
          mkdir -p .github/release_notes
          mv release_notes.md .github/release_notes/release_notes.md

      - name: Upload release notes
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: .github/release_notes/release_notes.md
